// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by SA-F's tools/gen_pins.py from SA-F's probes p2 (C against C, 2026-10-09 15:42-15:44 UTC) and p1b (dump-o1, 15:32-15:33 UTC); DO NOT EDIT.

package parity

import "strings"

// fnsRecorded is an answer C gave to the admin's netdata-streaming call: the response as the agent wrote it, the
// seconds the request was in flight, the port the agent listened on, the second it was launched in, and (a `gone`
// round) the seconds each child that left was disconnected in.
type fnsRecorded struct {
	resp   string
	flight [2]int64
	port   string
	launch int64
	left   map[string][2]int64
}

// fnsStandalone is the admin's v1 call of TestFnBuiltins/access (fnStreamingView), each side's (00001-TestFnBuiltins_access~v1 admin netdata-streaming~view.0-1791560557-1791560557, 00003-TestFnBuiltins_access~v1 admin netdata-streaming~view.1-1791560560-1791560560).
var fnsStandalone = [2]fnsRecorded{
	{flight: [2]int64{1791560557, 1791560557}, port: "37421", launch: 1791560551, left: nil,
		resp: fnsResp("HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: Fri, 09 Oct 2026 15:42:37 GMT\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Fri, 09 Oct 2026 15:42:37 GMT\r\nContent-Length: 61813\r\nX-Transaction-ID: 5a1e0000000040008000000000007003", `[
        ["parity-parent",{
                "severity":"normal"
            },"permanent","netdata","v2.11.0-458-g1e97a0fc9e","Debian GNU/Linux","debian","unknown","13 (trixie)","13","/etc/os-release","16","429496729600","1999000000","50520903680","none","none","none","none","none","none","false","Linux","6.12.111+deb13-cloud-amd64","x86_64","kvm","systemd-detect-virt","none","systemd-detect-virt","unknown","unknown","unknown",0,1791560557000,null,0,0,0,"initializing","disabled","disabled",0,1791560551000,6,"LOCALHOST",0,0,0,"localhost",0,"",0,"PLAIN",
            [],0,0,0,0,1791560551000,6,"NEVER CONNECTED",1,0,0,"",0,"",0,"PLAIN","UNCOMPRESSED",
            [],0,0,0,0,
            [],null,null,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000aa",null]]`, map[string]string{"dbFrom": "0", "dbTo": "1791560557000", "dbDuration": "0", "dbMetrics": "0", "dbInstances": "0", "dbContexts": "0", "InConnections": "0", "InSince": "1791560551000", "InAge": "6", "InHops": "0", "InReplCompletion": "100", "InReplInstances": "0", "InLocalPort": "0", "InRemotePort": "0", "CollectedMetrics": "0", "CollectedInstances": "0", "CollectedContexts": "0", "OutConnections": "0", "OutSince": "1791560551000", "OutAge": "6", "OutHops": "1", "OutReplCompletion": "100", "OutReplInstances": "0", "OutRemotePort": "0", "OutTrafficData": "0", "OutTrafficMetadata": "0", "OutTrafficReplication": "0", "OutTrafficFunctions": "0", "OutAttemptSince": "0", "OutAttemptAge": "0", "MlAnomalous": "0", "MlNormal": "0", "MlTrained": "0", "MlPending": "0", "MlSilenced": "0"}, "1791560567")},
	{flight: [2]int64{1791560560, 1791560560}, port: "32933", launch: 1791560554, left: nil,
		resp: fnsResp("HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: Fri, 09 Oct 2026 15:42:40 GMT\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Fri, 09 Oct 2026 15:42:40 GMT\r\nContent-Length: 61813\r\nX-Transaction-ID: 5a1e0000000040008000000000007003", `[
        ["parity-parent",{
                "severity":"normal"
            },"permanent","netdata","v2.11.0-458-g1e97a0fc9e","Debian GNU/Linux","debian","unknown","13 (trixie)","13","/etc/os-release","16","429496729600","1999000000","50520903680","none","none","none","none","none","none","false","Linux","6.12.111+deb13-cloud-amd64","x86_64","kvm","systemd-detect-virt","none","systemd-detect-virt","unknown","unknown","unknown",0,1791560560000,null,0,0,0,"initializing","disabled","disabled",0,1791560554000,6,"LOCALHOST",0,0,0,"localhost",0,"",0,"PLAIN",
            [],0,0,0,0,1791560554000,6,"NEVER CONNECTED",1,0,0,"",0,"",0,"PLAIN","UNCOMPRESSED",
            [],0,0,0,0,
            [],null,null,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000aa",null]]`, map[string]string{"dbFrom": "0", "dbTo": "1791560560000", "dbDuration": "0", "dbMetrics": "0", "dbInstances": "0", "dbContexts": "0", "InConnections": "0", "InSince": "1791560554000", "InAge": "6", "InHops": "0", "InReplCompletion": "100", "InReplInstances": "0", "InLocalPort": "0", "InRemotePort": "0", "CollectedMetrics": "0", "CollectedInstances": "0", "CollectedContexts": "0", "OutConnections": "0", "OutSince": "1791560554000", "OutAge": "6", "OutHops": "1", "OutReplCompletion": "100", "OutReplInstances": "0", "OutRemotePort": "0", "OutTrafficData": "0", "OutTrafficMetadata": "0", "OutTrafficReplication": "0", "OutTrafficFunctions": "0", "OutAttemptSince": "0", "OutAttemptAge": "0", "MlAnomalous": "0", "MlNormal": "0", "MlTrained": "0", "MlPending": "0", "MlSilenced": "0"}, "1791560570")},
}

// fnsInfo is the admin's `netdata-streaming info` of TestFnBuiltins/streaming-info, the oracle's (00005-TestFnBuiltins_streaming-info~admin info~view.0-1791560594-1791560594).
var fnsInfo = [1]fnsRecorded{
	{flight: [2]int64{1791560594, 1791560594}, port: "43103", launch: 1791560588, left: nil,
		resp: fnsResp("HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: Fri, 09 Oct 2026 15:43:14 GMT\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Fri, 09 Oct 2026 15:43:14 GMT\r\nContent-Length: 61813\r\nX-Transaction-ID: 5a1e0000000040008000000000007311", `[
        ["parity-parent",{
                "severity":"normal"
            },"permanent","netdata","v2.11.0-458-g1e97a0fc9e","Debian GNU/Linux","debian","unknown","13 (trixie)","13","/etc/os-release","16","429496729600","1999000000","50520903680","none","none","none","none","none","none","false","Linux","6.12.111+deb13-cloud-amd64","x86_64","kvm","systemd-detect-virt","none","systemd-detect-virt","unknown","unknown","unknown",0,1791560594000,null,0,0,0,"initializing","disabled","disabled",0,1791560588000,6,"LOCALHOST",0,0,0,"localhost",0,"",0,"PLAIN",
            [],0,0,0,0,1791560588000,6,"NEVER CONNECTED",1,0,0,"",0,"",0,"PLAIN","UNCOMPRESSED",
            [],0,0,0,0,
            [],null,null,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000aa",null]]`, map[string]string{"dbFrom": "0", "dbTo": "1791560594000", "dbDuration": "0", "dbMetrics": "0", "dbInstances": "0", "dbContexts": "0", "InConnections": "0", "InSince": "1791560588000", "InAge": "6", "InHops": "0", "InReplCompletion": "100", "InReplInstances": "0", "InLocalPort": "0", "InRemotePort": "0", "CollectedMetrics": "0", "CollectedInstances": "0", "CollectedContexts": "0", "OutConnections": "0", "OutSince": "1791560588000", "OutAge": "6", "OutHops": "1", "OutReplCompletion": "100", "OutReplInstances": "0", "OutRemotePort": "0", "OutTrafficData": "0", "OutTrafficMetadata": "0", "OutTrafficReplication": "0", "OutTrafficFunctions": "0", "OutAttemptSince": "0", "OutAttemptAge": "0", "MlAnomalous": "0", "MlNormal": "0", "MlTrained": "0", "MlPending": "0", "MlSilenced": "0"}, "1791560604")},
}

// fnsGone is the last round of TestFnNetdataStreaming/gone (fnStreamingCompareWith), each side's (00006-TestFnNetdataStreaming_gone_netdata-streaming~round.0-1791560674-1791560674, 00007-TestFnNetdataStreaming_gone_netdata-streaming~round.1-1791560674-1791560674).
var fnsGone = [2]fnsRecorded{
	{flight: [2]int64{1791560674, 1791560674}, port: "33109", launch: 1791560658, left: map[string][2]int64{"parity-child": {1791560672, 1791560672}, "parity-child2": {1791560672, 1791560672}, "parity-child3": {1791560672, 1791560672}},
		resp: fnsResp("HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: Fri, 09 Oct 2026 15:44:34 GMT\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Fri, 09 Oct 2026 15:44:34 GMT\r\nContent-Length: 63532\r\nX-Transaction-ID: 5a1e0000000040008000000000003100", `[
        ["parity-parent",{
                "severity":"normal"
            },"permanent","netdata","v2.11.0-458-g1e97a0fc9e","Debian GNU/Linux","debian","unknown","13 (trixie)","13","/etc/os-release","16","429496729600","1999000000","50520903680","none","none","none","none","none","none","false","Linux","6.12.111+deb13-cloud-amd64","x86_64","kvm","systemd-detect-virt","none","systemd-detect-virt","unknown","unknown","unknown",0,1791560674000,null,0,0,0,"initializing","disabled","disabled",0,1791560658000,16,"LOCALHOST",0,0,0,"localhost",0,"",0,"PLAIN",
            [],0,0,0,0,1791560658000,16,"NEVER CONNECTED",1,0,0,"",0,"",0,"PLAIN","UNCOMPRESSED",
            [],0,0,0,0,
            [],null,null,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000aa",null],
        ["parity-child",{
                "severity":"critical"
            },"permanent","query-corpus-pusher","1.0","","","","","","","","","","","","","","","","","","","","","","","","","","","",1791560520000,1791560580000,60,7,2,1,"offline","disabled","disabled",1,1791560672000,2,"DISCONNECTED SOCKET CLOSED BY REMOTE END",1,0,0,"",0,"",0,"PLAIN",
            [],0,0,0,0,1791560658000,16,"NEVER CONNECTED",2,0,0,"",0,"",0,"PLAIN","UNCOMPRESSED",
            [],0,0,0,0,
            [],null,null,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000bb",null],
        ["parity-child2",{
                "severity":"critical"
            },"permanent","query-corpus-pusher","1.0","","","","","","","","","","","","","","","","","","","","","","","","","","","",1791560520000,1791560580000,60,7,2,1,"offline","disabled","disabled",1,1791560672000,2,"DISCONNECTED PARSE ERROR",1,0,0,"",0,"",0,"PLAIN",
            [],0,0,0,0,1791560658000,16,"NEVER CONNECTED",2,0,0,"",0,"",0,"PLAIN","UNCOMPRESSED",
            [],0,0,0,0,
            [],null,null,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000cc",null],
        ["parity-child3",{
                "severity":"critical"
            },"permanent","query-corpus-pusher","1.0","","","","","","","","","","","","","","","","","","","","","","","","","","","",1791560520000,1791560580000,60,7,2,1,"offline","disabled","disabled",1,1791560672000,2,"DISCONNECTED SOCKET CLOSED BY REMOTE END",1,0,0,"",0,"",0,"PLAIN",
            [],0,0,0,0,1791560658000,16,"NEVER CONNECTED",2,0,0,"",0,"",0,"PLAIN","UNCOMPRESSED",
            [],0,0,0,0,
            [],null,null,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000f3",null]]`, map[string]string{"dbFrom": "1791560520000", "dbTo": "1791560674000", "dbDuration": "60", "dbMetrics": "7", "dbInstances": "2", "dbContexts": "1", "InConnections": "1", "InSince": "1791560672000", "InAge": "16", "InHops": "1", "InReplCompletion": "100", "InReplInstances": "0", "InLocalPort": "0", "InRemotePort": "0", "CollectedMetrics": "7", "CollectedInstances": "2", "CollectedContexts": "1", "OutConnections": "0", "OutSince": "1791560658000", "OutAge": "16", "OutHops": "2", "OutReplCompletion": "100", "OutReplInstances": "0", "OutRemotePort": "0", "OutTrafficData": "0", "OutTrafficMetadata": "0", "OutTrafficReplication": "0", "OutTrafficFunctions": "0", "OutAttemptSince": "0", "OutAttemptAge": "0", "MlAnomalous": "0", "MlNormal": "0", "MlTrained": "0", "MlPending": "0", "MlSilenced": "0"}, "1791560684")},
	{flight: [2]int64{1791560674, 1791560674}, port: "33371", launch: 1791560661, left: map[string][2]int64{"parity-child": {1791560672, 1791560672}, "parity-child2": {1791560672, 1791560672}, "parity-child3": {1791560672, 1791560672}},
		resp: fnsResp("HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: Fri, 09 Oct 2026 15:44:34 GMT\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Fri, 09 Oct 2026 15:44:34 GMT\r\nContent-Length: 63532\r\nX-Transaction-ID: 5a1e0000000040008000000000003100", `[
        ["parity-parent",{
                "severity":"normal"
            },"permanent","netdata","v2.11.0-458-g1e97a0fc9e","Debian GNU/Linux","debian","unknown","13 (trixie)","13","/etc/os-release","16","429496729600","1999000000","50520903680","none","none","none","none","none","none","false","Linux","6.12.111+deb13-cloud-amd64","x86_64","kvm","systemd-detect-virt","none","systemd-detect-virt","unknown","unknown","unknown",0,1791560674000,null,0,0,0,"initializing","disabled","disabled",0,1791560661000,13,"LOCALHOST",0,0,0,"localhost",0,"",0,"PLAIN",
            [],0,0,0,0,1791560661000,13,"NEVER CONNECTED",1,0,0,"",0,"",0,"PLAIN","UNCOMPRESSED",
            [],0,0,0,0,
            [],null,null,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000aa",null],
        ["parity-child",{
                "severity":"critical"
            },"permanent","query-corpus-pusher","1.0","","","","","","","","","","","","","","","","","","","","","","","","","","","",1791560520000,1791560580000,60,7,2,1,"offline","disabled","disabled",1,1791560672000,2,"DISCONNECTED SOCKET CLOSED BY REMOTE END",1,0,0,"",0,"",0,"PLAIN",
            [],0,0,0,0,1791560661000,13,"NEVER CONNECTED",2,0,0,"",0,"",0,"PLAIN","UNCOMPRESSED",
            [],0,0,0,0,
            [],null,null,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000bb",null],
        ["parity-child2",{
                "severity":"critical"
            },"permanent","query-corpus-pusher","1.0","","","","","","","","","","","","","","","","","","","","","","","","","","","",1791560520000,1791560580000,60,7,2,1,"offline","disabled","disabled",1,1791560672000,2,"DISCONNECTED PARSE ERROR",1,0,0,"",0,"",0,"PLAIN",
            [],0,0,0,0,1791560661000,13,"NEVER CONNECTED",2,0,0,"",0,"",0,"PLAIN","UNCOMPRESSED",
            [],0,0,0,0,
            [],null,null,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000cc",null],
        ["parity-child3",{
                "severity":"critical"
            },"permanent","query-corpus-pusher","1.0","","","","","","","","","","","","","","","","","","","","","","","","","","","",1791560520000,1791560580000,60,7,2,1,"offline","disabled","disabled",1,1791560672000,2,"DISCONNECTED SOCKET CLOSED BY REMOTE END",1,0,0,"",0,"",0,"PLAIN",
            [],0,0,0,0,1791560661000,13,"NEVER CONNECTED",2,0,0,"",0,"",0,"PLAIN","UNCOMPRESSED",
            [],0,0,0,0,
            [],null,null,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000f3",null]]`, map[string]string{"dbFrom": "1791560520000", "dbTo": "1791560674000", "dbDuration": "60", "dbMetrics": "7", "dbInstances": "2", "dbContexts": "1", "InConnections": "1", "InSince": "1791560672000", "InAge": "13", "InHops": "1", "InReplCompletion": "100", "InReplInstances": "0", "InLocalPort": "0", "InRemotePort": "0", "CollectedMetrics": "7", "CollectedInstances": "2", "CollectedContexts": "1", "OutConnections": "0", "OutSince": "1791560661000", "OutAge": "13", "OutHops": "2", "OutReplCompletion": "100", "OutReplInstances": "0", "OutRemotePort": "0", "OutTrafficData": "0", "OutTrafficMetadata": "0", "OutTrafficReplication": "0", "OutTrafficFunctions": "0", "OutAttemptSince": "0", "OutAttemptAge": "0", "MlAnomalous": "0", "MlNormal": "0", "MlTrained": "0", "MlPending": "0", "MlSilenced": "0"}, "1791560684")},
}

// fnsOutNever is the stream pairs' first table at stage never, each side's (00002-never-never-0.0-1791559993001-1791559993003, 00003-never-never-0.1-1791559993003-1791559993004), and fnsOutNeverSides their values.
var fnsOutNever = [2]fnsRecorded{
	{flight: [2]int64{1791559993, 1791559993}, port: "34869", launch: 1791559985,
		resp: fnsResp("HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: Fri, 09 Oct 2026 15:33:13 GMT\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Fri, 09 Oct 2026 15:33:13 GMT\r\nContent-Length: 61874\r\nX-Transaction-ID: 5a1e0000000040008000000000003100", `[
        ["parity-parent",{
                "severity":"warning"
            },"permanent","netdata","v2.11.0-458-g1e97a0fc9e","Debian GNU/Linux","debian","unknown","13 (trixie)","13","/etc/os-release","16","429496729600","1999000000","50520903680","none","none","none","none","none","none","false","Linux","6.12.111+deb13-cloud-amd64","x86_64","kvm","systemd-detect-virt","none","systemd-detect-virt","unknown","unknown","unknown",0,1791559993000,null,0,0,0,"initializing","offline","disabled",0,1791559985000,8,"LOCALHOST",0,0,0,"localhost",0,"",0,"PLAIN",
            [],0,0,0,0,1791559985000,8,"NEVER CONNECTED",1,0,0,"not connected",0,"not connected",0,"PLAIN","UNCOMPRESSED",
            [],0,0,0,0,
            ["NEVER CONNECTED"],1791559987619,6,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000aa",null]]`, map[string]string{"dbFrom": "0", "dbTo": "1791559993000", "dbDuration": "0", "dbMetrics": "0", "dbInstances": "0", "dbContexts": "0", "InConnections": "0", "InSince": "1791559985000", "InAge": "8", "InHops": "0", "InReplCompletion": "100", "InReplInstances": "0", "InLocalPort": "0", "InRemotePort": "0", "CollectedMetrics": "0", "CollectedInstances": "0", "CollectedContexts": "0", "OutConnections": "0", "OutSince": "1791559985000", "OutAge": "8", "OutHops": "1", "OutReplCompletion": "100", "OutReplInstances": "0", "OutRemotePort": "0", "OutTrafficData": "0", "OutTrafficMetadata": "0", "OutTrafficReplication": "0", "OutTrafficFunctions": "0", "OutAttemptSince": "1791559987619", "OutAttemptAge": "6", "MlAnomalous": "0", "MlNormal": "0", "MlTrained": "0", "MlPending": "0", "MlSilenced": "0"}, "1791560003")},
	{flight: [2]int64{1791559993, 1791559993}, port: "45287", launch: 1791559987,
		resp: fnsResp("HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: Fri, 09 Oct 2026 15:33:13 GMT\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Fri, 09 Oct 2026 15:33:13 GMT\r\nContent-Length: 61874\r\nX-Transaction-ID: 5a1e0000000040008000000000003100", `[
        ["parity-parent",{
                "severity":"warning"
            },"permanent","netdata","v2.11.0-458-g1e97a0fc9e","Debian GNU/Linux","debian","unknown","13 (trixie)","13","/etc/os-release","16","429496729600","1999000000","50520903680","none","none","none","none","none","none","false","Linux","6.12.111+deb13-cloud-amd64","x86_64","kvm","systemd-detect-virt","none","systemd-detect-virt","unknown","unknown","unknown",0,1791559993000,null,0,0,0,"initializing","offline","disabled",0,1791559987000,6,"LOCALHOST",0,0,0,"localhost",0,"",0,"PLAIN",
            [],0,0,0,0,1791559987000,6,"NEVER CONNECTED",1,0,0,"not connected",0,"not connected",0,"PLAIN","UNCOMPRESSED",
            [],0,0,0,0,
            ["NEVER CONNECTED"],1791559990675,3,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000aa",null]]`, map[string]string{"dbFrom": "0", "dbTo": "1791559993000", "dbDuration": "0", "dbMetrics": "0", "dbInstances": "0", "dbContexts": "0", "InConnections": "0", "InSince": "1791559987000", "InAge": "6", "InHops": "0", "InReplCompletion": "100", "InReplInstances": "0", "InLocalPort": "0", "InRemotePort": "0", "CollectedMetrics": "0", "CollectedInstances": "0", "CollectedContexts": "0", "OutConnections": "0", "OutSince": "1791559987000", "OutAge": "6", "OutHops": "1", "OutReplCompletion": "100", "OutReplInstances": "0", "OutRemotePort": "0", "OutTrafficData": "0", "OutTrafficMetadata": "0", "OutTrafficReplication": "0", "OutTrafficFunctions": "0", "OutAttemptSince": "1791559990675", "OutAttemptAge": "3", "MlAnomalous": "0", "MlNormal": "0", "MlTrained": "0", "MlPending": "0", "MlSilenced": "0"}, "1791560003")},
}

var fnsOutNeverSides = [2]fnStreamingOutSide{
	{stage: "never", listen: "34869", stub: "42181", started: [2]int64{1791559985, 1791559990}, ready: 1791559987, connected: [2]int64{0, 0}, closed: [2]int64{0, 0}},
	{stage: "never", listen: "45287", stub: "42181", started: [2]int64{1791559987, 1791559992}, ready: 1791559990, connected: [2]int64{0, 0}, closed: [2]int64{0, 0}},
}

// fnsOutConnected is the stream pairs' first table at stage connected, each side's (00015-out-connected-0.0-1791560016003-1791560016005, 00016-out-connected-0.1-1791560016006-1791560016007), and fnsOutConnectedSides their values.
var fnsOutConnected = [2]fnsRecorded{
	{flight: [2]int64{1791560016, 1791560016}, port: "35207", launch: 1791559997,
		resp: fnsResp("HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: Fri, 09 Oct 2026 15:33:36 GMT\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Fri, 09 Oct 2026 15:33:36 GMT\r\nContent-Length: 62092\r\nX-Transaction-ID: 5a1e0000000040008000000000003100", `[
        ["parity-parent",{
                "severity":"normal"
            },"permanent","netdata","v2.11.0-458-g1e97a0fc9e","Debian GNU/Linux","debian","unknown","13 (trixie)","13","/etc/os-release","16","429496729600","1999000000","50520903680","none","none","none","none","none","none","false","Linux","6.12.111+deb13-cloud-amd64","x86_64","kvm","systemd-detect-virt","none","systemd-detect-virt","unknown","unknown","unknown",1791560001000,1791560016000,15,67,13,12,"online","online","disabled",0,1791559997000,19,"LOCALHOST",0,0,0,"localhost",0,"",0,"PLAIN",
            [],67,13,12,1,1791560009000,7,"CONNECTED",1,100,0,"127.0.0.1",44736,"127.0.0.1",36723,"PLAIN","UNCOMPRESSED",
            ["VCAPS","HLABELS","CLAIM","CLABELS","FUNCTIONS","FUNCDEL","REPLICATION","BINARY","INTERPOLATED","IEEE754","DYNCFG","SLOTS","PROGRESS","NODEID","PATHS","FLOATBASELINE"],17469,12132,5198,0,
            ["SOCKET CONNECTED"],1791560009002,7,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000aa",null]]`, map[string]string{"dbFrom": "1791560001000", "dbTo": "1791560016000", "dbDuration": "15", "dbMetrics": "67", "dbInstances": "13", "dbContexts": "12", "InConnections": "0", "InSince": "1791559997000", "InAge": "19", "InHops": "0", "InReplCompletion": "100", "InReplInstances": "0", "InLocalPort": "0", "InRemotePort": "0", "CollectedMetrics": "67", "CollectedInstances": "13", "CollectedContexts": "12", "OutConnections": "1", "OutSince": "1791560009000", "OutAge": "7", "OutHops": "1", "OutReplCompletion": "100", "OutReplInstances": "0", "OutRemotePort": "36723", "OutTrafficData": "17469", "OutTrafficMetadata": "12132", "OutTrafficReplication": "5198", "OutTrafficFunctions": "0", "OutAttemptSince": "1791560009002", "OutAttemptAge": "7", "MlAnomalous": "0", "MlNormal": "0", "MlTrained": "0", "MlPending": "0", "MlSilenced": "0"}, "1791560026")},
	{flight: [2]int64{1791560016, 1791560016}, port: "33435", launch: 1791560000,
		resp: fnsResp("HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: Fri, 09 Oct 2026 15:33:36 GMT\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Fri, 09 Oct 2026 15:33:36 GMT\r\nContent-Length: 62092\r\nX-Transaction-ID: 5a1e0000000040008000000000003100", `[
        ["parity-parent",{
                "severity":"normal"
            },"permanent","netdata","v2.11.0-458-g1e97a0fc9e","Debian GNU/Linux","debian","unknown","13 (trixie)","13","/etc/os-release","16","429496729600","1999000000","50520903680","none","none","none","none","none","none","false","Linux","6.12.111+deb13-cloud-amd64","x86_64","kvm","systemd-detect-virt","none","systemd-detect-virt","unknown","unknown","unknown",1791560004000,1791560016000,12,67,13,12,"online","online","disabled",0,1791560000000,16,"LOCALHOST",0,0,0,"localhost",0,"",0,"PLAIN",
            [],67,13,12,1,1791560010000,6,"CONNECTED",1,100,0,"127.0.0.1",44752,"127.0.0.1",36723,"PLAIN","UNCOMPRESSED",
            ["VCAPS","HLABELS","CLAIM","CLABELS","FUNCTIONS","FUNCDEL","REPLICATION","BINARY","INTERPOLATED","IEEE754","DYNCFG","SLOTS","PROGRESS","NODEID","PATHS","FLOATBASELINE"],14561,12132,5186,0,
            ["SOCKET CONNECTED"],1791560010001,6,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000aa",null]]`, map[string]string{"dbFrom": "1791560004000", "dbTo": "1791560016000", "dbDuration": "12", "dbMetrics": "67", "dbInstances": "13", "dbContexts": "12", "InConnections": "0", "InSince": "1791560000000", "InAge": "16", "InHops": "0", "InReplCompletion": "100", "InReplInstances": "0", "InLocalPort": "0", "InRemotePort": "0", "CollectedMetrics": "67", "CollectedInstances": "13", "CollectedContexts": "12", "OutConnections": "1", "OutSince": "1791560010000", "OutAge": "6", "OutHops": "1", "OutReplCompletion": "100", "OutReplInstances": "0", "OutRemotePort": "36723", "OutTrafficData": "14561", "OutTrafficMetadata": "12132", "OutTrafficReplication": "5186", "OutTrafficFunctions": "0", "OutAttemptSince": "1791560010001", "OutAttemptAge": "6", "MlAnomalous": "0", "MlNormal": "0", "MlTrained": "0", "MlPending": "0", "MlSilenced": "0"}, "1791560026")},
}

var fnsOutConnectedSides = [2]fnStreamingOutSide{
	{stage: "connected", listen: "35207", stub: "36723", started: [2]int64{1791559997, 1791560002}, ready: 1791560000, connected: [2]int64{1791560008, 1791560009}, closed: [2]int64{0, 0}},
	{stage: "connected", listen: "33435", stub: "36723", started: [2]int64{1791560000, 1791560005}, ready: 1791560003, connected: [2]int64{1791560008, 1791560010}, closed: [2]int64{0, 0}},
}

// fnsOutDenied is the stream pairs' first table at stage denied, each side's (00028-out-denied-0.0-1791560021278-1791560021279, 00029-out-denied-0.1-1791560021279-1791560021280), and fnsOutDeniedSides their values.
var fnsOutDenied = [2]fnsRecorded{
	{flight: [2]int64{1791560021, 1791560021}, port: "35207", launch: 1791559997,
		resp: fnsResp("HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: Fri, 09 Oct 2026 15:33:41 GMT\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Fri, 09 Oct 2026 15:33:41 GMT\r\nContent-Length: 61911\r\nX-Transaction-ID: 5a1e0000000040008000000000003100", `[
        ["parity-parent",{
                "severity":"warning"
            },"permanent","netdata","v2.11.0-458-g1e97a0fc9e","Debian GNU/Linux","debian","unknown","13 (trixie)","13","/etc/os-release","16","429496729600","1999000000","50520903680","none","none","none","none","none","none","false","Linux","6.12.111+deb13-cloud-amd64","x86_64","kvm","systemd-detect-virt","none","systemd-detect-virt","unknown","unknown","unknown",1791560001000,1791560021000,20,67,13,12,"online","offline","disabled",0,1791559997000,24,"LOCALHOST",0,0,0,"localhost",0,"",0,"PLAIN",
            [],67,13,12,1,1791560009000,12,"DENIED",1,0,0,"not connected",0,"not connected",0,"PLAIN","UNCOMPRESSED",
            [],26273,12132,5198,0,
            ["DENIED"],1791560019021,2,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000aa",null]]`, map[string]string{"dbFrom": "1791560001000", "dbTo": "1791560021000", "dbDuration": "20", "dbMetrics": "67", "dbInstances": "13", "dbContexts": "12", "InConnections": "0", "InSince": "1791559997000", "InAge": "24", "InHops": "0", "InReplCompletion": "100", "InReplInstances": "0", "InLocalPort": "0", "InRemotePort": "0", "CollectedMetrics": "67", "CollectedInstances": "13", "CollectedContexts": "12", "OutConnections": "1", "OutSince": "1791560009000", "OutAge": "12", "OutHops": "1", "OutReplCompletion": "100", "OutReplInstances": "0", "OutRemotePort": "0", "OutTrafficData": "26273", "OutTrafficMetadata": "12132", "OutTrafficReplication": "5198", "OutTrafficFunctions": "0", "OutAttemptSince": "1791560019021", "OutAttemptAge": "2", "MlAnomalous": "0", "MlNormal": "0", "MlTrained": "0", "MlPending": "0", "MlSilenced": "0"}, "1791560031")},
	{flight: [2]int64{1791560021, 1791560021}, port: "33435", launch: 1791560000,
		resp: fnsResp("HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: Fri, 09 Oct 2026 15:33:41 GMT\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Fri, 09 Oct 2026 15:33:41 GMT\r\nContent-Length: 61911\r\nX-Transaction-ID: 5a1e0000000040008000000000003100", `[
        ["parity-parent",{
                "severity":"warning"
            },"permanent","netdata","v2.11.0-458-g1e97a0fc9e","Debian GNU/Linux","debian","unknown","13 (trixie)","13","/etc/os-release","16","429496729600","1999000000","50520903680","none","none","none","none","none","none","false","Linux","6.12.111+deb13-cloud-amd64","x86_64","kvm","systemd-detect-virt","none","systemd-detect-virt","unknown","unknown","unknown",1791560004000,1791560021000,17,67,13,12,"online","offline","disabled",0,1791560000000,21,"LOCALHOST",0,0,0,"localhost",0,"",0,"PLAIN",
            [],67,13,12,1,1791560010000,11,"DENIED",1,0,0,"not connected",0,"not connected",0,"PLAIN","UNCOMPRESSED",
            [],23363,12132,5186,0,
            ["DENIED"],1791560019021,2,null,null,null,null,null,"5a1e0000-0000-4000-8000-0000000000aa",null]]`, map[string]string{"dbFrom": "1791560004000", "dbTo": "1791560021000", "dbDuration": "17", "dbMetrics": "67", "dbInstances": "13", "dbContexts": "12", "InConnections": "0", "InSince": "1791560000000", "InAge": "21", "InHops": "0", "InReplCompletion": "100", "InReplInstances": "0", "InLocalPort": "0", "InRemotePort": "0", "CollectedMetrics": "67", "CollectedInstances": "13", "CollectedContexts": "12", "OutConnections": "1", "OutSince": "1791560010000", "OutAge": "11", "OutHops": "1", "OutReplCompletion": "100", "OutReplInstances": "0", "OutRemotePort": "0", "OutTrafficData": "23363", "OutTrafficMetadata": "12132", "OutTrafficReplication": "5186", "OutTrafficFunctions": "0", "OutAttemptSince": "1791560019021", "OutAttemptAge": "2", "MlAnomalous": "0", "MlNormal": "0", "MlTrained": "0", "MlPending": "0", "MlSilenced": "0"}, "1791560031")},
}

var fnsOutDeniedSides = [2]fnStreamingOutSide{
	{stage: "denied", listen: "35207", stub: "36723", started: [2]int64{1791559997, 1791560002}, ready: 1791560000, connected: [2]int64{1791560008, 1791560009}, closed: [2]int64{1791560019, 1791560019}},
	{stage: "denied", listen: "33435", stub: "36723", started: [2]int64{1791560000, 1791560005}, ready: 1791560003, connected: [2]int64{1791560008, 1791560010}, closed: [2]int64{1791560019, 1791560019}},
}

// fnsTemplate is the body every recorded table shares but for its rows ({{data}}), the maxima of its columns
// ({{max:NAME}}) and its expiry ({{expires}}): C writes the same columns, help, charts and groups in every one.
const fnsTemplate = `{
    "hostname":"parity-parent",
    "status":200,
    "type":"table",
    "update_every":10,
    "has_history":false,
    "help":"Shows real-time streaming connections and replication status between parent and child nodes, including connection health, data flow metrics, and ML status.",
    "data":{{data}},
    "columns":{
        "Node":{
            "index":0,
            "unique_key":true,
            "name":"Node's Hostname",
            "visible":true,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":true,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "rowOptions":{
            "index":1,
            "unique_key":false,
            "name":"rowOptions",
            "visible":false,
            "type":"none",
            "visualization":"rowOptions",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":false,
            "sticky":false,
            "summary":"count",
            "filter":"none",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false,
            "dummy":true
        },
        "Ephemerality":{
            "index":2,
            "unique_key":false,
            "name":"The type of ephemerality for the node",
            "visible":true,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "AgentName":{
            "index":3,
            "unique_key":false,
            "name":"The name of the Netdata agent",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "AgentVersion":{
            "index":4,
            "unique_key":false,
            "name":"The version of the Netdata agent",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OSName":{
            "index":5,
            "unique_key":false,
            "name":"The name of the host's operating system",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OSId":{
            "index":6,
            "unique_key":false,
            "name":"The identifier of the host's operating system",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OSIdLike":{
            "index":7,
            "unique_key":false,
            "name":"The ID-like string for the host's OS",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OSVersion":{
            "index":8,
            "unique_key":false,
            "name":"The version of the host's operating system",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OSVersionId":{
            "index":9,
            "unique_key":false,
            "name":"The version identifier of the host's OS",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OSDetection":{
            "index":10,
            "unique_key":false,
            "name":"Details about host OS detection",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "CPUCores":{
            "index":11,
            "unique_key":false,
            "name":"The number of CPU cores in the host",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "DiskSpace":{
            "index":12,
            "unique_key":false,
            "name":"The total disk space available on the host",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"none",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "CPUFreq":{
            "index":13,
            "unique_key":false,
            "name":"The CPU frequency of the host",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"none",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "RAMTotal":{
            "index":14,
            "unique_key":false,
            "name":"The total RAM available on the host",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"none",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "ContainerOSName":{
            "index":15,
            "unique_key":false,
            "name":"The name of the container's operating system",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "ContainerOSId":{
            "index":16,
            "unique_key":false,
            "name":"The identifier of the container's operating system",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "ContainerOSIdLike":{
            "index":17,
            "unique_key":false,
            "name":"The ID-like string for the container's OS",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "ContainerOSVersion":{
            "index":18,
            "unique_key":false,
            "name":"The version of the container's OS",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "ContainerOSVersionId":{
            "index":19,
            "unique_key":false,
            "name":"The version identifier of the container's OS",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "ContainerOSDetection":{
            "index":20,
            "unique_key":false,
            "name":"Details about container OS detection",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "IsK8sNode":{
            "index":21,
            "unique_key":false,
            "name":"Whether this node is part of a Kubernetes cluster",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "KernelName":{
            "index":22,
            "unique_key":false,
            "name":"The kernel name",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "KernelVersion":{
            "index":23,
            "unique_key":false,
            "name":"The kernel version",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "Architecture":{
            "index":24,
            "unique_key":false,
            "name":"The system architecture",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "Virtualization":{
            "index":25,
            "unique_key":false,
            "name":"The virtualization technology in use",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "VirtDetection":{
            "index":26,
            "unique_key":false,
            "name":"Details about virtualization detection",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "Container":{
            "index":27,
            "unique_key":false,
            "name":"Container type information",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "ContainerDetection":{
            "index":28,
            "unique_key":false,
            "name":"Details about container detection",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "CloudProviderType":{
            "index":29,
            "unique_key":false,
            "name":"The type of cloud provider",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "CloudInstanceType":{
            "index":30,
            "unique_key":false,
            "name":"The type of cloud instance",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "CloudInstanceRegion":{
            "index":31,
            "unique_key":false,
            "name":"The region of the cloud instance",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "dbFrom":{
            "index":32,
            "unique_key":false,
            "name":"DB Data Retention From",
            "visible":false,
            "type":"timestamp",
            "visualization":"value",
            "value_options":{
                "transform":"datetime",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:dbFrom}},
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"min",
            "filter":"none",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "dbTo":{
            "index":33,
            "unique_key":false,
            "name":"DB Data Retention To",
            "visible":false,
            "type":"timestamp",
            "visualization":"value",
            "value_options":{
                "transform":"datetime",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:dbTo}},
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"max",
            "filter":"none",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "dbDuration":{
            "index":34,
            "unique_key":false,
            "name":"DB Data Retention Duration",
            "visible":true,
            "type":"duration",
            "visualization":"value",
            "value_options":{
                "transform":"duration",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:dbDuration}},
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"max",
            "filter":"none",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "dbMetrics":{
            "index":35,
            "unique_key":false,
            "name":"Time-series Metrics in the DB",
            "visible":true,
            "type":"integer",
            "visualization":"value",
            "value_options":{
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:dbMetrics}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "dbInstances":{
            "index":36,
            "unique_key":false,
            "name":"Instances in the DB",
            "visible":true,
            "type":"integer",
            "visualization":"value",
            "value_options":{
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:dbInstances}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "dbContexts":{
            "index":37,
            "unique_key":false,
            "name":"Contexts in the DB",
            "visible":true,
            "type":"integer",
            "visualization":"value",
            "value_options":{
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:dbContexts}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "InStatus":{
            "index":38,
            "unique_key":false,
            "name":"Data Collection Online Status",
            "visible":true,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutStatus":{
            "index":39,
            "unique_key":false,
            "name":"Streaming Online Status",
            "visible":true,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "MlStatus":{
            "index":40,
            "unique_key":false,
            "name":"ML Status",
            "visible":true,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "InConnections":{
            "index":41,
            "unique_key":false,
            "name":"Number of times this child connected",
            "visible":false,
            "type":"integer",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:InConnections}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "InSince":{
            "index":42,
            "unique_key":false,
            "name":"Last Data Collection Status Change",
            "visible":false,
            "type":"timestamp",
            "visualization":"value",
            "value_options":{
                "transform":"datetime",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:InSince}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"min",
            "filter":"none",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "InAge":{
            "index":43,
            "unique_key":false,
            "name":"Last Data Collection Online Status Change Age",
            "visible":true,
            "type":"duration",
            "visualization":"value",
            "value_options":{
                "transform":"duration",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:InAge}},
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"max",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "InReason":{
            "index":44,
            "unique_key":false,
            "name":"Data Collection Online Status Reason",
            "visible":true,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "InHops":{
            "index":45,
            "unique_key":false,
            "name":"Data Collection Distance Hops from Origin Node",
            "visible":true,
            "type":"integer",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:InHops}},
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"min",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "InReplCompletion":{
            "index":46,
            "unique_key":false,
            "name":"Inbound Replication Completion",
            "visible":true,
            "type":"integer",
            "units":"%",
            "visualization":"bar",
            "value_options":{
                "units":"%",
                "transform":"number",
                "decimal_points":1,
                "default_value":null
            },
            "max":{{max:InReplCompletion}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"min",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "InReplInstances":{
            "index":47,
            "unique_key":false,
            "name":"Inbound Replicating Instances",
            "visible":false,
            "type":"integer",
            "units":"instances",
            "visualization":"value",
            "value_options":{
                "units":"instances",
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:InReplInstances}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "InLocalIP":{
            "index":48,
            "unique_key":false,
            "name":"Inbound Local IP",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "InLocalPort":{
            "index":49,
            "unique_key":false,
            "name":"Inbound Local Port",
            "visible":false,
            "type":"integer",
            "visualization":"value",
            "value_options":{
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:InLocalPort}},
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "InRemoteIP":{
            "index":50,
            "unique_key":false,
            "name":"Inbound Remote IP",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "InRemotePort":{
            "index":51,
            "unique_key":false,
            "name":"Inbound Remote Port",
            "visible":false,
            "type":"integer",
            "visualization":"value",
            "value_options":{
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:InRemotePort}},
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "InSSL":{
            "index":52,
            "unique_key":false,
            "name":"Inbound SSL Connection",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "InCapabilities":{
            "index":53,
            "unique_key":false,
            "name":"Inbound Connection Capabilities",
            "visible":false,
            "type":"array",
            "visualization":"pill",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "CollectedMetrics":{
            "index":54,
            "unique_key":false,
            "name":"Time-series Metrics Currently Collected",
            "visible":true,
            "type":"integer",
            "visualization":"value",
            "value_options":{
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:CollectedMetrics}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "CollectedInstances":{
            "index":55,
            "unique_key":false,
            "name":"Instances Currently Collected",
            "visible":true,
            "type":"integer",
            "visualization":"value",
            "value_options":{
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:CollectedInstances}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "CollectedContexts":{
            "index":56,
            "unique_key":false,
            "name":"Contexts Currently Collected",
            "visible":true,
            "type":"integer",
            "visualization":"value",
            "value_options":{
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:CollectedContexts}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutConnections":{
            "index":57,
            "unique_key":false,
            "name":"Number of times connected to a parent",
            "visible":false,
            "type":"integer",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:OutConnections}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutSince":{
            "index":58,
            "unique_key":false,
            "name":"Last Streaming Status Change",
            "visible":false,
            "type":"timestamp",
            "visualization":"value",
            "value_options":{
                "transform":"datetime",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:OutSince}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"max",
            "filter":"none",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutAge":{
            "index":59,
            "unique_key":false,
            "name":"Last Streaming Status Change Age",
            "visible":true,
            "type":"duration",
            "visualization":"value",
            "value_options":{
                "transform":"duration",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:OutAge}},
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"min",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutReason":{
            "index":60,
            "unique_key":false,
            "name":"Streaming Status Reason",
            "visible":true,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutHops":{
            "index":61,
            "unique_key":false,
            "name":"Streaming Distance Hops from Origin Node",
            "visible":true,
            "type":"integer",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:OutHops}},
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"min",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutReplCompletion":{
            "index":62,
            "unique_key":false,
            "name":"Outbound Replication Completion",
            "visible":true,
            "type":"integer",
            "units":"%",
            "visualization":"bar",
            "value_options":{
                "units":"%",
                "transform":"number",
                "decimal_points":1,
                "default_value":null
            },
            "max":{{max:OutReplCompletion}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"min",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutReplInstances":{
            "index":63,
            "unique_key":false,
            "name":"Outbound Replicating Instances",
            "visible":false,
            "type":"integer",
            "units":"instances",
            "visualization":"value",
            "value_options":{
                "units":"instances",
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:OutReplInstances}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutLocalIP":{
            "index":64,
            "unique_key":false,
            "name":"Outbound Local IP",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutLocalPort":{
            "index":65,
            "unique_key":false,
            "name":"Outbound Local Port",
            "visible":false,
            "type":"integer",
            "visualization":"value",
            "value_options":{
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"none",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutRemoteIP":{
            "index":66,
            "unique_key":false,
            "name":"Outbound Remote IP",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutRemotePort":{
            "index":67,
            "unique_key":false,
            "name":"Outbound Remote Port",
            "visible":false,
            "type":"integer",
            "visualization":"value",
            "value_options":{
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:OutRemotePort}},
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutSSL":{
            "index":68,
            "unique_key":false,
            "name":"Outbound SSL Connection",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutCompression":{
            "index":69,
            "unique_key":false,
            "name":"Outbound Compressed Connection",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutCapabilities":{
            "index":70,
            "unique_key":false,
            "name":"Outbound Connection Capabilities",
            "visible":false,
            "type":"array",
            "visualization":"pill",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutTrafficData":{
            "index":71,
            "unique_key":false,
            "name":"Outbound Metric Data Traffic",
            "visible":false,
            "type":"integer",
            "units":"bytes",
            "visualization":"value",
            "value_options":{
                "units":"bytes",
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:OutTrafficData}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutTrafficMetadata":{
            "index":72,
            "unique_key":false,
            "name":"Outbound Metric Metadata Traffic",
            "visible":false,
            "type":"integer",
            "units":"bytes",
            "visualization":"value",
            "value_options":{
                "units":"bytes",
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:OutTrafficMetadata}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutTrafficReplication":{
            "index":73,
            "unique_key":false,
            "name":"Outbound Metric Replication Traffic",
            "visible":false,
            "type":"integer",
            "units":"bytes",
            "visualization":"value",
            "value_options":{
                "units":"bytes",
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:OutTrafficReplication}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutTrafficFunctions":{
            "index":74,
            "unique_key":false,
            "name":"Outbound Metric Functions Traffic",
            "visible":false,
            "type":"integer",
            "units":"bytes",
            "visualization":"value",
            "value_options":{
                "units":"bytes",
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:OutTrafficFunctions}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutAttemptHandshake":{
            "index":75,
            "unique_key":false,
            "name":"Outbound Connection Attempt Handshake Status",
            "visible":false,
            "type":"array",
            "visualization":"pill",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutAttemptSince":{
            "index":76,
            "unique_key":false,
            "name":"Last Outbound Connection Attempt Status Change Time",
            "visible":false,
            "type":"timestamp",
            "visualization":"value",
            "value_options":{
                "transform":"datetime",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:OutAttemptSince}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"max",
            "filter":"none",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "OutAttemptAge":{
            "index":77,
            "unique_key":false,
            "name":"Last Outbound Connection Attempt Status Change Age",
            "visible":true,
            "type":"duration",
            "visualization":"value",
            "value_options":{
                "transform":"duration",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:OutAttemptAge}},
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"min",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "MlAnomalous":{
            "index":78,
            "unique_key":false,
            "name":"Number of Anomalous Metrics",
            "visible":false,
            "type":"integer",
            "units":"metrics",
            "visualization":"value",
            "value_options":{
                "units":"metrics",
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:MlAnomalous}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "MlNormal":{
            "index":79,
            "unique_key":false,
            "name":"Number of Not Anomalous Metrics",
            "visible":false,
            "type":"integer",
            "units":"metrics",
            "visualization":"value",
            "value_options":{
                "units":"metrics",
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:MlNormal}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "MlTrained":{
            "index":80,
            "unique_key":false,
            "name":"Number of Trained Metrics",
            "visible":false,
            "type":"integer",
            "units":"metrics",
            "visualization":"value",
            "value_options":{
                "units":"metrics",
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:MlTrained}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "MlPending":{
            "index":81,
            "unique_key":false,
            "name":"Number of Pending Metrics",
            "visible":false,
            "type":"integer",
            "units":"metrics",
            "visualization":"value",
            "value_options":{
                "units":"metrics",
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:MlPending}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "MlSilenced":{
            "index":82,
            "unique_key":false,
            "name":"Number of Silenced Metrics",
            "visible":false,
            "type":"integer",
            "units":"metrics",
            "visualization":"value",
            "value_options":{
                "units":"metrics",
                "transform":"number",
                "decimal_points":0,
                "default_value":null
            },
            "max":{{max:MlSilenced}},
            "sort":"descending",
            "sortable":true,
            "sticky":false,
            "summary":"sum",
            "filter":"range",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "MachineGUID":{
            "index":83,
            "unique_key":false,
            "name":"Machine GUID",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        },
        "NodeID":{
            "index":84,
            "unique_key":false,
            "name":"Cloud Node ID",
            "visible":false,
            "type":"string",
            "visualization":"value",
            "value_options":{
                "transform":"none",
                "decimal_points":0,
                "default_value":null
            },
            "sort":"ascending",
            "sortable":true,
            "sticky":false,
            "summary":"count",
            "filter":"multiselect",
            "full_width":false,
            "wrap":false,
            "default_expanded_filter":false
        }
    },
    "default_sort_column":"Node",
    "charts":{
        "InAge":{
            "name":"Data Collection Age",
            "type":"stacked-bar",
            "columns":["InAge"]
        },
        "OutAge":{
            "name":"Streaming Age",
            "type":"stacked-bar",
            "columns":["OutAge"]
        },
        "dbDuration":{
            "name":"Retention Duration",
            "type":"stacked-bar",
            "columns":["dbDuration"]
        }
    },
    "default_charts":[
        ["InAge","Node"],
        ["OutAge","Node"]],
    "group_by":{
        "OSName":{
            "name":"O/S Name",
            "columns":["OSName"]
        },
        "OSId":{
            "name":"O/S ID",
            "columns":["OSId"]
        },
        "OSIdLike":{
            "name":"O/S ID Like",
            "columns":["OSIdLike"]
        },
        "OSVersion":{
            "name":"O/S Version",
            "columns":["OSVersion"]
        },
        "OSVersionId":{
            "name":"O/S Version ID",
            "columns":["OSVersionId"]
        },
        "OSDetection":{
            "name":"O/S Detection",
            "columns":["OSDetection"]
        },
        "CPUCores":{
            "name":"CPU Cores",
            "columns":["CPUCores"]
        },
        "ContainerOSName":{
            "name":"Container O/S Name",
            "columns":["ContainerOSName"]
        },
        "ContainerOSId":{
            "name":"Container O/S ID",
            "columns":["ContainerOSId"]
        },
        "ContainerOSIdLike":{
            "name":"Container O/S ID Like",
            "columns":["ContainerOSIdLike"]
        },
        "ContainerOSVersion":{
            "name":"Container O/S Version",
            "columns":["ContainerOSVersion"]
        },
        "ContainerOSVersionId":{
            "name":"Container O/S Version ID",
            "columns":["ContainerOSVersionId"]
        },
        "ContainerOSDetection":{
            "name":"Container O/S Detection",
            "columns":["ContainerOSDetection"]
        },
        "IsK8sNode":{
            "name":"Kubernetes Nodes",
            "columns":["IsK8sNode"]
        },
        "KernelName":{
            "name":"Kernel Name",
            "columns":["KernelName"]
        },
        "KernelVersion":{
            "name":"Kernel Version",
            "columns":["KernelVersion"]
        },
        "Architecture":{
            "name":"Architecture",
            "columns":["Architecture"]
        },
        "Virtualization":{
            "name":"Virtualization Technology",
            "columns":["Virtualization"]
        },
        "VirtDetection":{
            "name":"Virtualization Detection",
            "columns":["VirtDetection"]
        },
        "Container":{
            "name":"Container",
            "columns":["Container"]
        },
        "ContainerDetection":{
            "name":"Container Detection",
            "columns":["ContainerDetection"]
        },
        "CloudProviderType":{
            "name":"Cloud Provider Type",
            "columns":["CloudProviderType"]
        },
        "CloudInstanceType":{
            "name":"Cloud Instance Type",
            "columns":["CloudInstanceType"]
        },
        "CloudInstanceRegion":{
            "name":"Cloud Instance Region",
            "columns":["CloudInstanceRegion"]
        },
        "InStatus":{
            "name":"Collection Status",
            "columns":["InStatus"]
        },
        "OutStatus":{
            "name":"Streaming Status",
            "columns":["OutStatus"]
        },
        "MlStatus":{
            "name":"ML Status",
            "columns":["MlStatus"]
        },
        "InRemoteIP":{
            "name":"Inbound IP",
            "columns":["InRemoteIP"]
        },
        "OutRemoteIP":{
            "name":"Outbound IP",
            "columns":["OutRemoteIP"]
        }
    },
    "expires":{{expires}}
}
`

// fnsResp is a recorded answer: its head, then fnsTemplate with the table's rows, maxima and expiry.
func fnsResp(head, data string, maxima map[string]string, expires string) string {
	pairs := []string{"{{data}}", data, "{{expires}}", expires}
	for name, v := range maxima {
		pairs = append(pairs, "{{max:"+name+"}}", v)
	}
	return head + "\r\n\r\n" + strings.NewReplacer(pairs...).Replace(fnsTemplate)
}

// fnsGoneBase is the fixture's base of fnsGone's children (dashChildLinkAs).
const fnsGoneBase = 1791560520
