// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by the closer drafter SA-R's tools/pins_r.py from one C-against-C run with each answer written
// out (probe p2, 2026-10-10T14:59-15:01Z); DO NOT EDIT.

package parity

// dashNormClosersRSpawnRuns are, per script, each C side's runs (0 the oracle) of plugins.spawn's `env-claim`:
// the NETDATA_REGISTRY_* lines of each run's environment as spawnEnvView shows it, sorted.
var dashNormClosersRSpawnRuns = map[string][2][][]string{
	"get-kubernetes-labels.sh": {
		{
			{"NETDATA_REGISTRY_CLOUD_BASE_URL=https://cloud-start.parity.invalid", "NETDATA_REGISTRY_HOSTNAME=parity-parent", "NETDATA_REGISTRY_UNIQUE_ID=5a1e0000-0000-4000-8000-0000000000aa", "NETDATA_REGISTRY_URL=https://registry.my-netdata.io"},
			{"NETDATA_REGISTRY_CLOUD_BASE_URL=https://cloud-reload.parity.invalid", "NETDATA_REGISTRY_HOSTNAME=parity-parent", "NETDATA_REGISTRY_UNIQUE_ID=5a1e0000-0000-4000-8000-0000000000aa", "NETDATA_REGISTRY_URL=https://registry.my-netdata.io"},
		},
		{
			{"NETDATA_REGISTRY_CLOUD_BASE_URL=https://cloud-start.parity.invalid", "NETDATA_REGISTRY_HOSTNAME=parity-parent", "NETDATA_REGISTRY_UNIQUE_ID=5a1e0000-0000-4000-8000-0000000000aa", "NETDATA_REGISTRY_URL=https://registry.my-netdata.io"},
			{"NETDATA_REGISTRY_CLOUD_BASE_URL=https://cloud-reload.parity.invalid", "NETDATA_REGISTRY_HOSTNAME=parity-parent", "NETDATA_REGISTRY_UNIQUE_ID=5a1e0000-0000-4000-8000-0000000000aa", "NETDATA_REGISTRY_URL=https://registry.my-netdata.io"},
		},
	},
	"system-info.sh": {
		{
			{"NETDATA_REGISTRY_CLOUD_BASE_URL=https://cloud-start.parity.invalid", "NETDATA_REGISTRY_HOSTNAME=parity-parent", "NETDATA_REGISTRY_UNIQUE_ID=5a1e0000-0000-4000-8000-0000000000aa", "NETDATA_REGISTRY_URL=https://registry.my-netdata.io"},
			{"NETDATA_REGISTRY_CLOUD_BASE_URL=https://cloud-start.parity.invalid", "NETDATA_REGISTRY_HOSTNAME=parity-parent", "NETDATA_REGISTRY_UNIQUE_ID=5a1e0000-0000-4000-8000-0000000000aa", "NETDATA_REGISTRY_URL=https://registry.my-netdata.io"},
		},
		{
			{"NETDATA_REGISTRY_CLOUD_BASE_URL=https://cloud-start.parity.invalid", "NETDATA_REGISTRY_HOSTNAME=parity-parent", "NETDATA_REGISTRY_UNIQUE_ID=5a1e0000-0000-4000-8000-0000000000aa", "NETDATA_REGISTRY_URL=https://registry.my-netdata.io"},
			{"NETDATA_REGISTRY_CLOUD_BASE_URL=https://cloud-start.parity.invalid", "NETDATA_REGISTRY_HOSTNAME=parity-parent", "NETDATA_REGISTRY_UNIQUE_ID=5a1e0000-0000-4000-8000-0000000000aa", "NETDATA_REGISTRY_URL=https://registry.my-netdata.io"},
		},
	},
}

// dashNormClosersRSettings are the `errno` pair's outcomes (both C sides alike): the answer after maskAnswer, the
// row's file's state and the settings records.
var dashNormClosersRSettings = map[string]dashNormClosersRSetting{
	"control-get": {
		answer:  "HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: now\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Date+0\r\nContent-Length: 13\r\nX-Transaction-ID: <masked>\r\n\r\n{\"version\":1}",
		state:   settingsState{dir: "drwxr-x---", mode: "-rw-rw----", data: "not json"},
		records: []string{"time=T comm=netdata source=daemon level=error tid=N thread=WEB[n] src_transport=http role=none permissions=0x8 src_ip=localhost src_port=P req_method=GET conn=N transaction=X request=\"/api/v3/settings?file=default\" msg=\"file '<RUN>/lib/settings/default' cannot be parsed to extract version\""},
	},
	"bearer-get": {
		answer:  "HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: now\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Date+0\r\nContent-Length: 13\r\nX-Transaction-ID: <masked>\r\n\r\n{\"version\":1}",
		state:   settingsState{dir: "drwxr-x---", mode: "-rw-rw----", data: "not json"},
		records: []string{"time=T comm=netdata source=daemon level=error errno=\"2, No such file or directory\" tid=N thread=WEB[n] src_transport=http role=none permissions=0x8 src_ip=localhost src_port=P req_method=GET conn=N transaction=X request=\"/api/v3/settings?file=default\" msg=\"file '<RUN>/lib/settings/default' cannot be parsed to extract version\""},
	},
	"bearer-put": {
		answer:  "HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: now\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Date+1\r\nContent-Length: 34\r\nX-Transaction-ID: <masked>\r\n\r\n{\"status\":200,\"errorMessage\":\"OK\"}",
		state:   settingsState{dir: "drwxr-x---", mode: "-rw-rw----", data: "{ \"version\": 2 }"},
		records: []string{"time=T comm=netdata source=daemon level=error errno=\"2, No such file or directory\" tid=N thread=WEB[n] src_transport=http role=none permissions=0x8 src_ip=localhost src_port=P req_method=PUT conn=N transaction=X request=\"/api/v3/settings?file=default\" msg=\"file '<RUN>/lib/settings/default' cannot be parsed to extract version\""},
	},
	"string-get": {
		answer:  "HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: now\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Date+0\r\nContent-Length: 13\r\nX-Transaction-ID: <masked>\r\n\r\n{\"version\":1}",
		state:   settingsState{dir: "drwxr-x---", mode: "-rw-rw----", data: "{\"version\":\"x\"}"},
		records: []string{"time=T comm=netdata source=daemon level=error errno=\"22, Invalid argument\" tid=N thread=WEB[n] src_transport=http account=b6b6b6b666664666866600000000acc1 user=fnhttp-admin role=admin permissions=0x7ff src_ip=localhost src_port=P req_method=GET conn=N transaction=X request=\"/api/v3/settings?file=st-strx\" msg=\"file '<RUN>/lib/settings/st-strx' cannot be parsed to extract version\""},
	},
	"string-put": {
		answer:  "HTTP/1.1 200 OK\r\nConnection: close\r\nServer: Netdata Embedded HTTP Server v2.11.0-458-g1e97a0fc9e\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nDate: now\r\nContent-Type: application/json; charset=utf-8\r\nCache-Control: no-cache, no-store, must-revalidate\r\nPragma: no-cache\r\nExpires: Date+1\r\nContent-Length: 34\r\nX-Transaction-ID: <masked>\r\n\r\n{\"status\":200,\"errorMessage\":\"OK\"}",
		state:   settingsState{dir: "drwxr-x---", mode: "-rw-rw----", data: "{ \"version\": 2 }"},
		records: []string{"time=T comm=netdata source=daemon level=error errno=\"22, Invalid argument\" tid=N thread=WEB[n] src_transport=http account=b6b6b6b666664666866600000000acc1 user=fnhttp-admin role=admin permissions=0x7ff src_ip=localhost src_port=P req_method=PUT conn=N transaction=X request=\"/api/v3/settings?file=st-strx\" msg=\"file '<RUN>/lib/settings/st-strx' cannot be parsed to extract version\""},
	},
}

// dashNormClosersRRows are the closer v2 rows of api.v2-contexts and api.v2-q by `<check>/<case>/<row>`, both C
// sides (0 the oracle; the last answer of each, a settled row being asked again), each body written without the
// whitespace outside its strings.
var dashNormClosersRRows = map[string]dashNormSearchRow{
	"contexts/data/q-ignored": {
		target: "/api/v2/contexts?scope_nodes=*&q=nomatch",
		bodies: [2]string{
			`{"api":2,"nodes":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nm":"parity-parent","ni":0,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000bb","nm":"parity-child","ni":1,"st":{"ai":0,"code":200,"msg":""}}],"contexts":{"q.ctx":{"family":"fam","units":"units","priority":1000,"first_entry":1791644220,"last_entry":1791644383,"live":true}},"versions":{"routing_hard_hash":1,"nodes_hard_hash":2,"contexts_hard_hash":13,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644383,"ai":0,"timings":{"prep_ms":0,"query_ms":0.009,"output_ms":0.005,"total_ms":0.014,"cloud_ms":0.014}}],"timings":{"routing_ms":0,"node_max_ms":0,"total_ms":0.014}}`,
			`{"api":2,"nodes":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nm":"parity-parent","ni":0,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000bb","nm":"parity-child","ni":1,"st":{"ai":0,"code":200,"msg":""}}],"contexts":{"q.ctx":{"family":"fam","units":"units","priority":1000,"first_entry":1791644220,"last_entry":1791644383,"live":true}},"versions":{"routing_hard_hash":1,"nodes_hard_hash":2,"contexts_hard_hash":13,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644383,"ai":0,"timings":{"prep_ms":0,"query_ms":0.021,"output_ms":0.008,"total_ms":0.029,"cloud_ms":0.029}}],"timings":{"routing_ms":0,"node_max_ms":0,"total_ms":0.029}}`,
		},
		flight: [2][2]int64{{1791644383, 1791644383}, {1791644383, 1791644383}},
		lines:  [2]int{59, 59},
	},
	"contexts/three/truncated2": {
		target: "/api/v2/contexts?scope_nodes=*&cardinality=2",
		bodies: [2]string{
			`{"api":2,"nodes":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nm":"parity-parent","ni":0,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000bb","nm":"parity-child","ni":1,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000cc","nm":"parity-child2","ni":2,"st":{"ai":0,"code":200,"msg":""}}],"contexts":{"q.ctx":{"family":"fam[x]","units":"units","priority":900,"first_entry":1791644160,"last_entry":1791644395,"live":true},"r.ctx":{"family":"rfam","units":"runits","priority":1100,"first_entry":1791644160,"last_entry":1791644395,"live":true},"__truncated__":{"total_contexts":3,"returned":2,"remaining":1}},"versions":{"routing_hard_hash":1,"nodes_hard_hash":3,"contexts_hard_hash":52,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644395,"ai":0,"timings":{"prep_ms":0,"query_ms":0.093,"output_ms":0.064,"total_ms":0.157,"cloud_ms":0.157}}],"timings":{"routing_ms":0,"node_max_ms":0,"total_ms":0.157}}`,
			`{"api":2,"nodes":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nm":"parity-parent","ni":0,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000bb","nm":"parity-child","ni":1,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000cc","nm":"parity-child2","ni":2,"st":{"ai":0,"code":200,"msg":""}}],"contexts":{"q.ctx":{"family":"fam[x]","units":"units","priority":900,"first_entry":1791644160,"last_entry":1791644395,"live":true},"r.ctx":{"family":"rfam","units":"runits","priority":1100,"first_entry":1791644160,"last_entry":1791644395,"live":true},"__truncated__":{"total_contexts":3,"returned":2,"remaining":1}},"versions":{"routing_hard_hash":1,"nodes_hard_hash":3,"contexts_hard_hash":52,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644395,"ai":0,"timings":{"prep_ms":0,"query_ms":0.064,"output_ms":0.037,"total_ms":0.101,"cloud_ms":0.101}}],"timings":{"routing_ms":0,"node_max_ms":0,"total_ms":0.101}}`,
		},
		flight: [2][2]int64{{1791644395, 1791644395}, {1791644395, 1791644395}},
		lines:  [2]int{81, 81},
	},
	"search/data/every-mcp": {
		target: "/api/v2/q?q=**&options=mcp",
		bodies: [2]string{
			`{"nodes":[{"machine_guid":"5a1e0000-0000-4000-8000-0000000000aa","hostname":"parity-parent","relationship":"localhost","connected":true},{"machine_guid":"5a1e0000-0000-4000-8000-0000000000bb","hostname":"parity-child","relationship":"child","connected":true}],"contexts":{"q.ctx":{"title":"title [x]","family":"fam","units":"units","instances":["q.q_a_name","q.two"],"dimensions":["alpha","b","... 4 dimensions more"],"labels":{"_collect_plugin":["fixture-pusher"],"_collect_module":["corpus"],"k":["v1","v2"]}}},"searches":{"strings":13,"char":12,"total":25},"versions":{"routing_hard_hash":1,"nodes_hard_hash":2,"contexts_hard_hash":13,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644407,"ai":0,"timings":{"prep_ms":0,"query_ms":0.021,"output_ms":0.009,"total_ms":0.03,"cloud_ms":0.03}}]}`,
			`{"nodes":[{"machine_guid":"5a1e0000-0000-4000-8000-0000000000aa","hostname":"parity-parent","relationship":"localhost","connected":true},{"machine_guid":"5a1e0000-0000-4000-8000-0000000000bb","hostname":"parity-child","relationship":"child","connected":true}],"contexts":{"q.ctx":{"title":"title [x]","family":"fam","units":"units","instances":["q.q_a_name","q.two"],"dimensions":["alpha","b","... 4 dimensions more"],"labels":{"_collect_plugin":["fixture-pusher"],"_collect_module":["corpus"],"k":["v1","v2"]}}},"searches":{"strings":13,"char":12,"total":25},"versions":{"routing_hard_hash":1,"nodes_hard_hash":2,"contexts_hard_hash":13,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644407,"ai":0,"timings":{"prep_ms":0,"query_ms":0.02,"output_ms":0.009,"total_ms":0.029,"cloud_ms":0.029}}]}`,
		},
		flight: [2][2]int64{{1791644407, 1791644407}, {1791644407, 1791644407}},
		lines:  [2]int{54, 54},
	},
	"search/three/truncated3": {
		target: "/api/v2/q?q=fam&cardinality=2",
		bodies: [2]string{
			`{"api":2,"nodes":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nm":"parity-parent","ni":0,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000bb","nm":"parity-child","ni":1,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000cc","nm":"parity-child2","ni":2,"st":{"ai":0,"code":200,"msg":""}}],"contexts":{"q.ctx":{"family":"fam[x]","matched":["families"]},"r.ctx":{"family":"rfam","matched":["families"]},"__truncated__":{"total_contexts":3,"returned":2,"remaining":1}},"searches":{"strings":60,"char":0,"total":60},"versions":{"routing_hard_hash":1,"nodes_hard_hash":3,"contexts_hard_hash":52,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644432,"ai":0,"timings":{"prep_ms":0,"query_ms":0.128,"output_ms":0.06,"total_ms":0.188,"cloud_ms":0.188}}],"timings":{"routing_ms":0,"node_max_ms":0,"total_ms":0.188}}`,
			`{"api":2,"nodes":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nm":"parity-parent","ni":0,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000bb","nm":"parity-child","ni":1,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000cc","nm":"parity-child2","ni":2,"st":{"ai":0,"code":200,"msg":""}}],"contexts":{"q.ctx":{"family":"fam[x]","matched":["families"]},"r.ctx":{"family":"rfam","matched":["families"]},"__truncated__":{"total_contexts":3,"returned":2,"remaining":1}},"searches":{"strings":60,"char":0,"total":60},"versions":{"routing_hard_hash":1,"nodes_hard_hash":3,"contexts_hard_hash":52,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644432,"ai":0,"timings":{"prep_ms":0,"query_ms":0.048,"output_ms":0.018,"total_ms":0.066,"cloud_ms":0.066}}],"timings":{"routing_ms":0,"node_max_ms":0,"total_ms":0.066}}`,
		},
		flight: [2][2]int64{{1791644432, 1791644432}, {1791644432, 1791644432}},
		lines:  [2]int{78, 78},
	},
	"search/three/first-gone-child": {
		target: "/api/v2/contexts?options=titles&scope_nodes=parity-child",
		bodies: [2]string{
			`{"api":2,"nodes":[{"mg":"5a1e0000-0000-4000-8000-0000000000bb","nm":"parity-child","ni":0,"st":{"ai":0,"code":200,"msg":""}}],"contexts":{"q.ctx":{"title":"title [x]","family":"fam","units":"units","priority":1000,"first_entry":1791644280,"last_entry":1791644340,"live":false}},"versions":{"routing_hard_hash":1,"nodes_hard_hash":3,"contexts_hard_hash":13,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644433,"ai":0,"timings":{"prep_ms":0,"query_ms":0.021,"output_ms":0.029,"total_ms":0.05,"cloud_ms":0.05}}],"timings":{"routing_ms":0,"node_max_ms":0,"total_ms":0.05}}`,
			`{"api":2,"nodes":[{"mg":"5a1e0000-0000-4000-8000-0000000000bb","nm":"parity-child","ni":0,"st":{"ai":0,"code":200,"msg":""}}],"contexts":{"q.ctx":{"title":"title [x]","family":"fam","units":"units","priority":1000,"first_entry":1791644280,"last_entry":1791644340,"live":false}},"versions":{"routing_hard_hash":1,"nodes_hard_hash":3,"contexts_hard_hash":13,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644433,"ai":0,"timings":{"prep_ms":0,"query_ms":0.021,"output_ms":0.015,"total_ms":0.036,"cloud_ms":0.036}}],"timings":{"routing_ms":0,"node_max_ms":0,"total_ms":0.036}}`,
		},
		flight: [2][2]int64{{1791644433, 1791644433}, {1791644433, 1791644433}},
		lines:  [2]int{51, 51},
	},
	"search/three/first-gone": {
		target: "/api/v2/q?q=title|other",
		bodies: [2]string{
			`{"api":2,"nodes":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nm":"parity-parent","ni":0,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000bb","nm":"parity-child","ni":1,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000cc","nm":"parity-child2","ni":2,"st":{"ai":0,"code":200,"msg":""}}],"contexts":{"q.ctx":{"title":"[x] [x]","matched":["title","instances"],"instances":["q.q_a_other"]},"r.ctx":{"title":"r title [x]","matched":["title"]},"s.ctx":{"title":"s title [x]","matched":["title"]}},"searches":{"strings":60,"char":0,"total":60},"versions":{"routing_hard_hash":1,"nodes_hard_hash":3,"contexts_hard_hash":52,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644433,"ai":0,"timings":{"prep_ms":0,"query_ms":0.043,"output_ms":0.013,"total_ms":0.056,"cloud_ms":0.056}}],"timings":{"routing_ms":0,"node_max_ms":0,"total_ms":0.056}}`,
			`{"api":2,"nodes":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nm":"parity-parent","ni":0,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000bb","nm":"parity-child","ni":1,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000cc","nm":"parity-child2","ni":2,"st":{"ai":0,"code":200,"msg":""}}],"contexts":{"q.ctx":{"title":"[x] [x]","matched":["title","instances"],"instances":["q.q_a_other"]},"r.ctx":{"title":"r title [x]","matched":["title"]},"s.ctx":{"title":"s title [x]","matched":["title"]}},"searches":{"strings":60,"char":0,"total":60},"versions":{"routing_hard_hash":1,"nodes_hard_hash":3,"contexts_hard_hash":52,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644433,"ai":0,"timings":{"prep_ms":0,"query_ms":0.039,"output_ms":0.012,"total_ms":0.051,"cloud_ms":0.051}}],"timings":{"routing_ms":0,"node_max_ms":0,"total_ms":0.051}}`,
		},
		flight: [2][2]int64{{1791644433, 1791644433}, {1791644433, 1791644433}},
		lines:  [2]int{78, 78},
	},
	"search/keep/second-gone": {
		target: "/api/v2/q?q=title|other",
		bodies: [2]string{
			`{"api":2,"nodes":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nm":"parity-parent","ni":0,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000bb","nm":"parity-child","ni":1,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000cc","nm":"parity-child2","ni":2,"st":{"ai":0,"code":200,"msg":""}}],"contexts":{"q.ctx":{"title":"title [x]","matched":["title","instances"],"instances":["q.q_a_other"]},"r.ctx":{"title":"r title [x]","matched":["title"]}},"searches":{"strings":45,"char":0,"total":45},"versions":{"routing_hard_hash":1,"nodes_hard_hash":3,"contexts_hard_hash":39,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644447,"ai":0,"timings":{"prep_ms":0,"query_ms":0.072,"output_ms":0.036,"total_ms":0.108,"cloud_ms":0.108}}],"timings":{"routing_ms":0,"node_max_ms":0,"total_ms":0.108}}`,
			`{"api":2,"nodes":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nm":"parity-parent","ni":0,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000bb","nm":"parity-child","ni":1,"st":{"ai":0,"code":200,"msg":""}},{"mg":"5a1e0000-0000-4000-8000-0000000000cc","nm":"parity-child2","ni":2,"st":{"ai":0,"code":200,"msg":""}}],"contexts":{"q.ctx":{"title":"title [x]","matched":["title","instances"],"instances":["q.q_a_other"]},"r.ctx":{"title":"r title [x]","matched":["title"]}},"searches":{"strings":45,"char":0,"total":45},"versions":{"routing_hard_hash":1,"nodes_hard_hash":3,"contexts_hard_hash":39,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644447,"ai":0,"timings":{"prep_ms":0,"query_ms":0.07,"output_ms":0.038,"total_ms":0.108,"cloud_ms":0.108}}],"timings":{"routing_ms":0,"node_max_ms":0,"total_ms":0.108}}`,
		},
		flight: [2][2]int64{{1791644447, 1791644447}, {1791644447, 1791644447}},
		lines:  [2]int{74, 74},
	},
	"search/obsolete/obsolete-chart": {
		target: "/api/v2/q?q=**&after=1791644341&before=1791644350",
		bodies: [2]string{
			`{"api":2,"nodes":[{"mg":"5a1e0000-0000-4000-8000-0000000000bb","nm":"parity-child","ni":0,"st":{"ai":0,"code":200,"msg":""}}],"contexts":{"o.ctx":{"title":"otitle [x]","family":"ofam","units":"ounits","matched":["id","title","units","families","instances","dimensions","labels"],"instances":["o.live","o.obs"],"dimensions":["d1","e1"],"labels":{"ol":["obs","live"],"_collect_plugin":["fixture-pusher"],"_collect_module":["corpus"]}}},"searches":{"strings":8,"char":12,"total":20},"versions":{"routing_hard_hash":1,"nodes_hard_hash":2,"contexts_hard_hash":11,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644456,"ai":0,"timings":{"prep_ms":0,"query_ms":0.097,"output_ms":0.046,"total_ms":0.143,"cloud_ms":0.143}}],"timings":{"routing_ms":0,"node_max_ms":0,"total_ms":0.143}}`,
			`{"api":2,"nodes":[{"mg":"5a1e0000-0000-4000-8000-0000000000bb","nm":"parity-child","ni":0,"st":{"ai":0,"code":200,"msg":""}}],"contexts":{"o.ctx":{"title":"otitle [x]","family":"ofam","units":"ounits","matched":["id","title","units","families","instances","dimensions","labels"],"instances":["o.live","o.obs"],"dimensions":["d1","e1"],"labels":{"_collect_plugin":["fixture-pusher"],"_collect_module":["corpus"],"ol":["live","obs"]}}},"searches":{"strings":8,"char":12,"total":20},"versions":{"routing_hard_hash":1,"nodes_hard_hash":2,"contexts_hard_hash":11,"contexts_soft_hash":0,"alerts_hard_hash":0,"alerts_soft_hash":0},"agents":[{"mg":"5a1e0000-0000-4000-8000-0000000000aa","nd":null,"nm":"parity-parent","now":1791644456,"ai":0,"timings":{"prep_ms":0,"query_ms":0.057,"output_ms":0.053,"total_ms":0.11,"cloud_ms":0.11}}],"timings":{"routing_ms":0,"node_max_ms":0,"total_ms":0.11}}`,
		},
		flight: [2][2]int64{{1791644457, 1791644457}, {1791644457, 1791644457}},
		lines:  [2]int{60, 60},
	},
}
