[package]
name = "netdata-agent-nrpc"
description = "The function registry (nRPC) of the netdata agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
netdata-agent-log = { workspace = true }
netdata-agent-sys = { workspace = true }
netdata-agent-text = { workspace = true }
netdata-agent-web = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[features]
# `testing::inert` for other crates' tests.
testing = []
