version: '3.3'
services:
  child:
    image: netdata/netdata
    command: /usr/sbin/netdata -D
    #ports:               Removed to allow scaling
    #- 20001:19999
    volumes:
      - ./child_stream.conf:/etc/netdata/stream.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # agent_child2:
  #   image: netdata/netdata
  #   command: /usr/sbin/netdata -D
  #   #ports:              Removed to allow scaling
  #   #- 20002:19999
  #   volumes:
  #     - ./child_stream.conf:/etc/netdata/stream.conf:ro
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
