[package]
name = "otel-oracle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
bytes = { workspace = true }
clap = { workspace = true }
opentelemetry-proto = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true, features = ["gzip"] }

[dev-dependencies]
tempfile = { workspace = true }
tokio-stream = { workspace = true, features = ["net"] }
