/* This file was generated by CMAKE from config.cmake.h.in */

#define VERSION "@NETDATA_VERSION@"

#define CONFIGURE_COMMAND "cmake"

#define NETDATA_USER "@NETDATA_USER@"

/* Using a bundled copy of protobuf */
// #undef BUNDLED_PROTOBUF
#define HAVE_PROTOBUF 1

#define likely(x) @LIKELY_MACRO@
#define unlikely(x) @UNLIKELY_MACRO@

/* La boring stuff */
#cmakedefine HAVE_STRUCT_TIMESPEC

/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif

#cmakedefine HAVE_SYS_STATFS_H
#cmakedefine HAVE_SYS_STATVFS_H
#cmakedefine HAVE_INTTYPES_H
#cmakedefine HAVE_STDINT_H
#cmakedefine STRERROR_R_CHAR_P

#cmakedefine MAJOR_IN_MKDEV
#cmakedefine MAJOR_IN_SYSMACROS

#cmakedefine HAVE_CRYPTO

#cmakedefine ENABLE_PROMETHEUS_REMOTE_WRITE

/* they are defined as REQUIRED in CMakeLists.txt */
#define NETDATA_WITH_ZLIB 1
#define ENABLE_JSONC 1

#cmakedefine ENABLE_ML

#cmakedefine HAVE_LIBBPF

/* NSA spy stuff */
#define ENABLE_HTTPS 1
#cmakedefine01 HAVE_X509_VERIFY_PARAM_set1_host

#define ENABLE_ACLK
#define ENABLE_DBENGINE
#define ENABLE_COMPRESSION // pkg_check_modules(LIBLZ4 REQUIRED liblz4)

#cmakedefine ENABLE_APPS_PLUGIN
#cmakedefine ENABLE_PERF_PLUGIN

#define __always_unused @ALWAYS_UNUSED_MACRO@
#define __maybe_unused @MAYBE_UNUSED_MACRO@

/* netdata dirs */
#define CACHE_DIR       "@NETDATA_CACHE_DIR@"
#define CONFIG_DIR      "@NETDATA_CONFIG_DIR@"
#define LIBCONFIG_DIR   "@NETDATA_LIBCONFIG_DIR@"
#define LOG_DIR         "@NETDATA_LOG_DIR@"
#define PLUGINS_DIR     "@NETDATA_PLUGINS_DIR@"
#define WEB_DIR         "@NETDATA_WEB_DIR@"
#define VARLIB_DIR      "@NETDATA_VARLIB_DIR@"
