//! dbengine page formats against vectors the C implementation produced (`tests/vectors/dbengine/`, regenerated by
//! `tests/oracle/dbengine/gen.sh`; README there).

use std::path::PathBuf;

use netdata_agent_storage::dbengine::format::descriptor::{
    PAGE_TYPE_ARRAY_32BIT, PAGE_TYPE_ARRAY_TIER1, PAGE_TYPE_GORILLA_32BIT,
};
use netdata_agent_storage::dbengine::format::page::{
    Cursor, DiskPage, PageBuilder, gorilla, tier1,
};
use netdata_agent_storage::storage_number::pack;
use netdata_agent_storage::storage_point::StoragePoint;
use serde_json::Value;

fn vectors(name: &str) -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/vectors/dbengine")
        .join(name);
    serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap()
}

fn hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn to_hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn bits(v: &Value) -> f64 {
    f64::from_bits(u64::from_str_radix(v["bits"].as_str().unwrap(), 16).unwrap())
}

/// The vectors' point tuple: `[ok, sum_bits, min_bits, max_bits, count, anomaly_count, flags]`.
fn tuple(ok: bool, p: &StoragePoint) -> Value {
    serde_json::json!([
        ok,
        format!("{:016x}", p.sum.to_bits()),
        format!("{:016x}", p.min.to_bits()),
        format!("{:016x}", p.max.to_bits()),
        p.count,
        p.anomaly_count,
        p.flags
    ])
}

/// The next `n` points of a cursor.
fn cursor_points(mut cursor: Cursor<'_>, n: usize) -> Vec<Value> {
    (0..n)
        .map(|_| {
            let (ok, p) = cursor.next_point();
            tuple(ok, &p)
        })
        .collect()
}

fn n(v: &Value) -> usize {
    v.as_u64().unwrap() as usize
}

#[test]
fn raw_pages_as_c() {
    let v = vectors("raw-pages.json");
    let cases = v["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 8);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let page_type = if c["page_type_id"] == 1 {
            PAGE_TYPE_ARRAY_TIER1
        } else {
            PAGE_TYPE_ARRAY_32BIT
        };
        // what the collector builds and puts on disk
        let slots = c["slots"].as_u64().unwrap_or(1024) as usize;
        let mut page = PageBuilder::new(page_type, slots).unwrap();
        if let Some(values) = c["input_values"].as_array() {
            for (v, f) in values.iter().zip(c["input_flags"].as_array().unwrap()) {
                let v = bits(v);
                page.append(v, v, v, 1, 0, f.as_u64().unwrap() as u32)
                    .unwrap();
            }
        }
        if let Some(records) = c["input"].as_array() {
            for (r, want) in records.iter().zip(c["records"].as_array().unwrap()) {
                let (sum, min, max) = (bits(&r["sum"]), bits(&r["min"]), bits(&r["max"]));
                let (count, anomalies) = (n(&r["count"]) as u16, n(&r["anomaly_count"]) as u16);
                let record = tier1::Tier1Record::from_aggregate(sum, min, max, count, anomalies);
                assert_eq!(to_hex(&record.encode()), want["hex"], "{name}");
                page.append(sum, min, max, count, anomalies, 0).unwrap();
            }
        }
        if c.get("pgd_slots_used").is_some() {
            assert_eq!(to_hex(&page.to_extent_bytes()), c["page_hex"], "{name}");
            assert_eq!(page.disk_footprint(), n(&c["disk_footprint"]), "{name}");
            assert_eq!(page.slots_used(), n(&c["pgd_slots_used"]), "{name}");
            assert_eq!(Value::Bool(page.is_empty()), c["pgd_is_empty"], "{name}");
        }
        // what a disk load gives back: the page's bytes, or the first `size` bytes of the disk input
        let mut disk = hex(c["page_hex"]
            .as_str()
            .or(c["disk_input_hex"].as_str())
            .unwrap());
        if let Some(size) = c["size"].as_u64() {
            disk.truncate(size as usize);
        }
        let from_disk = &c["from_disk"];
        let Some(loaded) = DiskPage::from_disk(page_type, &disk) else {
            assert_eq!(from_disk, "PGD_EMPTY", "{name}");
            continue;
        };
        let wanted = from_disk["points_from_0"].as_array().unwrap();
        assert_eq!(
            loaded.slots_used(),
            n(&from_disk["pgd_slots_used"]),
            "{name}"
        );
        assert_eq!(
            cursor_points(loaded.cursor(0), wanted.len()),
            *wanted,
            "{name}"
        );
    }
}

fn u32_hex(v: &Value) -> u32 {
    u32::from_str_radix(v.as_str().unwrap().trim_start_matches("0x"), 16).unwrap()
}

fn read_all(mut r: gorilla::Reader<'_>) -> Vec<Value> {
    std::iter::from_fn(|| r.read())
        .map(|n| Value::String(format!("0x{n:08x}")))
        .collect()
}

fn buffers_json(w: &gorilla::Writer) -> Vec<Value> {
    let last = w.buffers().len() - 1;
    w.buffers()
        .iter()
        .enumerate()
        .map(|(i, b)| {
            serde_json::json!({
                "next": if i == last { "zero" } else { "nonzero" },
                "entries": b.entries,
                "nbits": b.nbits,
                "hex_next_masked": to_hex(&b.to_bytes(0)),
            })
        })
        .collect()
}

#[test]
fn gorilla_writer_as_c() {
    let v = vectors("gorilla-writer.json");
    let cases = v["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 26);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let mut w = gorilla::Writer::default();
        let mut failures = Vec::new();
        for (index, n) in c["input_u32"]
            .as_array()
            .unwrap()
            .iter()
            .map(u32_hex)
            .enumerate()
        {
            let before = w.buffers().last().unwrap().nbits;
            if !w.write(n) {
                let last = w.buffers().last().unwrap();
                failures.push(serde_json::json!({
                    "index": index,
                    "full_buffer": w.buffers().len() - 1,
                    "nbits_before": before,
                    "nbits_after": last.nbits,
                    "partial_bits": last.nbits - before,
                    "entries": last.entries,
                }));
                w.add_buffer();
                assert!(w.write(n), "{name}");
            }
        }
        assert_eq!(Value::Array(failures), c["write_failures"], "{name}");
        assert_eq!(
            w.buffers().len() as u64,
            c["num_buffers"].as_u64().unwrap(),
            "{name}"
        );
        assert_eq!(
            u64::from(w.entries()),
            c["writer_entries"].as_u64().unwrap(),
            "{name}"
        );
        let bytes = w.serialize();
        assert_eq!(
            bytes.len() as u64,
            c["byte_length"].as_u64().unwrap(),
            "{name}"
        );
        assert_eq!(Value::Array(buffers_json(&w)), c["buffers"], "{name}");
        assert_eq!(
            Value::Array(read_all(w.reader())),
            c["decoded_live"],
            "{name}"
        );
        let disk = gorilla::from_disk(&bytes);
        assert_eq!(Value::Bool(disk.is_some()), c["disk_patch_ok"], "{name}");
        if let Some(disk) = disk {
            assert_eq!(
                u64::from(disk.entries),
                c["disk_patch_entries"].as_u64().unwrap(),
                "{name}"
            );
            assert_eq!(
                Value::Array(read_all(gorilla::Reader::new(&disk.buffers))),
                c["decoded_disk"],
                "{name}"
            );
        }
    }
}

#[test]
fn gorilla_pages_as_c() {
    let v = vectors("gorilla-page.json");
    let cases = v["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 10);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let mut page = PageBuilder::new(PAGE_TYPE_GORILLA_32BIT, n(&c["slots"])).unwrap();
        let mut grew = Vec::new();
        let mut packed = Vec::new();
        let values = c["input_values"].as_array().unwrap();
        for (i, (v, f)) in values
            .iter()
            .zip(c["input_flags"].as_array().unwrap())
            .enumerate()
        {
            let (v, f) = (bits(v), f.as_u64().unwrap() as u32);
            packed.push(Value::String(format!("0x{:08x}", pack(v, f))));
            if page.append(v, v, v, 1, 0, f).unwrap() {
                grew.push(i);
            }
        }
        assert_eq!(Value::Array(packed), c["packed_u32"], "{name}");
        assert_eq!(
            serde_json::json!(grew),
            c["append_returned_buffer_size_at"],
            "{name}"
        );
        assert_eq!(page.slots_used(), n(&c["pgd_slots_used"]), "{name}");
        assert_eq!(Value::Bool(page.is_empty()), c["pgd_is_empty"], "{name}");
        assert_eq!(page.disk_footprint(), n(&c["disk_footprint"]), "{name}");
        let bytes = page.to_extent_bytes();
        assert_eq!(bytes.len(), page.disk_footprint(), "{name}");
        if page.slots_used() > 0 {
            let w = page.gorilla().unwrap();
            assert_eq!(w.buffers().len(), n(&c["num_buffers"]), "{name}");
            assert_eq!(Value::Array(buffers_json(w)), c["buffers"], "{name}");
        }
        let live = c["collector_points_from_0"].as_array().unwrap();
        assert_eq!(cursor_points(page.cursor(0), live.len()), *live, "{name}");
        let from_disk = &c["from_disk"];
        if from_disk.is_object() {
            let disk = DiskPage::from_disk(PAGE_TYPE_GORILLA_32BIT, &bytes).unwrap();
            assert_eq!(disk.slots_used(), n(&from_disk["pgd_slots_used"]), "{name}");
            // a page from disk has as many slots as it uses
            assert_eq!(disk.slots_used(), n(&from_disk["pgd_capacity"]), "{name}");
            assert_eq!(
                Value::Bool(disk.is_empty()),
                from_disk["pgd_is_empty"],
                "{name}"
            );
            let wanted = from_disk["points_from_0"].as_array().unwrap();
            assert_eq!(
                cursor_points(disk.cursor(0), wanted.len()),
                *wanted,
                "{name}"
            );
        }
    }
}

#[test]
fn gorilla_disk_loads_as_c() {
    let v = vectors("gorilla-disk-load.json");
    let cases = v["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 24);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let mut bytes = hex(c["input_hex"].as_str().unwrap());
        bytes.truncate(n(&c["size"]));
        let result = &c["result"];
        let Some(disk) = DiskPage::from_disk(PAGE_TYPE_GORILLA_32BIT, &bytes) else {
            assert_eq!(result, "PGD_EMPTY", "{name}");
            continue;
        };
        assert_eq!(disk.slots_used(), n(&result["pgd_slots_used"]), "{name}");
        assert_eq!(disk.slots_used(), n(&result["pgd_capacity"]), "{name}");
        let wanted = result["points_from_0"].as_array().unwrap();
        assert_eq!(
            cursor_points(disk.cursor(0), wanted.len()),
            *wanted,
            "{name}"
        );
    }
}

/// `page_test.cc` never ran in C (no gtest in the build); each test's expectations live in a vector case, or here.
#[test]
fn pgd_tests_are_covered() {
    let v = vectors("pgd-tests.json");
    let tests = v["tests"].as_array().unwrap();
    assert_eq!(tests.len(), 11);
    let case_re = |file: &str| -> Vec<String> {
        vectors(file)["cases"]
            .as_array()
            .unwrap()
            .iter()
            .map(|c| c["name"].as_str().unwrap().to_string())
            .collect()
    };
    for t in tests {
        let Some(m) = t["materialized"].as_str() else {
            continue;
        };
        // "<file>.json case[s] <name>[, <name>][, and <name>] [(note)]"
        let (file, rest) = m.split_once(' ').unwrap();
        let names = rest.split('(').next().unwrap();
        let names = names
            .trim_start_matches("cases ")
            .trim_start_matches("case ");
        let known = case_re(file);
        for name in names
            .split([',', ' '])
            .filter(|w| !w.is_empty() && *w != "and")
        {
            assert!(
                known.iter().any(|k| k == name),
                "{}: {name} not in {file}",
                t["test"]
            );
        }
    }
    // PGD.EmptyOrNull: PGD_EMPTY is None; an empty collected page has no points and no footprint
    assert!(DiskPage::from_disk(PAGE_TYPE_GORILLA_32BIT, &[]).is_none());
    let page = PageBuilder::new(PAGE_TYPE_GORILLA_32BIT, 1024).unwrap();
    assert!(page.is_empty());
    assert_eq!((page.slots_used(), page.disk_footprint()), (0, 0));
    assert!(!page.cursor(0).next_point().0);
    // PGD.Create: appends stop at the capacity (C's fatal)
    let mut page = PageBuilder::new(PAGE_TYPE_ARRAY_32BIT, 2).unwrap();
    assert!(page.append(1.0, 1.0, 1.0, 1, 0, 0).is_some());
    assert!(page.append(2.0, 2.0, 2.0, 1, 0, 0).is_some());
    assert!(page.append(3.0, 3.0, 3.0, 1, 0, 0).is_none());
    assert_eq!(page.capacity(), 2);
    // PGD.CursorHalfPage: a cursor reset to the middle of a gorilla page reads from there
    let mut page = PageBuilder::new(PAGE_TYPE_GORILLA_32BIT, 1024).unwrap();
    for i in 0..1024 {
        page.append(f64::from(i), 0.0, 0.0, 1, 0, 0x0100_0000)
            .unwrap();
    }
    let (ok, p) = page.cursor(512).next_point();
    assert!(ok);
    assert_eq!(p.sum, 512.0);
    let disk = DiskPage::from_disk(PAGE_TYPE_GORILLA_32BIT, &page.to_extent_bytes()).unwrap();
    let mut cursor = disk.cursor(1023);
    assert_eq!(cursor.next_point().1.sum, 1023.0);
    assert!(!cursor.next_point().0);
}
