//! dbengine page formats against vectors the C implementation produced (`tests/vectors/dbengine/`, regenerated by
//! `tests/oracle/dbengine/gen.sh`; README there).

use std::path::PathBuf;

use netdata_agent_storage::dbengine::format::page::{self, tier1};
use netdata_agent_storage::storage_number::pack;
use netdata_agent_storage::storage_point::StoragePoint;
use serde_json::Value;

fn vectors(name: &str) -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/vectors/dbengine")
        .join(name);
    serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap()
}

fn hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn to_hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn bits(v: &Value) -> f64 {
    f64::from_bits(u64::from_str_radix(v["bits"].as_str().unwrap(), 16).unwrap())
}

/// The vectors' point tuple: `[ok, sum_bits, min_bits, max_bits, count, anomaly_count, flags]`.
fn tuple(ok: bool, p: &StoragePoint) -> Value {
    serde_json::json!([
        ok,
        format!("{:016x}", p.sum.to_bits()),
        format!("{:016x}", p.min.to_bits()),
        format!("{:016x}", p.max.to_bits()),
        p.count,
        p.anomaly_count,
        p.flags
    ])
}

/// The cursor from slot 0: the used points, then empty ones.
fn points(used: &[StoragePoint], wanted: usize) -> Vec<Value> {
    (0..wanted)
        .map(|i| match used.get(i) {
            Some(p) => tuple(true, p),
            None => tuple(false, &StoragePoint::empty(0, 0)),
        })
        .collect()
}

#[test]
fn raw_pages_as_c() {
    let v = vectors("raw-pages.json");
    let cases = v["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 8);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let tier1 = c["page_type_id"] == 1;
        // what the writer puts on disk
        if let Some(values) = c["input_values"].as_array() {
            let flags = c["input_flags"].as_array().unwrap();
            let slots: Vec<u32> = values
                .iter()
                .zip(flags)
                .map(|(v, f)| pack(bits(v), f.as_u64().unwrap() as u32))
                .collect();
            let bytes = page::array32_encode(&slots);
            assert_eq!(to_hex(&bytes), c["page_hex"], "{name}");
            assert_eq!(
                bytes.len() as u64,
                c["disk_footprint"].as_u64().unwrap(),
                "{name}"
            );
        }
        if let Some(records) = c["input"].as_array() {
            let encoded: Vec<tier1::Tier1Record> = records
                .iter()
                .map(|r| {
                    tier1::Tier1Record::from_aggregate(
                        bits(&r["sum"]),
                        bits(&r["min"]),
                        bits(&r["max"]),
                        r["count"].as_u64().unwrap() as u16,
                        r["anomaly_count"].as_u64().unwrap() as u16,
                    )
                })
                .collect();
            for (r, want) in encoded.iter().zip(c["records"].as_array().unwrap()) {
                assert_eq!(to_hex(&r.encode()), want["hex"], "{name}");
            }
            assert_eq!(to_hex(&tier1::encode(&encoded)), c["page_hex"], "{name}");
        }
        // what a disk load gives back: the page's bytes, or the first `size` bytes of the disk input
        let mut disk = hex(c["page_hex"]
            .as_str()
            .or(c["disk_input_hex"].as_str())
            .unwrap());
        if let Some(size) = c["size"].as_u64() {
            disk.truncate(size as usize);
        }
        let from_disk = &c["from_disk"];
        if from_disk == "PGD_EMPTY" {
            let empty = if tier1 {
                tier1::decode(&disk).is_none()
            } else {
                page::array32_decode(&disk).is_none()
            };
            assert!(empty, "{name}");
            continue;
        }
        let wanted = from_disk["points_from_0"].as_array().unwrap();
        let used: Vec<StoragePoint> = if tier1 {
            tier1::decode(&disk)
                .unwrap_or_default()
                .iter()
                .map(tier1::Tier1Record::to_point)
                .collect()
        } else {
            page::array32_decode(&disk)
                .unwrap_or_default()
                .into_iter()
                .map(page::array32_point)
                .collect()
        };
        assert_eq!(
            used.len() as u64,
            from_disk["pgd_slots_used"].as_u64().unwrap(),
            "{name}"
        );
        assert_eq!(points(&used, wanted.len()), *wanted, "{name}");
    }
}

use netdata_agent_storage::dbengine::format::page::gorilla;

fn u32_hex(v: &Value) -> u32 {
    u32::from_str_radix(v.as_str().unwrap().trim_start_matches("0x"), 16).unwrap()
}

fn read_all(mut r: gorilla::Reader<'_>) -> Vec<Value> {
    std::iter::from_fn(|| r.read())
        .map(|n| Value::String(format!("0x{n:08x}")))
        .collect()
}

/// A gorilla cursor from slot 0 over `slots` points; a failed read is an empty point.
fn gorilla_points(buffers: &[gorilla::Buffer], slots: usize, wanted: usize) -> Vec<Value> {
    let mut r = gorilla::Reader::new(buffers);
    (0..wanted)
        .map(|i| match (i < slots).then(|| r.read()).flatten() {
            Some(n) => tuple(true, &page::array32_point(n)),
            None => tuple(false, &StoragePoint::empty(0, 0)),
        })
        .collect()
}

fn buffers_json(w: &gorilla::Writer) -> Vec<Value> {
    let last = w.buffers().len() - 1;
    w.buffers()
        .iter()
        .enumerate()
        .map(|(i, b)| {
            serde_json::json!({
                "next": if i == last { "zero" } else { "nonzero" },
                "entries": b.entries,
                "nbits": b.nbits,
                "hex_next_masked": to_hex(&b.to_bytes(0)),
            })
        })
        .collect()
}

#[test]
fn gorilla_writer_as_c() {
    let v = vectors("gorilla-writer.json");
    let cases = v["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 26);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let mut w = gorilla::Writer::default();
        let mut failures = Vec::new();
        for (index, n) in c["input_u32"]
            .as_array()
            .unwrap()
            .iter()
            .map(u32_hex)
            .enumerate()
        {
            let before = w.buffers().last().unwrap().nbits;
            if !w.write(n) {
                let last = w.buffers().last().unwrap();
                failures.push(serde_json::json!({
                    "index": index,
                    "full_buffer": w.buffers().len() - 1,
                    "nbits_before": before,
                    "nbits_after": last.nbits,
                    "partial_bits": last.nbits - before,
                    "entries": last.entries,
                }));
                w.add_buffer();
                assert!(w.write(n), "{name}");
            }
        }
        assert_eq!(Value::Array(failures), c["write_failures"], "{name}");
        assert_eq!(
            w.buffers().len() as u64,
            c["num_buffers"].as_u64().unwrap(),
            "{name}"
        );
        assert_eq!(
            u64::from(w.entries()),
            c["writer_entries"].as_u64().unwrap(),
            "{name}"
        );
        let bytes = w.serialize();
        assert_eq!(
            bytes.len() as u64,
            c["byte_length"].as_u64().unwrap(),
            "{name}"
        );
        assert_eq!(Value::Array(buffers_json(&w)), c["buffers"], "{name}");
        assert_eq!(
            Value::Array(read_all(w.reader())),
            c["decoded_live"],
            "{name}"
        );
        let disk = gorilla::from_disk(&bytes);
        assert_eq!(Value::Bool(disk.is_some()), c["disk_patch_ok"], "{name}");
        if let Some(disk) = disk {
            assert_eq!(
                u64::from(disk.entries),
                c["disk_patch_entries"].as_u64().unwrap(),
                "{name}"
            );
            assert_eq!(
                Value::Array(read_all(gorilla::Reader::new(&disk.buffers))),
                c["decoded_disk"],
                "{name}"
            );
        }
    }
}

#[test]
fn gorilla_pages_as_c() {
    let v = vectors("gorilla-page.json");
    let cases = v["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 10);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let mut w = gorilla::Writer::default();
        let mut grew = Vec::new();
        let values = c["input_values"].as_array().unwrap();
        let flags = c["input_flags"].as_array().unwrap();
        let mut packed = Vec::new();
        for (i, (v, f)) in values.iter().zip(flags).enumerate() {
            let n = pack(bits(v), f.as_u64().unwrap() as u32);
            packed.push(Value::String(format!("0x{n:08x}")));
            if w.append(n) {
                grew.push(i);
            }
        }
        let count = values.len();
        assert_eq!(Value::Array(packed), c["packed_u32"], "{name}");
        assert_eq!(
            serde_json::json!(grew),
            c["append_returned_buffer_size_at"],
            "{name}"
        );
        assert_eq!(
            count as u64,
            c["pgd_slots_used"].as_u64().unwrap(),
            "{name}"
        );
        if count > 0 {
            assert_eq!(
                w.buffers().len() as u64,
                c["num_buffers"].as_u64().unwrap(),
                "{name}"
            );
            assert_eq!(Value::Array(buffers_json(&w)), c["buffers"], "{name}");
            assert_eq!(
                (w.buffers().len() * gorilla::BUFFER_SIZE) as u64,
                c["disk_footprint"].as_u64().unwrap(),
                "{name}"
            );
        }
        let live = c["collector_points_from_0"].as_array().unwrap();
        assert_eq!(
            gorilla_points(w.buffers(), count, live.len()),
            *live,
            "{name}"
        );
        let from_disk = &c["from_disk"];
        if from_disk.is_object() {
            let disk = gorilla::from_disk(&w.serialize()).unwrap();
            assert_eq!(
                u64::from(disk.slots),
                from_disk["pgd_slots_used"].as_u64().unwrap(),
                "{name}"
            );
            let wanted = from_disk["points_from_0"].as_array().unwrap();
            assert_eq!(
                gorilla_points(&disk.buffers, disk.slots.into(), wanted.len()),
                *wanted,
                "{name}"
            );
        }
    }
}

#[test]
fn gorilla_disk_loads_as_c() {
    let v = vectors("gorilla-disk-load.json");
    let cases = v["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 24);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let mut bytes = hex(c["input_hex"].as_str().unwrap());
        bytes.truncate(c["size"].as_u64().unwrap() as usize);
        let disk = gorilla::from_disk(&bytes);
        let result = &c["result"];
        if result == "PGD_EMPTY" {
            assert!(disk.is_none(), "{name}");
            continue;
        }
        let disk = disk.unwrap_or_else(|| panic!("{name}: not loaded"));
        assert_eq!(
            u64::from(disk.slots),
            result["pgd_slots_used"].as_u64().unwrap(),
            "{name}"
        );
        let wanted = result["points_from_0"].as_array().unwrap();
        assert_eq!(
            gorilla_points(&disk.buffers, disk.slots.into(), wanted.len()),
            *wanted,
            "{name}"
        );
    }
}
