//! dbengine page formats against vectors the C implementation produced (`tests/vectors/dbengine/`, regenerated by
//! `tests/oracle/dbengine/gen.sh`; README there).

use std::path::PathBuf;

use netdata_agent_storage::dbengine::format::page::{self, tier1};
use netdata_agent_storage::storage_number::pack;
use netdata_agent_storage::storage_point::StoragePoint;
use serde_json::Value;

fn vectors(name: &str) -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/vectors/dbengine")
        .join(name);
    serde_json::from_str(&std::fs::read_to_string(&path).unwrap()).unwrap()
}

fn hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn to_hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn bits(v: &Value) -> f64 {
    f64::from_bits(u64::from_str_radix(v["bits"].as_str().unwrap(), 16).unwrap())
}

/// The vectors' point tuple: `[ok, sum_bits, min_bits, max_bits, count, anomaly_count, flags]`.
fn tuple(ok: bool, p: &StoragePoint) -> Value {
    serde_json::json!([
        ok,
        format!("{:016x}", p.sum.to_bits()),
        format!("{:016x}", p.min.to_bits()),
        format!("{:016x}", p.max.to_bits()),
        p.count,
        p.anomaly_count,
        p.flags
    ])
}

/// The cursor from slot 0: the used points, then empty ones.
fn points(used: &[StoragePoint], wanted: usize) -> Vec<Value> {
    (0..wanted)
        .map(|i| match used.get(i) {
            Some(p) => tuple(true, p),
            None => tuple(false, &StoragePoint::empty(0, 0)),
        })
        .collect()
}

#[test]
fn raw_pages_as_c() {
    let v = vectors("raw-pages.json");
    let cases = v["cases"].as_array().unwrap();
    assert_eq!(cases.len(), 8);
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let tier1 = c["page_type_id"] == 1;
        // what the writer puts on disk
        if let Some(values) = c["input_values"].as_array() {
            let flags = c["input_flags"].as_array().unwrap();
            let slots: Vec<u32> = values
                .iter()
                .zip(flags)
                .map(|(v, f)| pack(bits(v), f.as_u64().unwrap() as u32))
                .collect();
            let bytes = page::array32_encode(&slots);
            assert_eq!(to_hex(&bytes), c["page_hex"], "{name}");
            assert_eq!(
                bytes.len() as u64,
                c["disk_footprint"].as_u64().unwrap(),
                "{name}"
            );
        }
        if let Some(records) = c["input"].as_array() {
            let encoded: Vec<tier1::Tier1Record> = records
                .iter()
                .map(|r| {
                    tier1::Tier1Record::from_aggregate(
                        bits(&r["sum"]),
                        bits(&r["min"]),
                        bits(&r["max"]),
                        r["count"].as_u64().unwrap() as u16,
                        r["anomaly_count"].as_u64().unwrap() as u16,
                    )
                })
                .collect();
            for (r, want) in encoded.iter().zip(c["records"].as_array().unwrap()) {
                assert_eq!(to_hex(&r.encode()), want["hex"], "{name}");
            }
            assert_eq!(to_hex(&tier1::encode(&encoded)), c["page_hex"], "{name}");
        }
        // what a disk load gives back: the page's bytes, or the first `size` bytes of the disk input
        let mut disk = hex(c["page_hex"]
            .as_str()
            .or(c["disk_input_hex"].as_str())
            .unwrap());
        if let Some(size) = c["size"].as_u64() {
            disk.truncate(size as usize);
        }
        let from_disk = &c["from_disk"];
        if from_disk == "PGD_EMPTY" {
            let empty = if tier1 {
                tier1::decode(&disk).is_none()
            } else {
                page::array32_decode(&disk).is_none()
            };
            assert!(empty, "{name}");
            continue;
        }
        let wanted = from_disk["points_from_0"].as_array().unwrap();
        let used: Vec<StoragePoint> = if tier1 {
            tier1::decode(&disk)
                .unwrap_or_default()
                .iter()
                .map(tier1::Tier1Record::to_point)
                .collect()
        } else {
            page::array32_decode(&disk)
                .unwrap_or_default()
                .into_iter()
                .map(page::array32_point)
                .collect()
        };
        assert_eq!(
            used.len() as u64,
            from_disk["pgd_slots_used"].as_u64().unwrap(),
            "{name}"
        );
        assert_eq!(points(&used, wanted.len()), *wanted, "{name}");
    }
}
