[package]
name = "netdata-agent-rrd"
description = "Hosts, charts and dimensions of the netdata agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
netdata-agent-log = { workspace = true }
netdata-agent-nrpc = { workspace = true }
netdata-agent-storage = { workspace = true }
netdata-agent-text = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
tempfile = { workspace = true }
