[global]
    hostname = nd0
    config directory = /home/vk/repos/nd/multind/nd0/etc/netdata
    log directory = /home/vk/repos/nd/multind/nd0/var/log/netdata
    cache directory = /home/vk/repos/nd/multind/nd0/var/cache/netdata
    lib directory = /home/vk/repos/nd/multind/nd0/var/lib/netdata
    errors flood protection period = 9999
    errors to trigger flood protection = 999999
    memory mode = dbengine

[web]
    default port = 20000
