// SPDX-License-Identifier: GPL-3.0-or-later
//
// Golden vectors of the query progress table's row order (netdata-agent-web, `progress.rs`): a fixed-seed script of
// starts and finishes run through the production query_progress_*() functions, then the transactions in the order
// progress_function_result() lists them. Phase 1 churns a pool of 300 transactions (evictions past the 200 finished
// kept, tombstones in the index); phase 2 starts 500 more that never finish (the index grows past 400 live rows);
// phase 3 finishes those 500 (a burst of evictions); phase 4 starts and finishes 40000 new ids, as a long-running
// agent does: each eviction leaves a tombstone, new ids take most of them back, and when the slots fill up the probes
// grow long enough that the index is rebuilt at its size (six times here).
//
// Output lines: `S <tx>` a start, `F <tx> <code>` a finish, `R <tx> <tx> ...` a render's order, and
// `L <first> <count> <every>`: tx_of(first + i) started and finished (200) for each i < count, the next `R` line after
// every `every` of them.

#include "libnetdata/libnetdata.h"

static uint64_t rng_state = 0x70726f6772657373ULL;

static uint64_t rnd(void) {
    uint64_t z = (rng_state += 0x9e3779b97f4a7c15ULL);
    z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ULL;
    z = (z ^ (z >> 27)) * 0x94d049bb133111ebULL;
    return z ^ (z >> 31);
}

static void tx_of(nd_uuid_t *tx, uint64_t n) {
    uint64_t a = n * 0x9e3779b97f4a7c15ULL + 1, b = ~n * 0xbf58476d1ce4e5b9ULL;
    memcpy(&(*tx)[0], &a, 8);
    memcpy(&(*tx)[8], &b, 8);
}

static void print_tx(FILE *f, nd_uuid_t *tx) {
    char s[UUID_COMPACT_STR_LEN];
    uuid_unparse_lower_compact(*tx, s);
    fputs(s, f);
}

static void render(FILE *f, BUFFER *wb) {
    progress_function_result(wb, "h");
    // the rows' first cells are the only 32 lower-hex strings of the data array
    const char *s = buffer_tostring(wb), *end = strstr(s, "\"columns\"");
    fputc('R', f);
    for(const char *p = s; (p = strchr(p, '"')) && p < end; p++) {
        size_t n = 0;
        while(n < 32 && ((p[1 + n] >= '0' && p[1 + n] <= '9') || (p[1 + n] >= 'a' && p[1 + n] <= 'f')))
            n++;
        if(n == 32 && p[33] == '"') {
            fputc(' ', f);
            fwrite(p + 1, 1, 32, f);
            p += 33;
        }
    }
    fputc('\n', f);
}

int main(int argc, char **argv) {
    if(argc != 2) {
        fprintf(stderr, "usage: %s <output file>\n", argv[0]);
        return 1;
    }
    FILE *f = fopen(argv[1], "w");
    if(!f) return 1;
    fprintf(f, "# generated by tests/oracle/gen-progress.c from the C implementation; do not edit\n");
    BUFFER *wb = buffer_create(0, NULL);
    nd_uuid_t tx;
    usec_t t = 1000000;

    for(int i = 0; i < 2000; i++) {
        tx_of(&tx, rnd() % 300);
        if(rnd() % 10 < 6) {
            query_progress_start_or_update(&tx, ++t, HTTP_REQUEST_MODE_GET, 0, "q", NULL, "c");
            fputs("S ", f); print_tx(f, &tx); fputc('\n', f);
        }
        else {
            short code = (short)(200 + (rnd() % 4) * 100);
            query_progress_finished(&tx, ++t, code, 10, 1, 1);
            fputs("F ", f); print_tx(f, &tx); fprintf(f, " %d\n", code);
        }
    }
    render(f, wb);

    for(int i = 0; i < 500; i++) {
        tx_of(&tx, 1000 + (uint64_t)i);
        query_progress_start_or_update(&tx, ++t, HTTP_REQUEST_MODE_GET, 0, "q", NULL, "c");
        fputs("S ", f); print_tx(f, &tx); fputc('\n', f);
    }
    render(f, wb);

    for(int i = 0; i < 500; i++) {
        tx_of(&tx, 1000 + (uint64_t)i);
        query_progress_finished(&tx, ++t, 200, 10, 1, 1);
        fputs("F ", f); print_tx(f, &tx); fputs(" 200\n", f);
    }
    render(f, wb);

    // a long-running agent: unique ids, each finished, written as one line (its expansion in the Rust test)
    fprintf(f, "L %d %d %d\n", 100000, 40000, 10000);
    for(int i = 0; i < 40000; i++) {
        tx_of(&tx, 100000 + (uint64_t)i);
        query_progress_start_or_update(&tx, ++t, HTTP_REQUEST_MODE_GET, 0, "q", NULL, "c");
        query_progress_finished(&tx, ++t, 200, 10, 1, 1);
        if(i % 10000 == 9999)
            render(f, wb);
    }

    buffer_free(wb);
    fclose(f);
    return 0;
}
