[package]
name = "file-registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
crc32fast = { workspace = true }
gix-chunk = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
twox-hash = { workspace = true, features = ["xxhash64"] }
uuid = { workspace = true, features = ["serde"] }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
