// SPDX-License-Identifier: GPL-3.0-or-later
//
// Golden vectors for netdata-agent-storage: pack_storage_number() over edge and random doubles with every user flag
// combination, and unpack_storage_number() over edge and random 32-bit values. Doubles are written as IEEE-754 bits.

#include "libnetdata/libnetdata.h"

static uint64_t rng_state = 0x73746f7261676521ULL;
static uint64_t rnd(void) {
    uint64_t z = (rng_state += 0x9e3779b97f4a7c15ULL);
    z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ULL;
    z = (z ^ (z >> 27)) * 0x94d049bb133111ebULL;
    return z ^ (z >> 31);
}

static uint64_t bits_of(double v) { uint64_t b; memcpy(&b, &v, sizeof(b)); return b; }
static double double_of(uint64_t b) { double v; memcpy(&v, &b, sizeof(v)); return v; }

int main(int argc, char **argv) {
    if(argc != 2) { fprintf(stderr, "usage: %s DIR\n", argv[0]); return 1; }
    char path[4096];
    snprintf(path, sizeof(path), "%s/pack.tsv", argv[1]);
    FILE *fp = fopen(path, "w");
    snprintf(path, sizeof(path), "%s/unpack.tsv", argv[1]);
    FILE *fu = fopen(path, "w");
    if(!fp || !fu) { perror("open"); return 1; }
    fprintf(fp, "# generated by tests/oracle/gen-vectors.c from the C implementation; do not edit\n# value bits | flags | packed\n");
    fprintf(fu, "# generated by tests/oracle/gen-vectors.c from the C implementation; do not edit\n# packed | value bits\n");

    const double edges[] = { 0.0, -0.0, 1.0, -1.0, 0.1, 1e-7, 1e-8, 5e-324, 2.2250738585072014e-308, 16777215.0,
        16777215.5, 16777216.0, 16777216.5, 1677721.4, 1677721.5, 0x19999e, 0x19999d, 1e7, 1e14, 1.6777215e14,
        1.6777216e14, 1.6777215e21, 1e21, 1e22, 1e30, 1e300, DBL_MAX, -DBL_MAX, NAN, INFINITY, -INFINITY, 123.456,
        -0.5, 0.5, 1.5, 2.5, 12345678.9, 99999999.5, 0.000123, 3.14159265358979 };
    const uint32_t flags[] = { 0, SN_FLAG_NOT_ANOMALOUS, SN_FLAG_RESET, SN_FLAG_NOT_ANOMALOUS | SN_FLAG_RESET, 0xffffffff };
    for(size_t f = 0; f < sizeof(flags) / sizeof(flags[0]); f++) {
        for(size_t i = 0; i < sizeof(edges) / sizeof(edges[0]); i++)
            fprintf(fp, "%016" PRIx64 "\t%u\t%u\n", bits_of(edges[i]), flags[f], pack_storage_number(edges[i], flags[f]));
        for(int k = 0; k < 4000; k++) {
            double v;
            switch(k % 4) {
                case 0: v = double_of(rnd()); break;
                case 1: v = (double)(int64_t)(rnd() >> (rnd() % 64)) * ((rnd() & 1) ? -1.0 : 1.0); break;
                case 2: v = (double)(rnd() % 100000000) / (double)(1ULL << (rnd() % 40)); break;
                default: v = ldexp((double)(rnd() & 0xffffff), (int)(rnd() % 120) - 60); break;
            }
            fprintf(fp, "%016" PRIx64 "\t%u\t%u\n", bits_of(v), flags[f], pack_storage_number(v, flags[f]));
        }
    }
    const uint32_t uedges[] = { 0, SN_EMPTY_SLOT, 0xffffffff, 0x00ffffff, 0x80000000, 0x40000000, 0x7fffffff,
        STORAGE_NUMBER_POSITIVE_MAX_RAW, STORAGE_NUMBER_POSITIVE_MIN_RAW, STORAGE_NUMBER_NEGATIVE_MAX_RAW,
        STORAGE_NUMBER_NEGATIVE_MIN_RAW };
    for(size_t i = 0; i < sizeof(uedges) / sizeof(uedges[0]); i++)
        fprintf(fu, "%u\t%016" PRIx64 "\n", uedges[i], bits_of(unpack_storage_number(uedges[i])));
    for(int k = 0; k < 20000; k++) {
        uint32_t u = (uint32_t)rnd();
        fprintf(fu, "%u\t%016" PRIx64 "\n", u, bits_of(unpack_storage_number(u)));
    }
    fclose(fp);
    fclose(fu);
    return 0;
}
