// This file is @generated by prost-build.
/// A function declaration message for Netdata's external plugin protocol
#[cfg_attr(feature = "with-serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "with-serde", serde(rename_all = "camelCase"))]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionDeclaration {
    /// True if the function is global
    #[prost(bool, tag = "1")]
    pub global: bool,
    /// The name of the function
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Timeout in seconds for function execution
    #[prost(uint32, tag = "3")]
    pub timeout: u32,
    /// Help text describing what the function does
    #[prost(string, tag = "4")]
    pub help: ::prost::alloc::string::String,
    /// Tags of the function
    #[prost(string, optional, tag = "5")]
    pub tags: ::core::option::Option<::prost::alloc::string::String>,
    /// Access control flags for the function
    #[prost(uint32, optional, tag = "6")]
    pub access: ::core::option::Option<u32>,
    /// Priority level for function execution
    #[prost(uint32, optional, tag = "7")]
    pub priority: ::core::option::Option<u32>,
    /// Version of the function
    #[prost(uint32, optional, tag = "8")]
    pub version: ::core::option::Option<u32>,
}
/// A function call message for invoking functions (input context)
#[cfg_attr(feature = "with-serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "with-serde", serde(rename_all = "camelCase"))]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionCall {
    /// Transaction ID for this function call
    #[prost(string, tag = "1")]
    pub transaction: ::prost::alloc::string::String,
    /// Timeout in seconds for function execution
    #[prost(uint32, tag = "2")]
    pub timeout: u32,
    /// Function name to call
    #[prost(string, tag = "3")]
    pub function: ::prost::alloc::string::String,
    /// Access control flags for the function
    #[prost(uint32, optional, tag = "4")]
    pub access: ::core::option::Option<u32>,
    /// Source information containing caller details
    #[prost(string, optional, tag = "5")]
    pub source: ::core::option::Option<::prost::alloc::string::String>,
    /// Payload data for the function call (optional)
    #[prost(bytes = "vec", optional, tag = "6")]
    pub payload: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// A function result message containing the response payload
#[cfg_attr(feature = "with-serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "with-serde", serde(rename_all = "camelCase"))]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionResult {
    /// Transaction ID or unique identifier for this function call
    #[prost(string, tag = "1")]
    pub transaction: ::prost::alloc::string::String,
    /// Status of the function call
    #[prost(uint32, tag = "2")]
    pub status: u32,
    /// Content type of the result (e.g., "application/json", "text/plain")
    #[prost(string, tag = "3")]
    pub format: ::prost::alloc::string::String,
    /// Expires timestamp
    #[prost(uint32, tag = "4")]
    pub expires: u32,
    /// Result payload data
    #[prost(bytes = "vec", tag = "5")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
/// A function cancel message for terminating function execution
#[cfg_attr(feature = "with-serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "with-serde", serde(rename_all = "camelCase"))]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionCancel {
    /// Transaction ID of the function call to cancel
    #[prost(string, tag = "1")]
    pub transaction: ::prost::alloc::string::String,
}
