// This file is @generated by prost-build.
/// A function declaration message for Netdata's external plugin protocol
#[cfg_attr(feature = "with-serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "with-serde", serde(rename_all = "camelCase"))]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionDeclaration {
    /// True if the function is global
    #[prost(bool, tag = "1")]
    pub global: bool,
    /// The name of the function
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Timeout in seconds for function execution
    #[prost(uint32, tag = "3")]
    pub timeout: u32,
    /// Help text describing what the function does
    #[prost(string, tag = "4")]
    pub help: ::prost::alloc::string::String,
    /// Tags of the function
    #[prost(string, optional, tag = "5")]
    pub tags: ::core::option::Option<::prost::alloc::string::String>,
    /// Access control flags for the function
    #[prost(uint32, optional, tag = "6")]
    pub access: ::core::option::Option<u32>,
    /// Priority level for function execution
    #[prost(uint32, optional, tag = "7")]
    pub priority: ::core::option::Option<u32>,
    /// Version of the function
    #[prost(uint32, optional, tag = "8")]
    pub version: ::core::option::Option<u32>,
}
/// A function call message for invoking functions (input context)
#[cfg_attr(feature = "with-serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "with-serde", serde(rename_all = "camelCase"))]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionCall {
    /// Transaction ID for this function call
    #[prost(string, tag = "1")]
    pub transaction: ::prost::alloc::string::String,
    /// Timeout in seconds for function execution
    #[prost(uint32, tag = "2")]
    pub timeout: u32,
    /// Function name to call
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    /// Access control flags for the function
    #[prost(uint32, optional, tag = "4")]
    pub access: ::core::option::Option<u32>,
    /// Source information containing caller details
    #[prost(string, optional, tag = "5")]
    pub source: ::core::option::Option<::prost::alloc::string::String>,
    /// Payload data for the function call (optional)
    #[prost(bytes = "vec", optional, tag = "6")]
    pub payload: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
/// A function result message containing the response payload
#[cfg_attr(feature = "with-serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "with-serde", serde(rename_all = "camelCase"))]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionResult {
    /// Transaction ID or unique identifier for this function call
    #[prost(string, tag = "1")]
    pub transaction: ::prost::alloc::string::String,
    /// Status of the function call
    #[prost(uint32, tag = "2")]
    pub status: u32,
    /// Content type of the result (e.g., "application/json", "text/plain")
    #[prost(string, tag = "3")]
    pub format: ::prost::alloc::string::String,
    /// Expires timestamp
    #[prost(uint32, tag = "4")]
    pub expires: u32,
    /// Result payload data
    #[prost(bytes = "vec", tag = "5")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
/// A function cancel message for terminating function execution
#[cfg_attr(feature = "with-serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "with-serde", serde(rename_all = "camelCase"))]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionCancel {
    /// Transaction ID of the function call to cancel
    #[prost(string, tag = "1")]
    pub transaction: ::prost::alloc::string::String,
}
/// Generated client implementations.
#[cfg(feature = "gen-tonic")]
pub mod plugin_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Service for managing plugin functions
    #[derive(Debug, Clone)]
    pub struct PluginClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PluginClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PluginClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PluginClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PluginClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Call a function
        pub async fn call_function(
            &mut self,
            request: impl tonic::IntoRequest<super::FunctionCall>,
        ) -> std::result::Result<tonic::Response<super::FunctionResult>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/netdata.v1.Plugin/CallFunction",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("netdata.v1.Plugin", "CallFunction"));
            self.inner.unary(req, path, codec).await
        }
        /// Cancel a function
        pub async fn cancel_function(
            &mut self,
            request: impl tonic::IntoRequest<super::FunctionCancel>,
        ) -> std::result::Result<tonic::Response<super::FunctionResult>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/netdata.v1.Plugin/CancelFunction",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("netdata.v1.Plugin", "CancelFunction"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
#[cfg(feature = "gen-tonic")]
pub mod plugin_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with PluginServer.
    #[async_trait]
    pub trait Plugin: std::marker::Send + std::marker::Sync + 'static {
        /// Call a function
        async fn call_function(
            &self,
            request: tonic::Request<super::FunctionCall>,
        ) -> std::result::Result<tonic::Response<super::FunctionResult>, tonic::Status>;
        /// Cancel a function
        async fn cancel_function(
            &self,
            request: tonic::Request<super::FunctionCancel>,
        ) -> std::result::Result<tonic::Response<super::FunctionResult>, tonic::Status>;
    }
    /// Service for managing plugin functions
    #[derive(Debug)]
    pub struct PluginServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> PluginServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for PluginServer<T>
    where
        T: Plugin,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/netdata.v1.Plugin/CallFunction" => {
                    #[allow(non_camel_case_types)]
                    struct CallFunctionSvc<T: Plugin>(pub Arc<T>);
                    impl<T: Plugin> tonic::server::UnaryService<super::FunctionCall>
                    for CallFunctionSvc<T> {
                        type Response = super::FunctionResult;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FunctionCall>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Plugin>::call_function(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CallFunctionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/netdata.v1.Plugin/CancelFunction" => {
                    #[allow(non_camel_case_types)]
                    struct CancelFunctionSvc<T: Plugin>(pub Arc<T>);
                    impl<T: Plugin> tonic::server::UnaryService<super::FunctionCancel>
                    for CancelFunctionSvc<T> {
                        type Response = super::FunctionResult;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FunctionCancel>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Plugin>::cancel_function(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CancelFunctionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for PluginServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "netdata.v1.Plugin";
    impl<T> tonic::server::NamedService for PluginServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
