#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Regenerates the golden vectors of netdata-agent-text from the C implementation:
#   - tests/vectors/*.tsv          from gen-vectors.c
#   - tests/vectors/utf8_unittest_cases.rs from the case table of utf8-sanitizer-unittest.c
#
# Usage:
#   NETDATA_SRC=/path/to/netdata [NETDATA_BUILD=/path/to/netdata/build] tests/oracle/gen-vectors.sh
#
# NETDATA_BUILD must hold a CMake build of NETDATA_SRC (liblibnetdata.a,
# config.h). The generator is compiled with the flags of that build (gcc,
# -O2, LTO) so it runs the production code paths.

set -euo pipefail

# shellcheck source=../../../c-oracle/lib.sh
source "$(dirname -- "${BASH_SOURCE[0]}")/../../../c-oracle/lib.sh"

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
CRATE_DIR=$(cd -- "${SCRIPT_DIR}/../.." && pwd)
[[ -f "${CRATE_DIR}/Cargo.toml" && -d "${CRATE_DIR}/tests/vectors" ]] || die "unexpected crate layout at ${CRATE_DIR}"

c_oracle_env

WORK=$(mktemp -d "${TMPDIR:-/tmp}/netdata-agent-text-oracle.XXXXXX")
trap 'rm -rf -- "${WORK}"' EXIT

run cc "${CFLAGS[@]}" "${SCRIPT_DIR}/gen-vectors.c" -o "${WORK}/gen-vectors" "${LIBS[@]}"
run "${WORK}/gen-vectors" "${CRATE_DIR}/tests/vectors"

# the case table of utf8-sanitizer-unittest.c, dumped while the C test runs
UNITTEST="${SRC}/src/libnetdata/sanitizers/utf8-sanitizer-unittest.c"
[[ -f "${UNITTEST}" ]] || die "missing ${UNITTEST}"
awk -v inc="${SCRIPT_DIR}/utf8-unittest-dump.inc" '
    /^static void run_sanitize_test\(const sanitize_test_t \*t\) \{$/ {
        while ((getline line < inc) > 0) print line
        print
        print "    dump_case(t);"
        found = 1
        next
    }
    { print }
    END { if (!found) exit 1 }
' "${UNITTEST}" > "${WORK}/utf8-unittest.c" || die "run_sanitize_test() not found in ${UNITTEST}"
printf '\nint main(void) { return utf8_sanitizer_unittest(); }\n' >> "${WORK}/utf8-unittest.c"

run cc "${CFLAGS[@]}" -iquote "${SRC}/src/libnetdata/sanitizers" "${WORK}/utf8-unittest.c" \
    -o "${WORK}/utf8-unittest" "${LIBS[@]}"
run "${WORK}/utf8-unittest" >"${WORK}/utf8-unittest-cases.rs" 2>"${WORK}/utf8-unittest.log" \
    || die "the C unit test failed: $(tail -n 5 "${WORK}/utf8-unittest.log")"
{
    printf '// generated by tests/oracle/gen-vectors.sh from src/libnetdata/sanitizers/utf8-sanitizer-unittest.c; do not edit\n\n'
    printf 'const CASES: &[Case] = &[\n'
    cat "${WORK}/utf8-unittest-cases.rs"
    printf '];\n'
} >"${CRATE_DIR}/tests/vectors/utf8_unittest_cases.rs"

printf >&2 "vectors written to %s\n" "${CRATE_DIR}/tests/vectors"
