// SPDX-License-Identifier: GPL-3.0-or-later
//
// Golden vectors for netdata-agent-text's jsonc_doc module: what json-c makes of a text with the calls
// /api/v3/settings uses (src/web/api/v3/api_v3_settings.c): json_tokener_parse(), json_object_to_json_string(),
// json_object_object_get_ex(.., "version", ..) with json_object_get_int(), and json_object_object_add(..,
// "version", ..) followed by another print.
//
// Usage: gen-jsonc-doc <inputs file> <vector file>. Links the system's json-c alone (see gen-jsonc-doc.sh).
//
// Field encoding (shared with tests/common/mod.rs): bytes 0x20..0x7e except '\' and '#' are written as-is, '\' as
// "\\", every other byte as "\xHH". An input line is "<flag> <text>" with the text in this encoding; lines that
// start with '#' are comments.

#include <json-c/json.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void esc(FILE *f, const char *s, size_t len) {
    for(size_t i = 0; i < len; i++) {
        unsigned char c = (unsigned char)s[i];
        if(c == '\\')
            fputs("\\\\", f);
        else if(c >= 0x20 && c <= 0x7e && c != '#')
            fputc(c, f);
        else
            fprintf(f, "\\x%02x", c);
    }
}

// Decodes a field in place; returns its length (the bytes may hold a NUL).
static size_t unesc(char *s) {
    char *d = s;
    const char *start = s;
    while(*s) {
        if(s[0] == '\\' && s[1] == '\\') {
            *d++ = '\\';
            s += 2;
        }
        else if(s[0] == '\\' && s[1] == 'x' && s[2] && s[3]) {
            char hex[3] = { s[2], s[3], 0 };
            *d++ = (char)strtol(hex, NULL, 16);
            s += 4;
        }
        else
            *d++ = *s++;
    }
    *d = '\0';
    return (size_t)(d - start);
}

int main(int argc, char **argv) {
    if(argc != 3) {
        fprintf(stderr, "usage: %s <inputs file> <vector file>\n", argv[0]);
        return 1;
    }

    FILE *in = fopen(argv[1], "r");
    FILE *out = fopen(argv[2], "w");
    if(!in || !out) {
        fprintf(stderr, "cannot open %s or create %s\n", argv[1], argv[2]);
        return 1;
    }

    fprintf(out, "# generated by tests/oracle/gen-jsonc-doc.c from json-c %s; do not edit\n", json_c_version());
    fprintf(out, "# columns: flag, text, parsed, printed, has_version, version_int, printed_after_version_7\n");

    char *line = NULL;
    size_t size = 0;
    ssize_t len;
    size_t rows = 0;
    while((len = getline(&line, &size, in)) != -1) {
        if(len && line[len - 1] == '\n')
            line[--len] = '\0';

        if(!len || line[0] == '#')
            continue;

        // (a text of spaces alone is written with its spaces encoded, so that no editor can strip it)
        if((line[0] != 'A' && line[0] != 'R') || (line[1] != ' ' && line[1] != '\0')) {
            fprintf(stderr, "bad input line: %s\n", line);
            return 1;
        }

        char flag = line[0];
        char *text = strdup(len > 2 ? line + 2 : "");
        size_t text_len = unesc(text);

        fputc(flag, out);
        fputc('\t', out);
        esc(out, text, text_len);
        fputc('\t', out);

        // the C string, as the handler passes it: json-c reads up to the first NUL
        struct json_object *jobj = json_tokener_parse(text);
        if(!jobj)
            fputs("0\t\t0\t0\t", out);
        else {
            fputs("1\t", out);
            const char *printed = json_object_to_json_string(jobj);
            esc(out, printed, strlen(printed));
            fputc('\t', out);

            struct json_object *version;
            if(json_object_object_get_ex(jobj, "version", &version))
                fprintf(out, "1\t%d\t", json_object_get_int(version));
            else
                fputs("0\t0\t", out);

            if(json_object_is_type(jobj, json_type_object)) {
                json_object_object_add(jobj, "version", json_object_new_int(7));
                printed = json_object_to_json_string(jobj);
                esc(out, printed, strlen(printed));
            }

            json_object_put(jobj);
        }

        fputc('\n', out);
        free(text);
        rows++;
    }

    free(line);
    fclose(in);
    if(fclose(out) != 0) {
        fprintf(stderr, "cannot write %s\n", argv[2]);
        return 1;
    }

    fprintf(stderr, "%zu rows\n", rows);
    return 0;
}
