// SPDX-License-Identifier: GPL-3.0-or-later
//
// Golden vector generator for the netdata-agent-text crate.
//
// Links against the production libnetdata (see gen-vectors.sh) and writes one
// tab-separated file per function family into the directory given as the
// only argument. Inputs are deterministic (fixed-seed splitmix64).
//
// Field encoding (shared with tests/common/mod.rs): bytes 0x20..0x7e except
// '\' and '#' are written as-is, '\' as "\\", every other byte as "\xHH".
// Lines that start with '#' are comments (data never starts with a raw '#').
// Multi-valued fields join items with 0x1f before encoding.

#include "libnetdata/libnetdata.h"

// ------------------------------------------------------------------------------------------------
// output helpers

static FILE *out_open(const char *dir, const char *name, const char *columns) {
    char path[4096];
    snprintf(path, sizeof(path), "%s/%s", dir, name);
    FILE *f = fopen(path, "w");
    if(!f) {
        fprintf(stderr, "cannot create %s\n", path);
        exit(1);
    }
    fprintf(f, "# generated by tests/oracle/gen-vectors.c from the C implementation; do not edit\n");
    fprintf(f, "# columns: %s\n", columns);
    return f;
}

static void esc(FILE *f, const void *data, size_t len) {
    const unsigned char *s = data;
    for(size_t i = 0; i < len; i++) {
        unsigned char c = s[i];
        if(c == '\\')
            fputs("\\\\", f);
        else if(c >= 0x20 && c <= 0x7e && c != '#')
            fputc(c, f);
        else
            fprintf(f, "\\x%02x", c);
    }
}

static void esc_str(FILE *f, const char *s) {
    esc(f, s, strlen(s));
}

static void tab(FILE *f) { fputc('\t', f); }
static void eol(FILE *f) { fputc('\n', f); }

static uint64_t bits_of(double d) {
    uint64_t u;
    memcpy(&u, &d, sizeof(u));
    return u;
}

static double double_of(uint64_t u) {
    double d;
    memcpy(&d, &u, sizeof(d));
    return d;
}

// ------------------------------------------------------------------------------------------------
// deterministic randomness

static uint64_t rng_state = 0x6e65746461746121ULL;

static uint64_t rnd(void) {
    uint64_t z = (rng_state += 0x9e3779b97f4a7c15ULL);
    z = (z ^ (z >> 30)) * 0xbf58476d1ce4e5b9ULL;
    z = (z ^ (z >> 27)) * 0x94d049bb133111ebULL;
    return z ^ (z >> 31);
}

static uint64_t rnd_below(uint64_t n) {
    return n ? rnd() % n : 0;
}

static const char *pick(const char *const *items, size_t count) {
    return items[rnd_below(count)];
}

#define PICK(arr) pick((arr), sizeof(arr) / sizeof((arr)[0]))
#define COUNT(arr) (sizeof(arr) / sizeof((arr)[0]))

// a random string of up to max_len bytes drawn from alphabet
static void rnd_string(char *dst, size_t max_len, const char *alphabet) {
    size_t n = rnd_below(max_len + 1);
    size_t a = strlen(alphabet);
    for(size_t i = 0; i < n; i++)
        dst[i] = alphabet[rnd_below(a)];
    dst[n] = '\0';
}

// a random string made of tokens
static void rnd_tokens(char *dst, size_t dst_size, const char *const *tokens, size_t count, size_t max_tokens) {
    dst[0] = '\0';
    size_t n = rnd_below(max_tokens + 1);
    for(size_t i = 0; i < n; i++) {
        const char *t = tokens[rnd_below(count)];
        if(strlen(dst) + strlen(t) + 1 >= dst_size)
            break;
        strcat(dst, t);
    }
}

// random double: raw bits, "decimal-like" or scaled integers
static double rnd_double(void) {
    switch(rnd_below(6)) {
        case 0:
            return double_of(rnd());
        case 1: {
            double v = (double)rnd_below(100000000) / pow(10, (double)rnd_below(12));
            return rnd_below(2) ? -v : v;
        }
        case 2: {
            double v = (double)(rnd() >> rnd_below(64));
            return rnd_below(2) ? -v : v;
        }
        case 3: {
            // exact binary fractions: llrint() ties
            double v = (double)rnd_below(1 << 20) / (double)(1ULL << rnd_below(40));
            return rnd_below(2) ? -v : v;
        }
        case 4: {
            double v = pow(10, (double)((int)rnd_below(640) - 320)) * (1.0 + (double)rnd_below(1000) / 1000.0);
            return rnd_below(2) ? -v : v;
        }
        default: {
            double v = (double)rnd_below(1000000) + (double)rnd_below(10000000) * 1e-7 + ((double)rnd_below(3) - 1.0) * 5e-8;
            return rnd_below(2) ? -v : v;
        }
    }
}

// ------------------------------------------------------------------------------------------------
// 1. number printing

// keeps the compiler from folding the conversions of non-finite constants
static double opaque(double v) {
    volatile double x = v;
    return x;
}

// the bit patterns already written, so that every input appears once
#define SEEN_SLOTS (1 << 17)
static uint64_t seen_bits[SEEN_SLOTS];
static bool seen_used[SEEN_SLOTS];

static bool seen_before(uint64_t bits) {
    size_t slot = (size_t)((bits * 0x9e3779b97f4a7c15ULL) >> 47);
    while(seen_used[slot]) {
        if(seen_bits[slot] == bits)
            return true;
        slot = (slot + 1) & (SEEN_SLOTS - 1);
    }
    seen_used[slot] = true;
    seen_bits[slot] = bits;
    return false;
}

static void print_double_line(FILE *f, BUFFER *wb, double value) {
    char tmp[DOUBLE_MAX_LENGTH + 2];
    double v = opaque(value);
    if(seen_before(bits_of(v)))
        return;

    fprintf(f, "%016" PRIx64, bits_of(v));

    print_netdata_double(tmp, v);
    tab(f); esc_str(f, tmp);

    buffer_flush(wb);
    buffer_print_netdata_double_encoded(wb, NUMBER_ENCODING_DECIMAL, v);
    tab(f); esc_str(f, buffer_tostring(wb));

    buffer_flush(wb);
    buffer_print_netdata_double_encoded(wb, NUMBER_ENCODING_HEX, v);
    tab(f); esc_str(f, buffer_tostring(wb));

    buffer_flush(wb);
    buffer_print_netdata_double_encoded(wb, NUMBER_ENCODING_BASE64, v);
    tab(f); esc_str(f, buffer_tostring(wb));

    eol(f);
}

static void gen_print_double(const char *dir, BUFFER *wb) {
    FILE *f = out_open(dir, "print_double.tsv",
                       "f64 bits (hex) | print_netdata_double | buffer_print_netdata_double | hex encoded | base64 encoded");

    const uint64_t special_bits[] = {
        0x0000000000000000ULL, 0x8000000000000000ULL, 0x7ff0000000000000ULL, 0xfff0000000000000ULL,
        0x7ff8000000000000ULL, 0xfff8000000000000ULL, 0x7ff0000000000001ULL, 0x7ff4000000000000ULL,
        0xfff8000000000123ULL, 0x0000000000000001ULL, 0x8000000000000001ULL, 0x000fffffffffffffULL,
        0x0010000000000000ULL, 0x7fefffffffffffffULL, 0xffefffffffffffffULL,
    };
    for(size_t i = 0; i < COUNT(special_bits); i++)
        print_double_line(f, wb, double_of(special_bits[i]));

    // the unit test tables of daemon/unit_test.c and storage_number/tests
    const double table[] = {
        0, 0.0000001, 0.00000009, 0.000000001, 99.99999999999999999, -99.99999999999999999,
        123.4567899123456789, 123.4567890123456789, 123.4567800123456789, 123.4567000123456789,
        123.4560000123456789, 123.4500000123456789, 123.4000000123456789, 123.0000000123456789,
        123.0000000923456789, 4294967295.123456789, 8294967295.123456789, 1.000000000000002e+19,
        9.2233720368547676e+18, 18446744073709541376.0, 18446744073709551616.0, 12318446744073710600192.0,
        1677721499999999885312.0, -1677721499999999885312.0, -1.677721499999999885312e40,
        -16777214999999997337621690403742592008192.0, 9999.9999999, -9999.9999999, 1.5, 1.23e+14,
        9.12345678901234567890123456789e+45, 16.777218, 0.5, 0.05, 0.00000005, 0.00000015, 0.00000025,
        -0.00000004, -0.00000005, -0.00000006, 1e-300, -1e-300,
    };
    for(size_t i = 0; i < COUNT(table); i++)
        print_double_line(f, wb, table[i]);

    // the switch to exponential notation and its neighbourhood
    double threshold = (double)(UINT64_MAX / 10);
    for(int sign = 0; sign < 2; sign++) {
        double v = sign ? -threshold : threshold;
        double lo = v, hi = v;
        print_double_line(f, wb, v);
        for(int i = 0; i < 64; i++) {
            lo = nextafter(lo, 0);
            hi = nextafter(hi, sign ? -INFINITY : INFINITY);
            print_double_line(f, wb, lo);
            print_double_line(f, wb, hi);
        }
    }

    // powers of ten and their neighbours
    for(int e = -330; e <= 310; e++) {
        double p = pow(10, e);
        const double mul[] = { 1, 2, 5, 9.999999, 0.999999999 };
        for(size_t m = 0; m < COUNT(mul); m++) {
            double v = p * mul[m];
            print_double_line(f, wb, v);
            print_double_line(f, wb, -v);
            print_double_line(f, wb, nextafter(v, INFINITY));
            print_double_line(f, wb, nextafter(v, 0));
        }
    }

    // exact binary fractions (ties in llrint) and 7-digit rounding edges
    for(int k = 1; k <= 30; k++) {
        for(int n = 1; n < 64; n += 2) {
            double v = (double)n / (double)(1ULL << k);
            print_double_line(f, wb, v);
            print_double_line(f, wb, -v);
            print_double_line(f, wb, v + 1000.0);
        }
    }
    for(int i = 0; i < 2000; i++) {
        double base = (double)rnd_below(100000);
        double v = base + (double)rnd_below(10000000) / 1e7 + (double)((int)rnd_below(21) - 10) * 1e-9;
        print_double_line(f, wb, v);
    }

    // integers around 2^53, 2^63 and 2^64
    for(int e = 50; e <= 66; e++) {
        double p = ldexp(1, e);
        for(int d = -4; d <= 4; d++) {
            print_double_line(f, wb, p + d);
            print_double_line(f, wb, nextafter(p, d < 0 ? 0 : INFINITY));
        }
    }

    for(int i = 0; i < 12000; i++)
        print_double_line(f, wb, rnd_double());

    fclose(f);
}

static void gen_print_integers(const char *dir, BUFFER *wb) {
    FILE *fu = out_open(dir, "print_uint64.tsv", "u64 | decimal | hex | hex full | base64");
    FILE *fi = out_open(dir, "print_int64.tsv", "i64 | decimal | hex | base64");

    uint64_t values[8000];
    size_t n = 0;
    values[n++] = 0;
    values[n++] = UINT64_MAX;
    values[n++] = (uint64_t)INT64_MAX;
    values[n++] = (uint64_t)INT64_MIN;
    values[n++] = 1676071986;
    for(int b = 0; b < 64; b++) {
        values[n++] = 1ULL << b;
        values[n++] = (1ULL << b) - 1;
        values[n++] = (1ULL << b) + 1;
        values[n++] = 0 - (1ULL << b);
    }
    for(uint64_t p = 1, i = 0; i < 20; i++, p *= 10) {
        values[n++] = p;
        values[n++] = p - 1;
        values[n++] = p + 1;
    }
    while(n < COUNT(values))
        values[n++] = rnd() >> rnd_below(64);

    for(size_t i = 0; i < n; i++) {
        uint64_t v = values[i];

        fprintf(fu, "%" PRIu64, v);
        buffer_flush(wb); buffer_print_uint64_encoded(wb, NUMBER_ENCODING_DECIMAL, v);
        tab(fu); esc_str(fu, buffer_tostring(wb));
        buffer_flush(wb); buffer_print_uint64_encoded(wb, NUMBER_ENCODING_HEX, v);
        tab(fu); esc_str(fu, buffer_tostring(wb));
        buffer_flush(wb); buffer_print_uint64_hex_full(wb, v);
        tab(fu); esc_str(fu, buffer_tostring(wb));
        buffer_flush(wb); buffer_print_uint64_encoded(wb, NUMBER_ENCODING_BASE64, v);
        tab(fu); esc_str(fu, buffer_tostring(wb));
        eol(fu);

        int64_t s = (int64_t)v;
        fprintf(fi, "%" PRId64, s);
        buffer_flush(wb); buffer_print_int64_encoded(wb, NUMBER_ENCODING_DECIMAL, s);
        tab(fi); esc_str(fi, buffer_tostring(wb));
        buffer_flush(wb); buffer_print_int64_encoded(wb, NUMBER_ENCODING_HEX, s);
        tab(fi); esc_str(fi, buffer_tostring(wb));
        buffer_flush(wb); buffer_print_int64_encoded(wb, NUMBER_ENCODING_BASE64, s);
        tab(fi); esc_str(fi, buffer_tostring(wb));
        eol(fi);
    }

    fclose(fu);
    fclose(fi);
}

// ------------------------------------------------------------------------------------------------
// 2. number parsing

static void parse_line(FILE *f, const char *input) {
    char *end;
    esc_str(f, input);

    NETDATA_DOUBLE d = str2ndd(input, &end);
    fprintf(f, "\t%016" PRIx64 "\t%td", bits_of(d), end - input);

    d = str2ndd_encoded(input, &end);
    fprintf(f, "\t%016" PRIx64 "\t%td", bits_of(d), end - input);

    d = strtod(input, &end);
    fprintf(f, "\t%016" PRIx64 "\t%td", bits_of(d), end - input);

    uint64_t u64 = str2uint64_t(input, &end);
    fprintf(f, "\t%" PRIu64 "\t%td", u64, end - input);

    uint32_t u32 = str2uint32_t(input, &end);
    fprintf(f, "\t%" PRIu32 "\t%td", u32, end - input);

    long long ll = str2ll(input, &end);
    fprintf(f, "\t%lld\t%td", ll, end - input);

    fprintf(f, "\t%u\t%d\t%lu\t%ld", str2u(input), str2i(input), str2ul(input), str2l(input));
    fprintf(f, "\t%llu\t%lld", str2ull_encoded(input), str2ll_encoded(input));

    u64 = str2uint64_hex(input, &end);
    fprintf(f, "\t%" PRIu64 "\t%td", u64, end - input);

    u32 = str2uint32_hex(input, &end);
    fprintf(f, "\t%" PRIu32 "\t%td", u32, end - input);

    u64 = str2uint64_base64(input, &end);
    fprintf(f, "\t%" PRIu64 "\t%td", u64, end - input);

    eol(f);
}

static void gen_parse_numbers(const char *dir, BUFFER *wb) {
    FILE *f = out_open(dir, "parse_numbers.tsv",
                       "input | str2ndd bits | used | str2ndd_encoded bits | used | strtod bits | used"
                       " | str2uint64_t | used | str2uint32_t | used | str2ll | used | str2u | str2i | str2ul | str2l"
                       " | str2ull_encoded | str2ll_encoded | str2uint64_hex | used | str2uint32_hex | used"
                       " | str2uint64_base64 | used");

    static const char *curated[] = {
        // unit_test_str2ld()
        "1.2345678", "-35.6", "0.00123", "23842384234234.2", ".1", "1.2e-10", "18446744073709551616.0",
        "18446744073709551616123456789123456789123456789123456789123456789123456789123456789.0",
        "1.8446744073709551616123456789123456789123456789123456789123456789123456789123456789e+300",
        "9.", "9.e2", "1.2e", "1.2e+", "1.2e-", "1.2e0", "1.2e-0", "1.2e+0", "-1.2e+1", "-1.2e-1", "1.2e1",
        "1.2e400", "hello", "1wrong", "nan", "inf",
        // buffer_unittest() int64 parsing table
        "0", "-0", "9223372036854775807", "0x7FFFFFFFFFFFFFFF", "#H//////////", "-9223372036854775808",
        "-0x8000000000000000", "-#IAAAAAAAAAA", "9223372036854775808", "0x8000000000000000", "#IAAAAAAAAAA",
        "-9223372036854775809", "-0x8000000000000001", "-#IAAAAAAAAAB", "18446744073709551615",
        "-18446744073709551615", "18446744073709551616", "0x10000000000000000", "#QAAAAAAAAAA",
        " 9223372036854775808", " -9223372036854775808", "- 9223372036854775808", " 0x8000000000000000",
        "- 0x8000000000000000", "-9223372036854775808suffix", "-0x8000000000000000!suffix",
        "-#IAAAAAAAAAA!suffix", "", "-", "+1", "--1", "#", "0x", "-#", "-0x",
        // buffer_unittest() round trips
        "#A", "0x63E6D432", "#Bj5tQy", "0xFFFFFFFFFFFFFFFF", "#P//////////", "-1676071986", "-0x63E6D432",
        "-#Bj5tQy", "%0", "@A", "%3FF8000000000000", "@D/4AAAAAAAA", "%42DBF78AD3AC0000", "@ELb94rTrAAA",
        "9.123456789012346128e+45", "%497991C25C9E4309", "@El5kcJcnkMJ",
        // specials
        "null", "nul", "nall", "na", "in", "infinity", "INF", "NaN", "-nan", "-inf", " nan", "+inf",
        "nan(123)", "nan()", "nan(0x1f)", "nan(012)", "nan(abc)", "nan(1", "-nan(7)", "nan(99999999999999999999)",
        "Infinity", "infinit", "iNfInItY", "+", ".", "-.", "+.", ".e5", "e5", "E", "1e", "1E+", "1e-x",
        "0x1p3", "0X1P3", "0x1.8p1", "0x.8", "0x.", "0x.p1", "0x1p", "0x1p+", "0x1p-1074", "0x1p-1075",
        "0x1.8p-1075", "0x1p1023", "0x1p1024", "0x1.fffffffffffffp1023", "0x1.fffffffffffff8p1023",
        "0x0.0000000000001p-1022", "0x00000000000000000000000000001p0", "0x123456789abcdef0123456789p-40",
        "0xg", "0x-1", "0x 1", "00x1", "-0x1.8p1", "0x1P+2147483648", "0x1p-2147483648",
        "1e308", "1e309", "-1e309", "1e-307", "1e-320", "1e-324", "4.9e-324", "2.4703282292062327e-324",
        "2.4703282292062328e-324", "1.7976931348623157e308", "1.7976931348623158e308", "1.7976931348623159e308",
        "0e999999999999999999999", "1e-999999999999999999999", "1e999999999999999999999", "0.0000000001e10",
        "123456789012345678901234567890", "0.123456789012345678901234567890", "1.5e", "1.5e+2e3",
        " \t\n\v\f\r42", "\x01" "5", "12 34", "1 .5", "1. 5", "1.5e 2", "1.5e+ 2", "- 5", "+ 5", "--5",
        "\xc3\xa9" "5", "5\xff", "1_000", "1,5", "1'5", "0.5e-1", "5e-1", "05", "0005.5000",
        "18446744073709551615.5", "4294967295", "4294967296", "4294967297", "-4294967296", "2147483648",
        "-2147483648", "-2147483649", "FFFFFFFF", "ffffffffffffffff", "10000000000000000", "abcdefABCDEF",
        "/+", "AAAAAAAAAAAA", "////////////", "+/+/", "@", "%", "@@", "%%", "-@A", "-%0", "-#A", "@ A",
        "% 1", "# 1", "0x 1F", "-0x10", "-#B", "-0x", "0x0x1", "#0x1", "%zz", "@!!",
    };
    for(size_t i = 0; i < COUNT(curated); i++)
        parse_line(f, curated[i]);

    // long digit strings: overflow of the chunked accumulation, NaN from inf/inf
    char tmp[1024];
    const size_t lengths[] = { 18, 19, 20, 21, 38, 39, 40, 100, 308, 309, 310, 400, 700 };
    for(size_t l = 0; l < COUNT(lengths); l++) {
        for(int variant = 0; variant < 6; variant++) {
            size_t n = lengths[l];
            size_t p = 0;
            if(variant == 1) tmp[p++] = '-';
            if(variant >= 2 && variant <= 4) { tmp[p++] = '0'; tmp[p++] = '.'; }
            for(size_t i = 0; i < n; i++)
                tmp[p++] = (char)(variant == 3 ? '9' : (variant == 4 ? '0' + (i % 10) : '1' + (i % 9)));
            if(variant == 5) { tmp[p++] = 'e'; tmp[p++] = '-'; tmp[p++] = '3'; tmp[p++] = '0'; tmp[p++] = '0'; }
            tmp[p] = '\0';
            parse_line(f, tmp);
        }
    }

    // round trips of printed numbers
    for(int i = 0; i < 2500; i++) {
        double v = rnd_double();
        buffer_flush(wb);
        buffer_print_netdata_double_encoded(wb, (NUMBER_ENCODING)rnd_below(3), v);
        parse_line(f, buffer_tostring(wb));

        uint64_t u = rnd() >> rnd_below(64);
        buffer_flush(wb);
        if(rnd_below(2))
            buffer_print_uint64_encoded(wb, (NUMBER_ENCODING)rnd_below(3), u);
        else
            buffer_print_int64_encoded(wb, (NUMBER_ENCODING)rnd_below(3), (int64_t)u);
        parse_line(f, buffer_tostring(wb));

        snprintf(tmp, sizeof(tmp), "%.17g", v);
        parse_line(f, tmp);
        snprintf(tmp, sizeof(tmp), "%a", v);
        parse_line(f, tmp);
    }

    // hexadecimal floats: long mantissas (sticky digits) and exponents across the subnormal range
    for(int i = 0; i < 2500; i++) {
        static const char hexd[] = "0123456789abcdefABCDEF";
        size_t p = 0;
        if(rnd_below(4) == 0) tmp[p++] = '-';
        tmp[p++] = '0';
        tmp[p++] = rnd_below(2) ? 'x' : 'X';
        size_t n1 = rnd_below(24), n2 = rnd_below(24);
        for(size_t k = 0; k < n1; k++) tmp[p++] = rnd_below(3) ? hexd[rnd_below(22)] : '0';
        if(rnd_below(3)) tmp[p++] = '.';
        for(size_t k = 0; k < n2; k++) tmp[p++] = rnd_below(3) ? hexd[rnd_below(22)] : '0';
        if(rnd_below(5)) {
            tmp[p++] = rnd_below(2) ? 'p' : 'P';
            p += (size_t)snprintf(&tmp[p], 16, "%s%d", rnd_below(2) ? "-" : (rnd_below(2) ? "+" : ""),
                                  (int)rnd_below(1200));
        }
        tmp[p] = '\0';
        parse_line(f, tmp);
    }

    // random token soup
    static const char *tokens[] = {
        "0", "1", "2", "5", "7", "9", "00", "123", "999999999", "18446744073709551615", ".", ".", "e", "E",
        "e+", "e-", "-", "+", " ", "\t", "\n", "x", "X", "0x", "0X", "p", "P", "p-", "#", "@", "%", "a", "b",
        "f", "F", "A", "Z", "/", "nan", "inf", "null", "infinity", "(", ")", "_", "\xc3", "\xa9", "\xff", "g",
    };
    for(int i = 0; i < 5000; i++) {
        rnd_tokens(tmp, 200, tokens, COUNT(tokens), 8);
        parse_line(f, tmp);
    }

    fclose(f);
}

// ------------------------------------------------------------------------------------------------
// 3. durations, sizes and entries

static const char *duration_units[] = {
    "ns", "nanosecond", "nanoseconds", "us", "microsecond", "microseconds", "ms", "millisecond",
    "milliseconds", "s", "sec", "secs", "second", "seconds", "m", "min", "minute", "minutes", "h",
    "hr", "hrs", "hour", "hours", "d", "day", "days", "w", "wk", "week", "weeks", "mo", "M", "month",
    "months", "q", "quarter", "quarters", "y", "Y", "a", "year", "years",
    "NS", "Us", "MS", "S", "SEC", "Seconds", "MIN", "H", "HOURS", "D", "Days", "W", "WK", "MO", "Mo", "mO",
    "MONTHS", "Q", "A", "YEARS", "", "x", "sx", "mins", "hourss", "yr", "millis",
};

static void gen_durations(const char *dir) {
    FILE *fp = out_open(dir, "duration_parse.tsv", "input | default unit | output unit | ok | value");
    FILE *fs = out_open(dir, "duration_seconds.tsv", "input | ok | value (duration_parse_seconds)");
    FILE *ff = out_open(dir, "duration_format.tsv", "value | unit | add spaces | return | text");
    FILE *fr = out_open(dir, "duration_round.tsv", "value | resolution | duration_round_to_resolution");

    static const char *unit_pairs[][2] = {
        { "s", "s" }, { "ms", "ms" }, { "ns", "ns" }, { "us", "us" }, { "", "" }, { "d", "s" }, { "s", "h" },
        { "h", "ms" }, { "us", "d" }, { "y", "ns" }, { "M", "s" }, { "xx", "s" }, { "s", "xx" }, { "mo", "q" },
        { "m", "m" }, { "h", "h" }, { "d", "d" }, { "S", "MS" }, { "weeks", "days" }, { "a", "mo" },
    };

    static const char *curated[] = {
        "5m", "2h", "7d", "1w", "30s", "7 days", "2 hours", "30 seconds", "5 minutes", "1 week", "2 months",
        "1 year", "7 DAYS", "2 Hours", "30 SECONDS", "5 Minutes", "7days", "2hours", "30seconds", "5minutes",
        "1 day", "1 hour", "1 second", "1 minute", "1 month", "2 hours 30 minutes", "1 day 12 hours",
        "1 week 2 days", "1 year 2 months 3 days", "2h 30 minutes", "1d 12 hours", "1 week 2d",
        "100 milliseconds", "50 microseconds", "25 nanoseconds", "100 MILLISECONDS", "50 Microseconds",
        "1.5 days", "2.5 hours", "0.5 minutes", "30 sec", "30 secs", "2 hr", "2 hrs", "never", "NEVER",
        "Never", "off", "OFF", "Off", "-5 minutes", "-2 hours", "-1 day", "7 days ago", "7d ago",
        "2 hours ago", "2h ago", "30 minutes ago", "30m ago", "1 year ago", "1y ago", "2 hours 30 minutes ago",
        "2h30m ago", "1 day 12 hours ago", "1d12h ago", "7 days AGO", "7 days Ago", "7daysago", "-7 days ago",
        "-2h ago", "invalid", "5 invalidunit", "abc days", "", "7 days ago extra", "7 days agooo", "ago",
        "7 ago days", "7 days ago 1 hour", "7d ago 1h", "-7d+1h", "1d-12h", "2h-3h", "3661s", "90000s",
        "31536000s", "366d", "100000000ns", "3600000ms", "0.001s", "1440m", "10080m", "0s", "0d", "60",
        "3600", "86400", "7", "24", "1000", "1000000", "1000000000", "-60", "-3600", "-86400", "-7", "-24",
        "1.5", "2.5", "0.5", "-1.5", "0", "-0", "+60", " 60 ", "1705318200", "1609459200", "946684800",
        "2147483647", "4102444800", "1705318200s", "1705318200 seconds", "2147483647s", "-2147483648s",
        "2147483648s", "-2147483649s", "nan", "inf", "-inf", "1e400ns", "1e300y", "9223372036854775808ns",
        "-9223372036854775808ns", "0ns-9223372036854775808ns", "0ns-9223372036854775808ns1ns",
        "0ns-9223372036854775808ns-1ns", "9223372036854774784ns1024ns", "0ns-9223372036854774784ns-1024ns",
        "9223372036854774784ns", "-9223372036854774784ns", "9223372036854774784ns ago",
        "9223372036854774784ns-1024ns", "1.5s", "5 ago", "5s ago ago", "agoago", "5 microsecondsago",
        "5 xxxxxxxxxxxxxxxxago", "5 millisecondsxago", "5 secondsagoago", "5 aGo", "5sAGO", "1null", "null",
        "nul", "5 .", "5m .", "5m -", "5m +", "--5m", "- 5m", "5m  ", "\t5m\n", "5\x0bm", "never ", " never",
        "neverx", "offx", "5m never", "5m off", "5 M", "5 MO", "1mo", "1Y", "1A", "1Q", "1e3s", "1e-3s",
        "1E3ms", ".5h", "5.h", "1,5h", "0x10s", "5m5", "5 5", "5m 5", "1h 1", "10 µs", "5\xc3\xa9",
        "5 microseconds", "5 microsecondsx", "5 milliseconds ago", "123456789012345678901234567890ns",
        "-0.4s", "0.4s", "0.5ns", "1.5ns", "2.5ns", "-2.5ns", "0.49999999999999994s", "292y", "293y",
        "-292y5mo21d23h47m16s854ms775us808ns", "9223372036854775807ns",
    };

    char tmp[512];
    for(size_t i = 0; i < COUNT(curated); i++) {
        for(size_t p = 0; p < COUNT(unit_pairs); p++) {
            int64_t v = 0x123456789;
            bool ok = duration_parse(curated[i], &v, unit_pairs[p][0], unit_pairs[p][1]);
            esc_str(fp, curated[i]); tab(fp); esc_str(fp, unit_pairs[p][0]); tab(fp); esc_str(fp, unit_pairs[p][1]);
            fprintf(fp, "\t%d\t%" PRId64 "\n", ok, v);
        }
        int si = 12345;
        bool ok = duration_parse_seconds(curated[i], &si);
        esc_str(fs, curated[i]);
        fprintf(fs, "\t%d\t%d\n", ok, si);
    }

    static const char *numbers[] = {
        "0", "1", "5", "-5", "+5", "1.5", "0.5", ".5", "5.", "1e3", "1E-3", "-0", "  7", "12",
        "9223372036854775807", "9223372036854775808", "1e19", "1e300", "nan", "inf", "null", "1e", "1e+",
        "0x10", "007", "2.4999999", "0.0000001", "1000000000", "-1.5", "3.14159265358979",
    };
    static const char *gaps[] = { "", " ", "\t", "  " };
    static const char *suffixes[] = { "", " ago", "ago", " AGO", " ago ", " agoo", " ago x", " x", " 5" };
    static const char *joiners[] = { "", " ", "  ", "+", "-", ",", "\t" };

    // one term with every unit spelling
    for(size_t n = 0; n < COUNT(numbers); n++) {
        for(size_t u = 0; u < COUNT(duration_units); u++) {
            snprintf(tmp, sizeof(tmp), "%s%s%s%s", numbers[n], PICK(gaps), duration_units[u], PICK(suffixes));
            for(int k = 0; k < 2; k++) {
                const char **pair = unit_pairs[k == 0 ? 0 : rnd_below(COUNT(unit_pairs))];
                int64_t v = 0x123456789;
                bool ok = duration_parse(tmp, &v, pair[0], pair[1]);
                esc_str(fp, tmp); tab(fp); esc_str(fp, pair[0]); tab(fp); esc_str(fp, pair[1]);
                fprintf(fp, "\t%d\t%" PRId64 "\n", ok, v);
            }
        }
    }

    // random multi-term expressions
    for(int i = 0; i < 12000; i++) {
        tmp[0] = '\0';
        if(rnd_below(4) == 0) strcat(tmp, rnd_below(2) ? "-" : " ");
        size_t terms = 1 + rnd_below(4);
        for(size_t t = 0; t < terms; t++) {
            if(t) strcat(tmp, PICK(joiners));
            strcat(tmp, PICK(numbers));
            strcat(tmp, PICK(gaps));
            strcat(tmp, PICK(duration_units));
        }
        strcat(tmp, PICK(suffixes));

        const char **pair = unit_pairs[rnd_below(COUNT(unit_pairs))];
        int64_t v = 0x123456789;
        bool ok = duration_parse(tmp, &v, pair[0], pair[1]);
        esc_str(fp, tmp); tab(fp); esc_str(fp, pair[0]); tab(fp); esc_str(fp, pair[1]);
        fprintf(fp, "\t%d\t%" PRId64 "\n", ok, v);

        if(i % 4 == 0) {
            int si = 12345;
            ok = duration_parse_seconds(tmp, &si);
            esc_str(fs, tmp);
            fprintf(fs, "\t%d\t%d\n", ok, si);
        }
    }

    // rendering
    int64_t values[600];
    size_t nv = 0;
    const int64_t fixed[] = {
        0, 1, -1, 2, -2, 59, 60, 61, 300, -300, 3599, 3600, 3661, 7200, 9000, 86399, 86400, 86401, 90000,
        129600, 604800, 2592000, 31536000, 31622400, 2372, INT64_MAX, INT64_MIN, INT64_MIN + 1, INT64_MAX - 1,
        1000, 999, 1001, 499, 500, 501, 1500, 2500, -500, -1500, 1705318200, 4102444800LL,
    };
    for(size_t i = 0; i < COUNT(fixed); i++) values[nv++] = fixed[i];
    const int64_t multipliers[] = {
        1, 1000, 1000000, 1000000000LL, 60000000000LL, 3600000000000LL, 86400000000000LL, 604800000000000LL,
        2592000000000000LL, 7776000000000000LL, 31536000000000000LL,
    };
    for(size_t m = 0; m < COUNT(multipliers) && nv + 8 < COUNT(values); m++) {
        for(int k = 1; k <= 3; k++) {
            values[nv++] = multipliers[m] * k;
            values[nv++] = multipliers[m] * k + 1;
            values[nv++] = multipliers[m] * k - 1;
            values[nv++] = -(multipliers[m] * k);
        }
    }
    while(nv < COUNT(values)) {
        int64_t v = (int64_t)(rnd() >> rnd_below(64));
        values[nv++] = rnd_below(3) == 0 ? -v : v;
    }

    for(size_t i = 0; i < nv; i++) {
        for(size_t u = 0; u < COUNT(duration_units); u++) {
            for(int spaces = 0; spaces < 2; spaces++) {
                if(i > 100 && (rnd_below(4) != 0))
                    continue;
                char buf[256];
                buf[0] = '\0';
                ssize_t ret = duration_snprintf(buf, sizeof(buf), values[i], duration_units[u], spaces);
                fprintf(ff, "%" PRId64 "\t", values[i]);
                esc_str(ff, duration_units[u]);
                fprintf(ff, "\t%d\t%zd\t", spaces, ret);
                if(ret >= 0) esc_str(ff, buf);
                eol(ff);
            }
        }
    }

    // rounding helper (avoiding the signed overflow C leaves undefined)
    const int64_t resolutions[] = { 1, 2, 3, 10, 1000, 1000000, 1000000000LL, 60000000000LL };
    for(size_t r = 0; r < COUNT(resolutions); r++) {
        for(int i = 0; i < 200; i++) {
            int64_t v = (int64_t)(rnd() >> (1 + rnd_below(63)));
            if(i < 20) v = i - 10;
            if(rnd_below(2)) v = -v;
            fprintf(fr, "%" PRId64 "\t%" PRId64 "\t%" PRId64 "\n", v, resolutions[r],
                    duration_round_to_resolution(v, resolutions[r]));
        }
    }

    fclose(fp);
    fclose(fs);
    fclose(ff);
    fclose(fr);
}

typedef bool (*scaled_parse_fn)(const char *, uint64_t *, const char *);
typedef ssize_t (*scaled_format_fn)(char *, size_t, uint64_t, const char *, bool);

static void gen_scaled(const char *dir, const char *prefix, scaled_parse_fn parse, scaled_format_fn format,
                       const char *const *units, size_t units_count, const char *const *defaults, size_t defaults_count) {
    char name[64];
    snprintf(name, sizeof(name), "%s_parse.tsv", prefix);
    FILE *fp = out_open(dir, name, "input | default unit | ok | value");
    snprintf(name, sizeof(name), "%s_format.tsv", prefix);
    FILE *ff = out_open(dir, name, "value | unit | accurate | return | text");

    static const char *numbers[] = {
        "0", "1", "1.5", "0.001", "-0", "-1", "1e3", "1E3", "0x10", "0x1p3", "0X1P-2", "inf", "INFINITY",
        "nan", "nan(1)", ".5", "5.", "1e", "1e+", "  3", "18446744073709551615", "18446744073709551616",
        "18446744073709549568", "1e19", "1e20", "17592186044416", "1536", "1535", "007", "1,5", "2.5",
        "0.5", "0.4999999", "1023.5", "4294967296", "16777217", "9007199254740993", "-0.4", "1e-400",
        "0x", "+7", "- 7", "off", "OFF", "o",
    };
    static const char *gaps[] = { "", " ", "\t" };
    static const char *trailers[] = { "", " x", "5", "s", " off", "\n" };

    char tmp[256];
    for(size_t n = 0; n < COUNT(numbers); n++) {
        for(size_t u = 0; u < units_count; u++) {
            snprintf(tmp, sizeof(tmp), "%s%s%s%s", numbers[n], PICK(gaps), units[u], PICK(trailers));
            for(size_t d = 0; d < defaults_count; d++) {
                if(d > 1 && rnd_below(3) != 0)
                    continue;
                uint64_t v = 0x123456789;
                bool ok = parse(tmp, &v, defaults[d]);
                esc_str(fp, tmp); tab(fp); esc_str(fp, defaults[d]);
                fprintf(fp, "\t%d\t%" PRIu64 "\n", ok, v);
            }
        }
    }
    static const char *extra[] = { "off", " off", "off ", "OFF", "", " ", "x", "B", "KiB", "18446744073709551615B" };
    for(size_t i = 0; i < COUNT(extra); i++) {
        for(size_t d = 0; d < defaults_count; d++) {
            uint64_t v = 0x123456789;
            bool ok = parse(extra[i], &v, defaults[d]);
            esc_str(fp, extra[i]); tab(fp); esc_str(fp, defaults[d]);
            fprintf(fp, "\t%d\t%" PRIu64 "\n", ok, v);
        }
    }

    uint64_t values[700];
    size_t nv = 0;
    values[nv++] = 0;
    values[nv++] = UINT64_MAX;
    values[nv++] = UINT64_MAX - 1;
    values[nv++] = 1ULL << 63;
    for(uint64_t p = 1; nv < 100; p *= 10) {
        values[nv++] = p;
        values[nv++] = p + 1;
        values[nv++] = p * 3 / 2;
        if(p > UINT64_MAX / 10) break;
    }
    for(int b = 0; b < 64 && nv + 4 < COUNT(values); b++) {
        values[nv++] = 1ULL << b;
        values[nv++] = (1ULL << b) + (1ULL << (b / 2));
        values[nv++] = (1ULL << b) * 3 / 2;
        values[nv++] = (1ULL << b) - 1;
    }
    while(nv < COUNT(values))
        values[nv++] = rnd() >> rnd_below(64);

    for(size_t i = 0; i < nv; i++) {
        for(size_t u = 0; u < units_count; u++) {
            for(int accurate = 0; accurate < 2; accurate++) {
                if(i > 80 && rnd_below(3) != 0)
                    continue;
                char buf[128];
                buf[0] = '\0';
                ssize_t ret = format(buf, sizeof(buf), values[i], units[u], accurate);
                fprintf(ff, "%" PRIu64 "\t", values[i]);
                esc_str(ff, units[u]);
                fprintf(ff, "\t%d\t%zd\t", accurate, ret);
                if(ret >= 0) esc_str(ff, buf);
                eol(ff);
            }
        }
    }

    fclose(fp);
    fclose(ff);
}

static void gen_sizes(const char *dir) {
    static const char *size_units[] = {
        "", "B", "k", "K", "KB", "KiB", "M", "MB", "MiB", "G", "GB", "GiB", "T", "TB", "TiB", "P", "PB",
        "PiB", "kb", "kib", "b", "E", "EB", "EiB", "KiBs", "MiBytes", "Bytes", "byte", "x", "Ki", "mib",
    };
    static const char *size_defaults[] = { "B", "KiB", "MiB", "GiB", "K", "M", "", "x", "b", "PiB", "k" };
    gen_scaled(dir, "size", size_parse, size_snprintf, size_units, COUNT(size_units), size_defaults, COUNT(size_defaults));

    static const char *entries_units[] = {
        "", "k", "K", "M", "G", "T", "P", "E", "Z", "Y", "m", "g", "KB", "Kx", "x", "B", "KiB", "EE",
    };
    static const char *entries_defaults[] = { "", "K", "M", "G", "k", "E", "Z", "Y", "x" };
    gen_scaled(dir, "entries", entries_parse, entries_snprintf, entries_units, COUNT(entries_units),
               entries_defaults, COUNT(entries_defaults));
}

// ------------------------------------------------------------------------------------------------
// 4. simple patterns

typedef struct {
    const char *code;          // W, N or B:<bytes>
    const char *separators;    // what simple_pattern_create() receives
} sp_separators;

static const sp_separators sp_seps[] = {
    { "W", NULL },
    { "N", SIMPLE_PATTERN_NO_SEPARATORS },
    { "B:", "" },
    { "B:,|\t\r\n\f\v", SIMPLE_PATTERN_DEFAULT_WEB_SEPARATORS },
    { "B:|", "|" },
    { "B:,", "," },
    { "B:a", "a" },
};

static const char sp_mode_code[] = { 'E', 'P', 'S', 'U' };

static void sp_head(FILE *f, const char *pattern, const sp_separators *seps, SIMPLE_PREFIX_MODE mode, bool cs) {
    esc_str(f, pattern); tab(f);
    esc_str(f, seps->code); tab(f);
    fprintf(f, "%c\t%d", sp_mode_code[mode], cs);
}

static void sp_case(FILE *fm, FILE *fi, const char *pattern, const sp_separators *seps, SIMPLE_PREFIX_MODE mode,
                    bool cs, const char *const *strings, size_t count) {
    SIMPLE_PATTERN *p = simple_pattern_create(pattern, seps->separators, mode, cs);

    sp_head(fi, pattern, seps, mode, cs);
    fprintf(fi, "\t%d\t%d\t", simple_pattern_contains_wildcards(pattern, seps->separators),
            p ? simple_pattern_is_potential_name(p) : 0);
    {
        SIMPLE_PATTERN *it = p;
        bool first = true;
        while(it) {
            char *m = simple_pattern_iterate(&it);
            if(!first) fputs("\\x1f", fi);
            first = false;
            if(m) { fputc('+', fi); esc_str(fi, m); }
            else fputc('-', fi);
        }
    }
    eol(fi);

    for(size_t i = 0; i < count; i++) {
        const char *s = strings[i];
        const size_t sizes[] = { 0, 1, 2, 4, 1024 };
        size_t wsize = sizes[rnd_below(COUNT(sizes))];
        char wildcarded[1024];
        wildcarded[0] = '\0';
        SIMPLE_PATTERN_RESULT r = simple_pattern_matches_extract(p, s, wsize ? wildcarded : NULL, wsize);

        sp_head(fm, pattern, seps, mode, cs);
        tab(fm); esc_str(fm, s);
        fprintf(fm, "\t%zu\t%d\t", wsize, (int)r);
        esc_str(fm, wildcarded);
        eol(fm);
    }

    simple_pattern_free(p);
}

static void gen_simple_patterns(const char *dir) {
    FILE *fm = out_open(dir, "simple_pattern.tsv",
                        "pattern | separators | default mode | case sensitive | string | wildcarded size | result | wildcarded");
    FILE *fi = out_open(dir, "simple_pattern_info.tsv",
                        "pattern | separators | default mode | case sensitive | contains_wildcards | is_potential_name | words");

    static const char *curated_patterns[] = {
        "!veth0 veth*", "!/path/*/*.ext /path/*.ext", "*", "**", "***", "a*", "*a", "*a*", "a*b", "a*b*c",
        "a**b", "a**", "**a", "*a**b*", "!*", "!", "! a", "!!a", "\\!a", "a\\ b", "a\\*b", "\\", "a\\",
        "localhost", "localhost *", "10.* 192.168.*", "!10.0.0.1 *", "::1", "fe80::*", "*.example.com",
        "*:*", "a:b", "*localhost*", "a* !b* *", "!a* a*", "abc|def", "abc,def", "", " ", "  a  b  ",
        "a\tb\nc\rd\fe\vf", "ABC* *DEF", "*Ab*cD*", "\xc3\xa9*", "*\xc3\xa9", "cpu.* !cpu.cpu* *",
        "disk_*.sd* !*.loop*", "*user*|*system*", "apps.plugin*", "!*/proc/* /*", "x*y*z*w", "*x*x*x*",
        "a*a", "aa*aa", "*aa", "aa*", "a*b*a*b", "?", "[a]", "a.b", "*.*", "!*.* *",
    };
    static const char *curated_strings[] = {
        "veth0", "veth12", "veth", "eth0", "/path/test.ext", "/path/a/test.ext", "/path/a/b/test.ext",
        "a", "b", "ab", "ba", "abc", "aXb", "aXbYc", "aXcYb", "abcab", "a*b", "a b", "!a", "a\\b", "*",
        "localhost", "10.0.0.1", "192.168.1.1", "::1", "fe80::1", "www.example.com", "example.com", "A",
        "AB", "ABC", "aBc", "Abc", "xxABCyyDEF", "abcdef", "abc|def", "abc,def", "cpu.user", "cpu.cpu0",
        "disk_util.sda", "disk_util.loop0", "apps.plugin.x", "/proc/1", "/usr", "xyzw", "xxyyzzww", "aa",
        "aaa", "aaaa", "ab", "abab", "\xc3\xa9t\xc3\xa9", "\xc3\x89T\xc3\x89", "", " ", "a.b", "axb", "[a]",
        "?", "x", "xx", "xxx", "xxxx",
    };

    // every curated pattern under every mode, against a sample of the curated strings
    const char *sample[20];
    for(size_t p = 0; p < COUNT(curated_patterns); p++)
        for(size_t s = 0; s < 3; s++)
            for(int mode = 0; mode < 4; mode++)
                for(int cs = 0; cs < 2; cs++) {
                    for(size_t k = 0; k < COUNT(sample); k++)
                        sample[k] = curated_strings[rnd_below(COUNT(curated_strings))];
                    sp_case(fm, fi, curated_patterns[p], &sp_seps[s == 2 ? 2 + rnd_below(COUNT(sp_seps) - 2) : s],
                            (SIMPLE_PREFIX_MODE)mode, cs, sample, COUNT(sample));
                }

    // random patterns and strings over a small alphabet
    static const char *pattern_tokens[] = { "a", "b", "A", "B", "*", "*", "!", " ", ",", "|", "\\", "ab", "\xc3\xa9" };
    static const char *string_tokens[] = { "a", "b", "A", "B", "*", "!", " ", ",", "ab", "ba", "\xc3\xa9", "\xc3\x89" };
    char pattern[64];
    char strings_buf[16][64];
    const char *strings[16];
    for(int i = 0; i < 1500; i++) {
        rnd_tokens(pattern, sizeof(pattern), pattern_tokens, COUNT(pattern_tokens), 10);
        for(int s = 0; s < 16; s++) {
            rnd_tokens(strings_buf[s], sizeof(strings_buf[s]), string_tokens, COUNT(string_tokens), 8);
            strings[s] = strings_buf[s];
        }
        sp_case(fm, fi, pattern, &sp_seps[rnd_below(COUNT(sp_seps))], (SIMPLE_PREFIX_MODE)rnd_below(4),
                rnd_below(2), strings, 16);
    }

    // the nesting limit of parse_pattern()
    {
        static char deep[4096], hay[4096];
        size_t n = 0;
        for(int i = 0; i < 1100 && n + 3 < sizeof(deep); i++) { deep[n++] = 'a'; deep[n++] = '*'; }
        deep[n++] = 'z';
        deep[n] = '\0';
        for(size_t i = 0; i < 1500; i++) hay[i] = 'a';
        hay[1500] = '\0';
        const char *hs[] = { hay, "az", "a" };
        sp_case(fm, fi, deep, &sp_seps[0], SIMPLE_PATTERN_EXACT, true, hs, COUNT(hs));
    }

    fclose(fm);
    fclose(fi);
}

// ------------------------------------------------------------------------------------------------
// 5. sanitizers

static unsigned char identity_map[256];

static void san_line(FILE *f, const char *func, const unsigned char *input, const char *size, const char *output,
                     size_t ret, const char *extra) {
    esc_str(f, func); tab(f);
    esc(f, input, strlen((const char *)input)); tab(f);
    esc_str(f, size); tab(f);
    esc_str(f, output);
    fprintf(f, "\t%zu\t%s\n", ret, extra);
}

static void san_all(FILE *f, const unsigned char *input, size_t dst_size) {
    // a destination with slack: text_sanitize() writes one byte past dst_size
    // when the "empty" replacement does not fit (see the report)
    static unsigned char dst[8192];
    char size[32], extra[32];
    snprintf(size, sizeof(size), "%zu", dst_size);

    struct { const char *name; const unsigned char *map; } maps[] = {
        { "identity", identity_map },
        { "rrd", rrd_string_allowed_chars },
        { "chart", chart_names_allowed_chars },
    };
    const char *empties[] = { "", "[none]", "-" };
    for(size_t m = 0; m < COUNT(maps); m++) {
        for(int utf = 0; utf < 2; utf++) {
            size_t e = rnd_below(COUNT(empties));
            char func[64];
            snprintf(func, sizeof(func), "text_sanitize:%s:%d:%zu", maps[m].name, utf, e);
            memset(dst, 0xcc, dst_size + 16);
            size_t mblen = 0;
            size_t ret = text_sanitize(dst, input, dst_size, maps[m].map, utf, empties[e], &mblen);
            snprintf(extra, sizeof(extra), "%zu", mblen);
            san_line(f, func, input, size, dst_size ? (const char *)dst : "", ret, extra);
        }
    }

    memset(dst, 0xcc, dst_size + 16);
    size_t ret = rrdlabels_sanitize_name((char *)dst, (const char *)input, dst_size);
    san_line(f, "rrdlabels_sanitize_name", input, size, dst_size ? (const char *)dst : "", ret, "-");

    memset(dst, 0xcc, dst_size + 16);
    ret = rrdlabels_sanitize_value((char *)dst, (const char *)input, dst_size);
    san_line(f, "rrdlabels_sanitize_value", input, size, dst_size ? (const char *)dst : "", ret, "-");

    memset(dst, 0xcc, dst_size + 16);
    ret = prometheus_rrdlabels_sanitize_name((char *)dst, (const char *)input, dst_size);
    san_line(f, "prometheus_rrdlabels_sanitize_name", input, size, dst_size ? (const char *)dst : "", ret, "-");

    memset(dst, 0xcc, dst_size + 16);
    ret = nrpc_sanitize_name((char *)dst, (const char *)input, dst_size);
    san_line(f, "nrpc_sanitize_name", input, size, dst_size ? (const char *)dst : "", ret, "-");

    if(dst_size) {
        memset(dst, 0xcc, dst_size + 16);
        rrdset_strncpyz_name((char *)dst, (const char *)input, dst_size - 1);
        san_line(f, "rrdset_strncpyz_name", input, size, (const char *)dst, strlen((char *)dst), "-");
    }
}

static void san_in_place(FILE *f, const unsigned char *input) {
    static char buf[8192];
    size_t len = strlen((const char *)input);

    memcpy(buf, input, len + 1);
    netdata_fix_chart_name(buf);
    san_line(f, "netdata_fix_chart_name", input, "-", buf, strlen(buf), "-");

    memcpy(buf, input, len + 1);
    netdata_fix_chart_id(buf);
    san_line(f, "netdata_fix_chart_id", input, "-", buf, strlen(buf), "-");

    memcpy(buf, input, len + 1);
    bool changed = rrdvar_fix_name(buf);
    san_line(f, "rrdvar_fix_name", input, "-", buf, strlen(buf), changed ? "1" : "0");

    // rrd_string_strdupz() (database/rrd.c) sanitization step
    if(len) {
        static unsigned char dst[16384];
        size_t ret = text_sanitize(dst, input, len * 2 + 1, rrd_string_allowed_chars, true, "", NULL);
        san_line(f, "rrd_string_sanitize", input, "-", (const char *)dst, ret, "-");
    }
    else
        san_line(f, "rrd_string_sanitize", input, "-", "", 0, "-");
}

static void gen_sanitizers(const char *dir) {
    for(int i = 0; i < 256; i++) identity_map[i] = (unsigned char)i;

    FILE *f = out_open(dir, "sanitize.tsv", "function | input | dst size | output | return | mblen or changed");
    FILE *fmaps = out_open(dir, "char_maps.tsv", "map | 256 bytes (or 256 0/1 flags)");

    esc_str(fmaps, "rrd_string_allowed_chars"); tab(fmaps); esc(fmaps, rrd_string_allowed_chars, 256); eol(fmaps);
    esc_str(fmaps, "chart_names_allowed_chars"); tab(fmaps); esc(fmaps, chart_names_allowed_chars, 256); eol(fmaps);
    esc_str(fmaps, "is_netdata_api_valid_character"); tab(fmaps);
    for(int c = 0; c < 256; c++) fputc(is_netdata_api_valid_character((char)c) ? '1' : '0', fmaps);
    eol(fmaps);
    fclose(fmaps);

    unsigned char input[4096];

    // every byte alone and between letters
    for(int c = 1; c < 256; c++) {
        input[0] = (unsigned char)c; input[1] = '\0';
        san_all(f, input, 32);
        san_in_place(f, input);
        input[0] = 'a'; input[1] = (unsigned char)c; input[2] = 'b'; input[3] = '\0';
        san_all(f, input, 32);
        san_in_place(f, input);
    }

    // UTF-8 structures under every destination size
    static const char *utf8[] = {
        "caf\xc3\xa9", "\xc2\xb0" "C", "\xe2\x82\xac", "\xf0\x9f\x98\x80", "\xc2", "\xe2\x82", "\xf0\x9f\x98",
        "\x80\x81lone", "\xc0\x80", "\xf8\x88\x80\x80\x80", "\xfe\xff", "a\xc2\xb0\xe2\x82\xac\xf0\x9f\x98\x80z",
        "\xc3\xa9\xa9", "\xe2\x82\xac\x80\x80", "\xc2\xc2\xb0", "\xed\xa0\x80", "\xf4\x90\x80\x80",
        "  lead", "trail  ", "  both  ", "in   side", "___", "_a_", "_", " _ ", "!name", "! name", "!!",
        "a!b", "*", "a b\tc\nd", "\x01\x02\x03", "\x7f", "\"quoted\"", "back\\slash", "k=v;x:y", "a,b",
        "UPPER lower", "[none]", "none", "", "cpu.user", "disk_util.sda1", "apps.plugin",
    };
    const size_t sizes[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 16, 64 };
    for(size_t i = 0; i < COUNT(utf8); i++) {
        for(size_t s = 0; s < COUNT(sizes); s++)
            san_all(f, (const unsigned char *)utf8[i], sizes[s]);
        san_in_place(f, (const unsigned char *)utf8[i]);
    }

    // random byte strings
    for(int i = 0; i < 1500; i++) {
        size_t len = rnd_below(24);
        for(size_t k = 0; k < len; k++) {
            unsigned char c;
            switch(rnd_below(5)) {
                case 0: c = (unsigned char)(0x80 + rnd_below(0x80)); break;
                case 1: c = (unsigned char)(1 + rnd_below(0x20)); break;
                case 2: c = " _!*\"'\\=:;,@()"[rnd_below(14)]; break;
                default: c = (unsigned char)(0x20 + rnd_below(0x5f)); break;
            }
            input[k] = c;
        }
        input[len] = '\0';
        san_all(f, input, 1 + rnd_below(48));
        san_in_place(f, input);
    }

    // rrdvar_fix_name() truncates at RRDVAR_MAX_LENGTH
    {
        const size_t lengths[] = { 1023, 1024, 1025, 1100 };
        for(size_t l = 0; l < COUNT(lengths); l++) {
            for(size_t k = 0; k < lengths[l]; k++) input[k] = (unsigned char)('a' + k % 26);
            input[lengths[l]] = '\0';
            san_in_place(f, input);
            input[lengths[l] - 1] = ' ';
            san_in_place(f, input);
        }
    }

    fclose(f);
}

// ------------------------------------------------------------------------------------------------
// 6. JSON writer

static void gen_json_escape(const char *dir) {
    FILE *f = out_open(dir, "json_escape.tsv", "input | buffer_json_strcat | buffer_json_quoted_strcat");
    BUFFER *wb = buffer_create(0, NULL);

    unsigned char input[64];
    for(int i = 0; i < 4000; i++) {
        size_t len;
        if(i < 255) {
            input[0] = (unsigned char)(i + 1);
            len = 1;
        }
        else {
            len = rnd_below(12);
            for(size_t k = 0; k < len; k++)
                input[k] = rnd_below(3) ? (unsigned char)"\"\\\n\r\t\b\f\x01\x1f\x7f\xc3\xa9" "ab/'"[rnd_below(17)]
                                        : (unsigned char)(1 + rnd_below(255));
        }
        input[len] = '\0';

        esc(f, input, len); tab(f);
        buffer_flush(wb); buffer_json_strcat(wb, (const char *)input);
        esc_str(f, buffer_tostring(wb)); tab(f);
        buffer_flush(wb); buffer_json_quoted_strcat(wb, (const char *)input);
        esc_str(f, buffer_tostring(wb)); eol(f);
    }

    buffer_free(wb);
    fclose(f);
}

// Scripts: operations joined with 0x1e, arguments with 0x1f (both encoded as \x1e / \x1f);
// arguments are hex encoded so that they never contain the separators.
// The first operation is always the initialization: I <key quote> <value quote> <depth> <anonymous> <options>.

typedef struct {
    FILE *f;
    bool first;
} script;

static void op_begin(script *s, const char *code) {
    if(!s->first) fputs("\\x1e", s->f);
    s->first = false;
    esc_str(s->f, code);
}

static void op_arg(script *s, const void *data, size_t len) {
    fputs("\\x1f", s->f);
    for(size_t i = 0; i < len; i++)
        fprintf(s->f, "%02x", ((const unsigned char *)data)[i]);
}

static void op_arg_str(script *s, const char *str) {
    op_arg(s, str, strlen(str));
}

static void op_arg_u64(script *s, uint64_t v) {
    char tmp[32];
    snprintf(tmp, sizeof(tmp), "%" PRIu64, v);
    op_arg_str(s, tmp);
}

static void op_arg_i64(script *s, int64_t v) {
    char tmp[32];
    snprintf(tmp, sizeof(tmp), "%" PRId64, v);
    op_arg_str(s, tmp);
}

static const char *json_strings[] = {
    "", "a", "hello", "world", "with space", "quote\"inside", "back\\slash", "tab\there", "new\nline",
    "\r\b\f", "\x01\x02\x1f", "\x7f", "caf\xc3\xa9", "\xf0\x9f\x98\x80", "\xff\xfe", "\"quoted\"", "\"", "\"\"",
    "null", "NULL", "/slash/", "'single'", "a\"b\"", "\"lead", "trail\"", "{}", "[]", ",:", "0", "-1.5",
};

static void rnd_uuid(unsigned char *uuid) {
    if(rnd_below(4) == 0) {
        memset(uuid, 0, 16);
        return;
    }
    for(int i = 0; i < 16; i++)
        uuid[i] = (unsigned char)rnd();
}

static void json_script(FILE *f, BUFFER *wb) {
    script s = { .f = f, .first = true };

    static const char *quotes[] = { "\"", "\"", "\"", "", "'", "``", "12345678" };
    const char *kq = PICK(quotes);
    const char *vq = rnd_below(3) ? kq : PICK(quotes);
    static const BUFFER_JSON_OPTIONS options[] = {
        BUFFER_JSON_OPTIONS_DEFAULT, BUFFER_JSON_OPTIONS_MINIFY, BUFFER_JSON_OPTIONS_NEWLINE_ON_ARRAY_ITEMS,
        BUFFER_JSON_OPTIONS_MINIFY | BUFFER_JSON_OPTIONS_NEWLINE_ON_ARRAY_ITEMS,
    };
    BUFFER_JSON_OPTIONS opt = options[rnd_below(COUNT(options))];
    bool anonymous = rnd_below(5) != 0;
    int depth = rnd_below(6) == 0 ? (int)(1 + rnd_below(3)) : 0;
    bool finalize = depth == 0 && rnd_below(8) != 0;

    buffer_flush(wb);
    buffer_json_initialize(wb, kq, vq, depth, anonymous, opt);
    op_begin(&s, "I");
    op_arg_str(&s, kq);
    op_arg_str(&s, vq);
    op_arg_i64(&s, depth);
    op_arg_u64(&s, anonymous);
    op_arg_u64(&s, opt);

    // what is open above the root: 'o' object, 'a' array
    char open[BUFFER_JSON_MAX_DEPTH];
    int level = 0;
    size_t ops = rnd_below(40);
    int in_array = 0;

    for(size_t i = 0; i < ops; i++) {
        in_array = level > 0 && open[level - 1] == 'a';
        const char *key = PICK(json_strings);
        const char *value = PICK(json_strings);
        unsigned char uuid[16];
        uint64_t u = rnd() >> rnd_below(64);
        double d = rnd_below(8) == 0 ? (rnd_below(2) ? NAN : INFINITY) : rnd_double();
        int64_t t = rnd_below(3) == 0 ? 0 : (int64_t)(rnd() >> (1 + rnd_below(63)));
        if(rnd_below(5) == 0) t = -t;

        // prefer items inside arrays and members inside objects, but mix
        unsigned what = (unsigned)rnd_below(100);
        bool items = in_array ? what < 85 : what < 10;
        unsigned k = (unsigned)rnd_below(items ? 16 : 22);

        if(level > 0 && rnd_below(6) == 0) {
            if(open[level - 1] == 'o') { buffer_json_object_close(wb); op_begin(&s, "OC"); }
            else { buffer_json_array_close(wb); op_begin(&s, "AC"); }
            level--;
            continue;
        }

        if(items) {
            switch(k) {
                case 0: if(level + depth < 28) { buffer_json_add_array_item_array(wb); op_begin(&s, "IA"); open[level++] = 'a'; } break;
                case 1: if(level + depth < 28) { buffer_json_add_array_item_object(wb); op_begin(&s, "IO"); open[level++] = 'o'; } break;
                case 2: buffer_json_add_array_item_string(wb, value); op_begin(&s, "IS"); op_arg_str(&s, value); break;
                case 3: buffer_json_add_array_item_string(wb, NULL); op_begin(&s, "IN"); break;
                case 4: rnd_uuid(uuid); buffer_json_add_array_item_uuid(wb, (nd_uuid_t *)uuid); op_begin(&s, "IU"); op_arg(&s, uuid, 16); break;
                case 5: rnd_uuid(uuid); buffer_json_add_array_item_uuid_compact(wb, (nd_uuid_t *)uuid); op_begin(&s, "IUC"); op_arg(&s, uuid, 16); break;
                case 6: buffer_json_add_array_item_double(wb, d); op_begin(&s, "ID"); op_arg_u64(&s, bits_of(d)); break;
                case 7: buffer_json_add_array_item_int64(wb, (int64_t)u); op_begin(&s, "II"); op_arg_i64(&s, (int64_t)u); break;
                case 8: buffer_json_add_array_item_uint64(wb, u); op_begin(&s, "IU64"); op_arg_u64(&s, u); break;
                case 9: buffer_json_add_array_item_boolean(wb, u & 1); op_begin(&s, "IB"); op_arg_u64(&s, u & 1); break;
                case 10: buffer_json_add_array_item_time_t(wb, t); op_begin(&s, "IT"); op_arg_i64(&s, t); break;
                case 11: buffer_json_add_array_item_time_ms(wb, t); op_begin(&s, "ITM"); op_arg_i64(&s, t); break;
                case 12: buffer_json_add_array_item_time_t_formatted(wb, t, u & 1); op_begin(&s, "ITF"); op_arg_i64(&s, t); op_arg_u64(&s, u & 1); break;
                case 13: buffer_json_add_array_item_datetime_rfc3339(wb, u, true); op_begin(&s, "IDT"); op_arg_u64(&s, u); break;
                case 14: buffer_json_add_array_item_uuid(wb, NULL); op_begin(&s, "IUN"); break;
                default: buffer_fast_strcat(wb, value, strlen(value)); op_begin(&s, "R"); op_arg_str(&s, value); break;
            }
        }
        else {
            switch(k) {
                case 0: if(level + depth < 28) { buffer_json_member_add_object(wb, key); op_begin(&s, "MO"); op_arg_str(&s, key); open[level++] = 'o'; } break;
                case 1: if(level + depth < 28) { buffer_json_member_add_array(wb, key); op_begin(&s, "MA"); op_arg_str(&s, key); open[level++] = 'a'; } break;
                case 2: if(level + depth < 28) { buffer_json_member_add_array(wb, NULL); op_begin(&s, "MAN"); open[level++] = 'a'; } break;
                case 3: buffer_json_member_add_string(wb, key, value); op_begin(&s, "MS"); op_arg_str(&s, key); op_arg_str(&s, value); break;
                case 4: buffer_json_member_add_string(wb, key, NULL); op_begin(&s, "MN"); op_arg_str(&s, key); break;
                case 5: buffer_json_member_add_string_or_omit(wb, key, value); op_begin(&s, "MSO"); op_arg_str(&s, key); op_arg_str(&s, value); break;
                case 6:
                    if(rnd_below(2)) { buffer_json_member_add_string_or_empty(wb, key, value); op_begin(&s, "MSE"); op_arg_str(&s, key); op_arg_str(&s, value); }
                    else { buffer_json_member_add_string_or_empty(wb, key, NULL); op_begin(&s, "MSEN"); op_arg_str(&s, key); }
                    break;
                case 7: buffer_json_member_add_quoted_string(wb, key, value); op_begin(&s, "MQ"); op_arg_str(&s, key); op_arg_str(&s, value); break;
                case 8: rnd_uuid(uuid); buffer_json_member_add_uuid(wb, key, *(nd_uuid_t *)uuid); op_begin(&s, "MU"); op_arg_str(&s, key); op_arg(&s, uuid, 16); break;
                case 9: rnd_uuid(uuid); buffer_json_member_add_uuid_ptr(wb, key, (nd_uuid_t *)uuid); op_begin(&s, "MUP"); op_arg_str(&s, key); op_arg(&s, uuid, 16); break;
                case 10: rnd_uuid(uuid); buffer_json_member_add_uuid_compact(wb, key, *(nd_uuid_t *)uuid); op_begin(&s, "MUC"); op_arg_str(&s, key); op_arg(&s, uuid, 16); break;
                case 11: buffer_json_member_add_boolean(wb, key, u & 1); op_begin(&s, "MB"); op_arg_str(&s, key); op_arg_u64(&s, u & 1); break;
                case 12: buffer_json_member_add_uint64(wb, key, u); op_begin(&s, "MU64"); op_arg_str(&s, key); op_arg_u64(&s, u); break;
                case 13: buffer_json_member_add_int64(wb, key, (int64_t)u); op_begin(&s, "MI"); op_arg_str(&s, key); op_arg_i64(&s, (int64_t)u); break;
                case 14: buffer_json_member_add_double(wb, key, d); op_begin(&s, "MD"); op_arg_str(&s, key); op_arg_u64(&s, bits_of(d)); break;
                case 15: buffer_json_member_add_time_t(wb, key, t); op_begin(&s, "MT"); op_arg_str(&s, key); op_arg_i64(&s, t); break;
                case 16: buffer_json_member_add_time_t_formatted(wb, key, t, u & 1); op_begin(&s, "MTF"); op_arg_str(&s, key); op_arg_i64(&s, t); op_arg_u64(&s, u & 1); break;
                case 17: buffer_json_member_add_datetime_rfc3339(wb, key, u, true); op_begin(&s, "MDT"); op_arg_str(&s, key); op_arg_u64(&s, u); break;
                case 18: {
                    int64_t duration = (int64_t)(u >> 1) * (rnd_below(2) ? 1 : -1);
                    buffer_json_member_add_duration_ut(wb, key, duration); op_begin(&s, "MDU"); op_arg_str(&s, key); op_arg_i64(&s, duration);
                    break;
                }
                case 19: buffer_json_member_add_uuid_ptr(wb, key, NULL); op_begin(&s, "MUPN"); op_arg_str(&s, key); break;
                case 20: buffer_json_member_add_quoted_string(wb, key, NULL); op_begin(&s, "MQN"); op_arg_str(&s, key); break;
                default: buffer_json_member_add_string_or_omit(wb, key, NULL); op_begin(&s, "MSON"); op_arg_str(&s, key); break;
            }
        }
    }

    if(finalize) {
        buffer_json_finalize(wb);
        op_begin(&s, "F");
    }

    tab(f);
    esc(f, buffer_tostring(wb), buffer_strlen(wb));
    eol(f);
}

static void gen_json(const char *dir) {
    FILE *f = out_open(dir, "json.tsv", "operations script | output");
    BUFFER *wb = buffer_create(0, NULL);
    for(int i = 0; i < 1500; i++)
        json_script(f, wb);
    buffer_free(wb);
    fclose(f);

    f = out_open(dir, "rfc3339.tsv", "usec | fractional digits | rfc3339_datetime_ut(utc)");
    for(int i = 0; i < 3000; i++) {
        uint64_t ut;
        switch(rnd_below(4)) {
            case 0: ut = rnd(); break;
            case 1: ut = rnd_below(4102444800ULL) * 1000000ULL; break;
            case 2: ut = rnd_below(4102444800ULL) * 1000000ULL + rnd_below(1000000); break;
            default: ut = rnd_below(253402300800ULL * 1000000ULL); break;
        }
        if(i < 4) ut = (uint64_t[]){ 0, 1, 999999, 951782400000000ULL }[i];
        size_t digits = rnd_below(12);
        char buf[RFC3339_MAX_LENGTH];
        rfc3339_datetime_ut(buf, sizeof(buf), ut, digits, true);
        fprintf(f, "%" PRIu64 "\t%zu\t", ut, digits);
        esc_str(f, buf);
        eol(f);
    }
    fclose(f);
}

// ------------------------------------------------------------------------------------------------

int main(int argc, char **argv) {
    if(argc != 2) {
        fprintf(stderr, "usage: %s <output directory>\n", argv[0]);
        return 1;
    }
    const char *dir = argv[1];
    BUFFER *wb = buffer_create(0, NULL);

    gen_print_double(dir, wb);
    gen_print_integers(dir, wb);
    gen_parse_numbers(dir, wb);
    gen_durations(dir);
    gen_sizes(dir);
    gen_simple_patterns(dir);
    gen_sanitizers(dir);
    gen_json_escape(dir);
    gen_json(dir);

    buffer_free(wb);
    return 0;
}
