/* Generated by re2c 1.3 on Sun Jul  4 15:35:50 2021 */
#line 1 "proc_pid_stat.in.c"
#include <string.h>
#include "proc_pid_stat.h"

void cp_comm(char *dest, char *lparen, char *rparen) {
    if (!lparen && !rparen && (lparen < rparen))
        return;

    size_t n = (rparen - lparen);
    if (n > MAX_COMM_LEN)
        n = MAX_COMM_LEN;

    strncpy(dest, lparen + 1, n - 1);
    dest[n - 1] = '\0';
}

void parse_number(proc_pid_stat_t *pid_stat, char *s, int col) {
    switch (col) {
        default:
            break;
        case 4:
            pid_stat->ppid = str2uint32_t(s);
            break;
        case 10:
            pid_stat->minflt = str2uint64_t(s);
            break;
        case 11:
            pid_stat->cminflt = str2uint64_t(s);
            break;
        case 12:
            pid_stat->majflt = str2uint64_t(s);
            break;
        case 13:
            pid_stat->cmajflt = str2uint64_t(s);
            break;
        case 14:
            pid_stat->utime = str2uint64_t(s);
            break;
        case 15:
            pid_stat->stime = str2uint64_t(s);
            break;
        case 16:
            pid_stat->cutime = str2uint64_t(s);
            break;
        case 17:
            pid_stat->cstime = str2uint64_t(s);
            break;
        case 20:
            pid_stat->num_threads = str2uint32_t(s);
            break;
        case 22:
            pid_stat->starttime = str2uint64_t(s);
            break;
        case 43:
            pid_stat->guest_time = str2uint64_t(s);
            break;
        case 44:
            pid_stat->cguest_time = str2uint64_t(s);
            break;
    }
}

void proc_pid_stat(char *buf, proc_pid_stat_t *pid_stat) {
    char *YYCURSOR = buf;

    int col = 0;

    for (;;) {
        char *p = YYCURSOR;

    
#line 74 "proc_pid_stat.c"
{
	char yych;
	yych = *YYCURSOR;
	if (yych <= ',') {
		if (yych <= 0x1F) {
			if (yych <= 0x00) goto yy2;
			if (yych == '\t') goto yy6;
			goto yy4;
		} else {
			if (yych <= ' ') goto yy6;
			if (yych == '(') goto yy9;
			goto yy4;
		}
	} else {
		if (yych <= '@') {
			if (yych <= '-') goto yy11;
			if (yych <= '/') goto yy4;
			if (yych <= '9') goto yy12;
			goto yy4;
		} else {
			if (yych <= 'Z') goto yy15;
			if (yych <= '`') goto yy4;
			if (yych <= 'z') goto yy15;
			goto yy4;
		}
	}
yy2:
	++YYCURSOR;
#line 79 "proc_pid_stat.in.c"
	{ return; }
#line 105 "proc_pid_stat.c"
yy4:
	++YYCURSOR;
yy5:
#line 99 "proc_pid_stat.in.c"
	{ return; }
#line 111 "proc_pid_stat.c"
yy6:
	yych = *++YYCURSOR;
	if (yych == '\t') goto yy6;
	if (yych == ' ') goto yy6;
#line 80 "proc_pid_stat.in.c"
	{ continue; }
#line 118 "proc_pid_stat.c"
yy9:
	++YYCURSOR;
#line 82 "proc_pid_stat.in.c"
	{
            col++;

            char *lparen = p;
            char *rparen = strrchr(p, ')');

            cp_comm(pid_stat->comm, lparen, rparen);

            // continue lexing after comm's rightmost paren.
            YYCURSOR = rparen + 1;
            continue;
        }
#line 134 "proc_pid_stat.c"
yy11:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy5;
	if (yych >= ':') goto yy5;
yy12:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy14;
	if (yych <= '9') goto yy12;
yy14:
#line 94 "proc_pid_stat.in.c"
	{
            col++; 
            parse_number(pid_stat, p, col);
            continue;
        }
#line 150 "proc_pid_stat.c"
yy15:
	++YYCURSOR;
#line 81 "proc_pid_stat.in.c"
	{ col++; continue; }
#line 155 "proc_pid_stat.c"
}
#line 100 "proc_pid_stat.in.c"

    }
}
