/* Generated by re2c 1.3 on Sun Jul  4 00:34:44 2021 */
#line 1 "proc_stat.in.c"
#include "proc_stat.h"

void proc_stat(char *buf, proc_stat_t *pstat) {
    char *YYCURSOR = buf;
    char *YYMARKER;

    int col = 0;

    for (;;) {
        char *p = YYCURSOR;

    
#line 16 "proc_stat.cc"
{
	char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,  64,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		 64,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *YYCURSOR;
	if (yybm[0+yych] & 64) {
		goto yy6;
	}
	if (yych <= '9') {
		if (yych <= 0x00) goto yy2;
		if (yych <= '/') goto yy4;
		goto yy9;
	} else {
		if (yych == 'c') goto yy12;
		goto yy4;
	}
yy2:
	++YYCURSOR;
#line 20 "proc_stat.in.c"
	{ return; }
#line 69 "proc_stat.cc"
yy4:
	++YYCURSOR;
yy5:
#line 64 "proc_stat.in.c"
	{ col = 0; continue; }
#line 75 "proc_stat.cc"
yy6:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 64) {
		goto yy6;
	}
#line 21 "proc_stat.in.c"
	{ continue; }
#line 83 "proc_stat.cc"
yy9:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy9;
	}
#line 23 "proc_stat.in.c"
	{
            uint32_t v = str2uint32_t(p);
            
            switch (col) {
            case 1:
                pstat->user = v;
                break;
            case 2:
                pstat->nice = v;
                break;               
            case 3:
                pstat->system = v;
                break;               
            case 4:
                pstat->idle = v;
                break;               
            case 5:
                pstat->iowait = v;
                break;               
            case 6:
                pstat->irq = v;
                break;               
            case 7:
                pstat->softirq = v;
                break;               
            case 8:
                pstat->steal = v;
                break;               
            case 9:
                pstat->guest = v;
                break;               
            case 10:
                pstat->guest_nice = v;
                return;
            default:
                continue;
            }

            col += 1;
            continue;
        }
#line 131 "proc_stat.cc"
yy12:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych != 'p') goto yy5;
	yych = *++YYCURSOR;
	if (yych == 'u') goto yy15;
yy14:
	YYCURSOR = YYMARKER;
	goto yy5;
yy15:
	yych = *++YYCURSOR;
	if (yych == '\t') goto yy16;
	if (yych != ' ') goto yy14;
yy16:
	yych = *++YYCURSOR;
	if (yych == '\t') goto yy16;
	if (yych == ' ') goto yy16;
#line 22 "proc_stat.in.c"
	{ col = 1; continue; }
#line 150 "proc_stat.cc"
}
#line 65 "proc_stat.in.c"

    }
}
