/* Generated by re2c 1.3 on Sun Jul  4 15:35:50 2021 */
#line 1 "proc_pid_status.in.c"
#include "proc_pid_status.h"

char *parse_effective_id(char *buf, uint64_t *id) {
    char *YYCURSOR = buf;
    char *YYMARKER;

    char *tag;
    const char *yyt1;


#line 14 "proc_pid_status.c"
{
	char yych;
	yych = *YYCURSOR;
	if (yych == '\t') goto yy4;
	if (yych == ' ') goto yy4;
	++YYCURSOR;
yy3:
#line 24 "proc_pid_status.in.c"
	{ return YYCURSOR; }
#line 24 "proc_pid_status.c"
yy4:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x1F) {
		if (yych != '\t') goto yy3;
	} else {
		if (yych <= ' ') goto yy5;
		if (yych <= '0') goto yy3;
		if (yych <= '9') goto yy8;
		goto yy3;
	}
yy5:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy5;
	} else {
		if (yych <= ' ') goto yy5;
		if (yych <= '0') goto yy7;
		if (yych <= '9') goto yy8;
	}
yy7:
	YYCURSOR = YYMARKER;
	goto yy3;
yy8:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych != '\t') goto yy7;
	} else {
		if (yych <= ' ') goto yy10;
		if (yych <= '/') goto yy7;
		if (yych <= '9') goto yy8;
		goto yy7;
	}
yy10:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy10;
		goto yy7;
	} else {
		if (yych <= ' ') goto yy10;
		if (yych <= '0') goto yy7;
		if (yych >= ':') goto yy7;
		yyt1 = YYCURSOR;
	}
yy12:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych != '\t') goto yy7;
	} else {
		if (yych <= ' ') goto yy14;
		if (yych <= '/') goto yy7;
		if (yych <= '9') goto yy12;
		goto yy7;
	}
yy14:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy14;
		goto yy7;
	} else {
		if (yych <= ' ') goto yy14;
		if (yych <= '0') goto yy7;
		if (yych >= ':') goto yy7;
	}
yy16:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych != '\t') goto yy7;
	} else {
		if (yych <= ' ') goto yy18;
		if (yych <= '/') goto yy7;
		if (yych <= '9') goto yy16;
		goto yy7;
	}
yy18:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy18;
		goto yy7;
	} else {
		if (yych <= ' ') goto yy18;
		if (yych <= '0') goto yy7;
		if (yych >= ':') goto yy7;
	}
yy20:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy22;
	if (yych <= '9') goto yy20;
yy22:
	tag = yyt1;
#line 20 "proc_pid_status.in.c"
	{
        *id = str2uint64_t(tag);
        return YYCURSOR;
    }
#line 119 "proc_pid_status.c"
}
#line 25 "proc_pid_status.in.c"

}

char *parse_size(char *buf, uint64_t *size) {
    char *YYCURSOR = buf;
    char *YYMARKER;

    char *tag;
    const char *yyt1;


#line 133 "proc_pid_status.c"
{
	char yych;
	yych = *YYCURSOR;
	if (yych == '\t') goto yy27;
	if (yych == ' ') goto yy27;
	++YYCURSOR;
yy26:
#line 40 "proc_pid_status.in.c"
	{ return YYCURSOR; }
#line 143 "proc_pid_status.c"
yy27:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych <= 0x1F) {
		if (yych != '\t') goto yy26;
	} else {
		if (yych <= ' ') goto yy28;
		if (yych <= '/') goto yy26;
		if (yych <= '9') {
			yyt1 = YYCURSOR;
			goto yy31;
		}
		goto yy26;
	}
yy28:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy28;
	} else {
		if (yych <= ' ') goto yy28;
		if (yych <= '/') goto yy30;
		if (yych <= '9') {
			yyt1 = YYCURSOR;
			goto yy31;
		}
	}
yy30:
	YYCURSOR = YYMARKER;
	goto yy26;
yy31:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych != '\t') goto yy30;
	} else {
		if (yych <= ' ') goto yy33;
		if (yych <= '/') goto yy30;
		if (yych <= '9') goto yy31;
		goto yy30;
	}
yy33:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy33;
		goto yy30;
	} else {
		if (yych <= ' ') goto yy33;
		if (yych != 'k') goto yy30;
	}
	yych = *++YYCURSOR;
	if (yych != 'B') goto yy30;
	++YYCURSOR;
	tag = yyt1;
#line 36 "proc_pid_status.in.c"
	{
        *size = str2uint64_t(tag);
        return YYCURSOR;
    }
#line 200 "proc_pid_status.c"
}
#line 41 "proc_pid_status.in.c"

}

void proc_pid_status(char *buf, proc_pid_status_t *pid_status) {
    char *YYCURSOR = buf;
    char *YYMARKER;

    for (int needed = 0; needed != 7;) {
    
#line 212 "proc_pid_status.c"
{
	char yych;
	yych = *YYCURSOR;
	if (yych <= 'F') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy40;
			if (yych <= 0x08) goto yy42;
			goto yy44;
		} else {
			if (yych == ' ') goto yy44;
			goto yy42;
		}
	} else {
		if (yych <= 'R') {
			if (yych <= 'G') goto yy47;
			if (yych <= 'Q') goto yy42;
			goto yy48;
		} else {
			if (yych <= 'T') goto yy42;
			if (yych <= 'U') goto yy49;
			if (yych <= 'V') goto yy50;
			goto yy42;
		}
	}
yy40:
	++YYCURSOR;
#line 51 "proc_pid_status.in.c"
	{ return; }
#line 241 "proc_pid_status.c"
yy42:
	++YYCURSOR;
yy43:
#line 50 "proc_pid_status.in.c"
	{ continue; }
#line 247 "proc_pid_status.c"
yy44:
	yych = *++YYCURSOR;
	if (yych == '\t') goto yy44;
	if (yych == ' ') goto yy44;
#line 52 "proc_pid_status.in.c"
	{ continue; }
#line 254 "proc_pid_status.c"
yy47:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'i') goto yy51;
	goto yy43;
yy48:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 's') goto yy53;
	goto yy43;
yy49:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'i') goto yy54;
	goto yy43;
yy50:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'm') goto yy55;
	goto yy43;
yy51:
	yych = *++YYCURSOR;
	if (yych == 'd') goto yy56;
yy52:
	YYCURSOR = YYMARKER;
	goto yy43;
yy53:
	yych = *++YYCURSOR;
	if (yych == 's') goto yy57;
	goto yy52;
yy54:
	yych = *++YYCURSOR;
	if (yych == 'd') goto yy58;
	goto yy52;
yy55:
	yych = *++YYCURSOR;
	if (yych <= 'Q') goto yy52;
	if (yych <= 'R') goto yy59;
	if (yych <= 'S') goto yy60;
	goto yy52;
yy56:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy61;
	goto yy52;
yy57:
	yych = *++YYCURSOR;
	if (yych == 'F') goto yy63;
	if (yych == 'S') goto yy64;
	goto yy52;
yy58:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy65;
	goto yy52;
yy59:
	yych = *++YYCURSOR;
	if (yych == 'S') goto yy67;
	goto yy52;
yy60:
	yych = *++YYCURSOR;
	if (yych == 'i') goto yy68;
	if (yych == 'w') goto yy69;
	goto yy52;
yy61:
	++YYCURSOR;
#line 58 "proc_pid_status.in.c"
	{
            YYCURSOR = parse_effective_id(YYCURSOR, &pid_status->egid);
            needed++;
            continue;
        }
#line 321 "proc_pid_status.c"
yy63:
	yych = *++YYCURSOR;
	if (yych == 'i') goto yy70;
	goto yy52;
yy64:
	yych = *++YYCURSOR;
	if (yych == 'h') goto yy71;
	goto yy52;
yy65:
	++YYCURSOR;
#line 53 "proc_pid_status.in.c"
	{
            YYCURSOR = parse_effective_id(YYCURSOR, &pid_status->euid);
            needed++;
            continue;
        }
#line 338 "proc_pid_status.c"
yy67:
	yych = *++YYCURSOR;
	if (yych == 'S') goto yy72;
	goto yy52;
yy68:
	yych = *++YYCURSOR;
	if (yych == 'z') goto yy73;
	goto yy52;
yy69:
	yych = *++YYCURSOR;
	if (yych == 'a') goto yy74;
	goto yy52;
yy70:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy75;
	goto yy52;
yy71:
	yych = *++YYCURSOR;
	if (yych == 'm') goto yy76;
	goto yy52;
yy72:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy77;
	goto yy52;
yy73:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy79;
	goto yy52;
yy74:
	yych = *++YYCURSOR;
	if (yych == 'p') goto yy80;
	goto yy52;
yy75:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy81;
	goto yy52;
yy76:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy82;
	goto yy52;
yy77:
	++YYCURSOR;
#line 68 "proc_pid_status.in.c"
	{
            YYCURSOR = parse_size(YYCURSOR, &pid_status->vm_rss);
            needed++;
            continue;
        }
#line 387 "proc_pid_status.c"
yy79:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy83;
	goto yy52;
yy80:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy85;
	goto yy52;
yy81:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy87;
	goto yy52;
yy82:
	yych = *++YYCURSOR;
	if (yych == 'm') goto yy89;
	goto yy52;
yy83:
	++YYCURSOR;
#line 63 "proc_pid_status.in.c"
	{
            YYCURSOR = parse_size(YYCURSOR, &pid_status->vm_size);
            needed++;
            continue;
        }
#line 412 "proc_pid_status.c"
yy85:
	++YYCURSOR;
#line 83 "proc_pid_status.in.c"
	{
            YYCURSOR = parse_size(YYCURSOR, &pid_status->vm_swap);
            needed++;
            continue;
        }
#line 421 "proc_pid_status.c"
yy87:
	++YYCURSOR;
#line 73 "proc_pid_status.in.c"
	{
            YYCURSOR = parse_size(YYCURSOR, &pid_status->rss_file);
            needed++;
            continue;
        }
#line 430 "proc_pid_status.c"
yy89:
	yych = *++YYCURSOR;
	if (yych != ':') goto yy52;
	++YYCURSOR;
#line 78 "proc_pid_status.in.c"
	{
            YYCURSOR = parse_size(YYCURSOR, &pid_status->rss_shmem);
            needed++;
            continue;
        }
#line 441 "proc_pid_status.c"
}
#line 88 "proc_pid_status.in.c"

    }
}
