/* Generated by re2c 1.3 on Sun Jul  4 00:34:44 2021 */
#line 1 "proc_pid_status.in.c"
#include "proc_pid_status.h"

char *parse_effective_id(char *buf, uint64_t *id) {
    char *YYCURSOR = buf;
    char *YYMARKER;

    char *tag;
    const char *yyt1;


#line 14 "proc_pid_status.cc"
{
	char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,  64,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		 64,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *YYCURSOR;
	if (yych == '\t') goto yy4;
	if (yych == ' ') goto yy4;
	++YYCURSOR;
yy3:
#line 24 "proc_pid_status.in.c"
	{ return YYCURSOR; }
#line 58 "proc_pid_status.cc"
yy4:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yybm[0+yych] & 64) {
		goto yy5;
	}
	if (yych <= '0') goto yy3;
	if (yych <= '9') goto yy8;
	goto yy3;
yy5:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 64) {
		goto yy5;
	}
	if (yych <= '0') goto yy7;
	if (yych <= '9') goto yy8;
yy7:
	YYCURSOR = YYMARKER;
	goto yy3;
yy8:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy8;
	}
	if (yych == '\t') goto yy10;
	if (yych != ' ') goto yy7;
yy10:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy10;
		goto yy7;
	} else {
		if (yych <= ' ') goto yy10;
		if (yych <= '0') goto yy7;
		if (yych >= ':') goto yy7;
		yyt1 = YYCURSOR;
	}
yy12:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych != '\t') goto yy7;
	} else {
		if (yych <= ' ') goto yy14;
		if (yych <= '/') goto yy7;
		if (yych <= '9') goto yy12;
		goto yy7;
	}
yy14:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy14;
		goto yy7;
	} else {
		if (yych <= ' ') goto yy14;
		if (yych <= '0') goto yy7;
		if (yych >= ':') goto yy7;
	}
yy16:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych != '\t') goto yy7;
	} else {
		if (yych <= ' ') goto yy18;
		if (yych <= '/') goto yy7;
		if (yych <= '9') goto yy16;
		goto yy7;
	}
yy18:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy18;
		goto yy7;
	} else {
		if (yych <= ' ') goto yy18;
		if (yych <= '0') goto yy7;
		if (yych >= ':') goto yy7;
	}
yy20:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy22;
	if (yych <= '9') goto yy20;
yy22:
	tag = yyt1;
#line 20 "proc_pid_status.in.c"
	{
        *id = str2uint64_t(tag);
        return YYCURSOR;
    }
#line 146 "proc_pid_status.cc"
}
#line 25 "proc_pid_status.in.c"

}

char *parse_size(char *buf, uint64_t *size) {
    char *YYCURSOR = buf;
    char *YYMARKER;

    char *tag;
    const char *yyt1;


#line 160 "proc_pid_status.cc"
{
	char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,  64,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		 64,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *YYCURSOR;
	if (yych == '\t') goto yy27;
	if (yych == ' ') goto yy27;
	++YYCURSOR;
yy26:
#line 40 "proc_pid_status.in.c"
	{ return YYCURSOR; }
#line 204 "proc_pid_status.cc"
yy27:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yybm[0+yych] & 64) {
		goto yy28;
	}
	if (yych <= '/') goto yy26;
	if (yych <= '9') {
		yyt1 = YYCURSOR;
		goto yy31;
	}
	goto yy26;
yy28:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 64) {
		goto yy28;
	}
	if (yych <= '/') goto yy30;
	if (yych <= '9') {
		yyt1 = YYCURSOR;
		goto yy31;
	}
yy30:
	YYCURSOR = YYMARKER;
	goto yy26;
yy31:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy31;
	}
	if (yych == '\t') goto yy33;
	if (yych != ' ') goto yy30;
yy33:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy33;
		goto yy30;
	} else {
		if (yych <= ' ') goto yy33;
		if (yych != 'k') goto yy30;
	}
	yych = *++YYCURSOR;
	if (yych != 'B') goto yy30;
	++YYCURSOR;
	tag = yyt1;
#line 36 "proc_pid_status.in.c"
	{
        *size = str2uint64_t(tag);
        return YYCURSOR;
    }
#line 254 "proc_pid_status.cc"
}
#line 41 "proc_pid_status.in.c"

}

void proc_pid_status(char *buf, proc_pid_status_t *pid_status) {
    char *YYCURSOR = buf;
    char *YYMARKER;

    for (;;) {
    
#line 266 "proc_pid_status.cc"
{
	char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy40, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy44, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy44, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy47,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy48, &&yy42, &&yy42, &&yy49, &&yy50, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42,
			&&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42, &&yy42
		};
		goto *yytarget[yych];
	}
yy40:
	++YYCURSOR;
#line 51 "proc_pid_status.in.c"
	{ return; }
#line 345 "proc_pid_status.cc"
yy42:
	++YYCURSOR;
yy43:
#line 50 "proc_pid_status.in.c"
	{ continue; }
#line 351 "proc_pid_status.cc"
yy44:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy44;
	}
#line 52 "proc_pid_status.in.c"
	{ continue; }
#line 359 "proc_pid_status.cc"
yy47:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'i') goto yy51;
	goto yy43;
yy48:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 's') goto yy53;
	goto yy43;
yy49:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'i') goto yy54;
	goto yy43;
yy50:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'm') goto yy55;
	goto yy43;
yy51:
	yych = *++YYCURSOR;
	if (yych == 'd') goto yy56;
yy52:
	YYCURSOR = YYMARKER;
	goto yy43;
yy53:
	yych = *++YYCURSOR;
	if (yych == 's') goto yy57;
	goto yy52;
yy54:
	yych = *++YYCURSOR;
	if (yych == 'd') goto yy58;
	goto yy52;
yy55:
	yych = *++YYCURSOR;
	if (yych <= 'Q') goto yy52;
	if (yych <= 'R') goto yy59;
	if (yych <= 'S') goto yy60;
	goto yy52;
yy56:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy61;
	goto yy52;
yy57:
	yych = *++YYCURSOR;
	if (yych == 'F') goto yy63;
	if (yych == 'S') goto yy64;
	goto yy52;
yy58:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy65;
	goto yy52;
yy59:
	yych = *++YYCURSOR;
	if (yych == 'S') goto yy67;
	goto yy52;
yy60:
	yych = *++YYCURSOR;
	if (yych == 'i') goto yy68;
	if (yych == 'w') goto yy69;
	goto yy52;
yy61:
	++YYCURSOR;
#line 57 "proc_pid_status.in.c"
	{
            YYCURSOR = parse_effective_id(YYCURSOR, &pid_status->egid);
            continue;
        }
#line 425 "proc_pid_status.cc"
yy63:
	yych = *++YYCURSOR;
	if (yych == 'i') goto yy70;
	goto yy52;
yy64:
	yych = *++YYCURSOR;
	if (yych == 'h') goto yy71;
	goto yy52;
yy65:
	++YYCURSOR;
#line 53 "proc_pid_status.in.c"
	{
            YYCURSOR = parse_effective_id(YYCURSOR, &pid_status->euid);
            continue;
        }
#line 441 "proc_pid_status.cc"
yy67:
	yych = *++YYCURSOR;
	if (yych == 'S') goto yy72;
	goto yy52;
yy68:
	yych = *++YYCURSOR;
	if (yych == 'z') goto yy73;
	goto yy52;
yy69:
	yych = *++YYCURSOR;
	if (yych == 'a') goto yy74;
	goto yy52;
yy70:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy75;
	goto yy52;
yy71:
	yych = *++YYCURSOR;
	if (yych == 'm') goto yy76;
	goto yy52;
yy72:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy77;
	goto yy52;
yy73:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy79;
	goto yy52;
yy74:
	yych = *++YYCURSOR;
	if (yych == 'p') goto yy80;
	goto yy52;
yy75:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy81;
	goto yy52;
yy76:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy82;
	goto yy52;
yy77:
	++YYCURSOR;
#line 65 "proc_pid_status.in.c"
	{
            YYCURSOR = parse_size(YYCURSOR, &pid_status->vm_rss);
            continue;
        }
#line 489 "proc_pid_status.cc"
yy79:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy83;
	goto yy52;
yy80:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy85;
	goto yy52;
yy81:
	yych = *++YYCURSOR;
	if (yych == ':') goto yy87;
	goto yy52;
yy82:
	yych = *++YYCURSOR;
	if (yych == 'm') goto yy89;
	goto yy52;
yy83:
	++YYCURSOR;
#line 61 "proc_pid_status.in.c"
	{
            YYCURSOR = parse_size(YYCURSOR, &pid_status->vm_size);
            continue;
        }
#line 513 "proc_pid_status.cc"
yy85:
	++YYCURSOR;
#line 77 "proc_pid_status.in.c"
	{
            YYCURSOR = parse_size(YYCURSOR, &pid_status->vm_swap);
            continue;
        }
#line 521 "proc_pid_status.cc"
yy87:
	++YYCURSOR;
#line 69 "proc_pid_status.in.c"
	{
            YYCURSOR = parse_size(YYCURSOR, &pid_status->rss_file);
            continue;
        }
#line 529 "proc_pid_status.cc"
yy89:
	yych = *++YYCURSOR;
	if (yych != ':') goto yy52;
	++YYCURSOR;
#line 73 "proc_pid_status.in.c"
	{
            YYCURSOR = parse_size(YYCURSOR, &pid_status->rss_shmem);
            continue;
        }
#line 539 "proc_pid_status.cc"
}
#line 81 "proc_pid_status.in.c"

    }
}
