/* Generated by re2c 1.3 on Sun Jul  4 00:34:44 2021 */
#line 1 "proc_pid_stat.in.c"
#include <string.h>
#include "proc_pid_stat.h"

void cp_comm(char *dest, char *lparen, char *rparen) {
    if (!lparen && !rparen && (lparen < rparen))
        return;

    size_t n = (rparen - lparen);
    if (n > MAX_COMM_LEN)
        n = MAX_COMM_LEN;

    strncpy(dest, lparen + 1, n - 1);
    dest[n - 1] = '\0';
}

void parse_number(proc_pid_stat_t *pid_stat, char *s, int col) {
    switch (col) {
        default:
            break;
        case 4:
            pid_stat->ppid = str2uint32_t(s);
            break;
        case 10:
            pid_stat->minflt = str2uint64_t(s);
            break;
        case 11:
            pid_stat->cminflt = str2uint64_t(s);
            break;
        case 12:
            pid_stat->majflt = str2uint64_t(s);
            break;
        case 13:
            pid_stat->cmajflt = str2uint64_t(s);
            break;
        case 14:
            pid_stat->utime = str2uint64_t(s);
            break;
        case 15:
            pid_stat->stime = str2uint64_t(s);
            break;
        case 16:
            pid_stat->cutime = str2uint64_t(s);
            break;
        case 17:
            pid_stat->cstime = str2uint64_t(s);
            break;
        case 20:
            pid_stat->num_threads = str2uint32_t(s);
            break;
        case 22:
            pid_stat->starttime = str2uint64_t(s);
            break;
        case 43:
            pid_stat->guest_time = str2uint64_t(s);
            break;
        case 44:
            pid_stat->cguest_time = str2uint64_t(s);
            break;
    }
}

void proc_pid_stat(char *buf, proc_pid_stat_t *pid_stat) {
    char *YYCURSOR = buf;

    int col = 0;

    for (;;) {
        char *p = YYCURSOR;

    
#line 74 "proc_pid_stat.cc"
{
	char yych;
	static const unsigned char yybm[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,  64,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		 64,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128, 128, 128, 128, 128, 128, 128, 128, 
		128, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	yych = *YYCURSOR;
	{
		static void *yytarget[256] = {
			&&yy2,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy6,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy6,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy9,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy11, &&yy4,  &&yy4,
			&&yy12, &&yy12, &&yy12, &&yy12, &&yy12, &&yy12, &&yy12, &&yy12,
			&&yy12, &&yy12, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15,
			&&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15,
			&&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15,
			&&yy15, &&yy15, &&yy15, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15,
			&&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15,
			&&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15, &&yy15,
			&&yy15, &&yy15, &&yy15, &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,
			&&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4,  &&yy4
		};
		goto *yytarget[yych];
	}
yy2:
	++YYCURSOR;
#line 79 "proc_pid_stat.in.c"
	{ return; }
#line 153 "proc_pid_stat.cc"
yy4:
	++YYCURSOR;
yy5:
#line 99 "proc_pid_stat.in.c"
	{ return; }
#line 159 "proc_pid_stat.cc"
yy6:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 64) {
		goto yy6;
	}
#line 80 "proc_pid_stat.in.c"
	{ continue; }
#line 167 "proc_pid_stat.cc"
yy9:
	++YYCURSOR;
#line 82 "proc_pid_stat.in.c"
	{
            col++;

            char *lparen = p;
            char *rparen = strrchr(p, ')');

            cp_comm(pid_stat->comm, lparen, rparen);

            // continue lexing after comm's rightmost paren.
            YYCURSOR = rparen + 1;
            continue;
        }
#line 183 "proc_pid_stat.cc"
yy11:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy12;
	}
	goto yy5;
yy12:
	yych = *++YYCURSOR;
	if (yybm[0+yych] & 128) {
		goto yy12;
	}
#line 94 "proc_pid_stat.in.c"
	{
            col++; 
            parse_number(pid_stat, p, col);
            continue;
        }
#line 201 "proc_pid_stat.cc"
yy15:
	++YYCURSOR;
#line 81 "proc_pid_stat.in.c"
	{ col++; continue; }
#line 206 "proc_pid_stat.cc"
}
#line 100 "proc_pid_stat.in.c"

    }
}
