/* Generated by re2c 1.3 on Sun Jul  4 15:35:50 2021 */
#line 1 "proc_pid_io.in.c"
#include "proc_pid_io.h"

enum token_t {
    TOKEN_RCHAR,
    TOKEN_WCHAR,
    TOKEN_SYSCR,
    TOKEN_SYSCW,
    TOKEN_READ_BYTES,
    TOKEN_WRITE_BYTES,
    TOKEN_CANCELLED_WRITE_BYTES,
    TOKEN_INVALID
};

void proc_pid_io(char *buf, proc_pid_io_t *pid_io) {
    char *YYCURSOR = buf;
    char *YYMARKER;

    enum token_t tok = TOKEN_INVALID;

    for (;;) {
        char *p = YYCURSOR;

    
#line 27 "proc_pid_io.c"
{
	char yych;
	yych = *YYCURSOR;
	if (yych <= ':') {
		if (yych <= 0x1F) {
			if (yych <= 0x00) goto yy2;
			if (yych == '\n') goto yy6;
			goto yy4;
		} else {
			if (yych <= ' ') goto yy6;
			if (yych <= '/') goto yy4;
			if (yych <= '9') goto yy9;
			goto yy6;
		}
	} else {
		if (yych <= 'r') {
			if (yych == 'c') goto yy12;
			if (yych <= 'q') goto yy4;
			goto yy13;
		} else {
			if (yych <= 's') goto yy14;
			if (yych == 'w') goto yy15;
			goto yy4;
		}
	}
yy2:
	++YYCURSOR;
#line 31 "proc_pid_io.in.c"
	{ return; }
#line 57 "proc_pid_io.c"
yy4:
	++YYCURSOR;
yy5:
#line 70 "proc_pid_io.in.c"
	{
            tok = TOKEN_INVALID;
            continue;
        }
#line 66 "proc_pid_io.c"
yy6:
	yych = *++YYCURSOR;
	if (yych <= 0x1F) {
		if (yych == '\n') goto yy6;
	} else {
		if (yych <= ' ') goto yy6;
		if (yych == ':') goto yy6;
	}
#line 32 "proc_pid_io.in.c"
	{ continue; }
#line 77 "proc_pid_io.c"
yy9:
	yych = *++YYCURSOR;
	if (yych <= '/') goto yy11;
	if (yych <= '9') goto yy9;
yy11:
#line 40 "proc_pid_io.in.c"
	{
            switch (tok) {
            case TOKEN_RCHAR:
                pid_io->rchar  = str2uint32_t(p);
                break;
            case TOKEN_WCHAR:
                pid_io->wchar  = str2uint32_t(p);
                break;
            case TOKEN_SYSCR:
                pid_io->syscr  = str2uint32_t(p);
                break;
            case TOKEN_SYSCW:
                pid_io->syscw  = str2uint32_t(p);
                break;
            case TOKEN_READ_BYTES:
                pid_io->read_bytes  = str2uint32_t(p);
                break;
            case TOKEN_WRITE_BYTES:
                pid_io->write_bytes  = str2uint32_t(p);
                break;
            case TOKEN_CANCELLED_WRITE_BYTES:
                pid_io->cancelled_write_bytes  = str2uint32_t(p);
                break;
            case TOKEN_INVALID:
                break;
            }

            tok = TOKEN_INVALID;
            continue;
        }
#line 114 "proc_pid_io.c"
yy12:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'a') goto yy16;
	goto yy5;
yy13:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'c') goto yy18;
	if (yych == 'e') goto yy19;
	goto yy5;
yy14:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'y') goto yy20;
	goto yy5;
yy15:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych == 'c') goto yy21;
	if (yych == 'r') goto yy22;
	goto yy5;
yy16:
	yych = *++YYCURSOR;
	if (yych == 'n') goto yy23;
yy17:
	YYCURSOR = YYMARKER;
	goto yy5;
yy18:
	yych = *++YYCURSOR;
	if (yych == 'h') goto yy24;
	goto yy17;
yy19:
	yych = *++YYCURSOR;
	if (yych == 'a') goto yy25;
	goto yy17;
yy20:
	yych = *++YYCURSOR;
	if (yych == 's') goto yy26;
	goto yy17;
yy21:
	yych = *++YYCURSOR;
	if (yych == 'h') goto yy27;
	goto yy17;
yy22:
	yych = *++YYCURSOR;
	if (yych == 'i') goto yy28;
	goto yy17;
yy23:
	yych = *++YYCURSOR;
	if (yych == 'c') goto yy29;
	goto yy17;
yy24:
	yych = *++YYCURSOR;
	if (yych == 'a') goto yy30;
	goto yy17;
yy25:
	yych = *++YYCURSOR;
	if (yych == 'd') goto yy31;
	goto yy17;
yy26:
	yych = *++YYCURSOR;
	if (yych == 'c') goto yy32;
	goto yy17;
yy27:
	yych = *++YYCURSOR;
	if (yych == 'a') goto yy33;
	goto yy17;
yy28:
	yych = *++YYCURSOR;
	if (yych == 't') goto yy34;
	goto yy17;
yy29:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy35;
	goto yy17;
yy30:
	yych = *++YYCURSOR;
	if (yych == 'r') goto yy36;
	goto yy17;
yy31:
	yych = *++YYCURSOR;
	if (yych == '_') goto yy38;
	goto yy17;
yy32:
	yych = *++YYCURSOR;
	if (yych == 'r') goto yy39;
	if (yych == 'w') goto yy41;
	goto yy17;
yy33:
	yych = *++YYCURSOR;
	if (yych == 'r') goto yy43;
	goto yy17;
yy34:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy45;
	goto yy17;
yy35:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy46;
	goto yy17;
yy36:
	++YYCURSOR;
#line 33 "proc_pid_io.in.c"
	{ tok = TOKEN_RCHAR; continue; }
#line 216 "proc_pid_io.c"
yy38:
	yych = *++YYCURSOR;
	if (yych == 'b') goto yy47;
	goto yy17;
yy39:
	++YYCURSOR;
#line 35 "proc_pid_io.in.c"
	{ tok = TOKEN_SYSCR; continue; }
#line 225 "proc_pid_io.c"
yy41:
	++YYCURSOR;
#line 36 "proc_pid_io.in.c"
	{ tok = TOKEN_SYSCW; continue; }
#line 230 "proc_pid_io.c"
yy43:
	++YYCURSOR;
#line 34 "proc_pid_io.in.c"
	{ tok = TOKEN_WCHAR; continue; }
#line 235 "proc_pid_io.c"
yy45:
	yych = *++YYCURSOR;
	if (yych == '_') goto yy48;
	goto yy17;
yy46:
	yych = *++YYCURSOR;
	if (yych == 'l') goto yy49;
	goto yy17;
yy47:
	yych = *++YYCURSOR;
	if (yych == 'y') goto yy50;
	goto yy17;
yy48:
	yych = *++YYCURSOR;
	if (yych == 'b') goto yy51;
	goto yy17;
yy49:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy52;
	goto yy17;
yy50:
	yych = *++YYCURSOR;
	if (yych == 't') goto yy53;
	goto yy17;
yy51:
	yych = *++YYCURSOR;
	if (yych == 'y') goto yy54;
	goto yy17;
yy52:
	yych = *++YYCURSOR;
	if (yych == 'd') goto yy55;
	goto yy17;
yy53:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy56;
	goto yy17;
yy54:
	yych = *++YYCURSOR;
	if (yych == 't') goto yy57;
	goto yy17;
yy55:
	yych = *++YYCURSOR;
	if (yych == '_') goto yy58;
	goto yy17;
yy56:
	yych = *++YYCURSOR;
	if (yych == 's') goto yy59;
	goto yy17;
yy57:
	yych = *++YYCURSOR;
	if (yych == 'e') goto yy61;
	goto yy17;
yy58:
	yych = *++YYCURSOR;
	if (yych == 'w') goto yy62;
	goto yy17;
yy59:
	++YYCURSOR;
#line 37 "proc_pid_io.in.c"
	{ tok = TOKEN_READ_BYTES; continue; }
#line 296 "proc_pid_io.c"
yy61:
	yych = *++YYCURSOR;
	if (yych == 's') goto yy63;
	goto yy17;
yy62:
	yych = *++YYCURSOR;
	if (yych == 'r') goto yy65;
	goto yy17;
yy63:
	++YYCURSOR;
#line 38 "proc_pid_io.in.c"
	{ tok = TOKEN_WRITE_BYTES; continue; }
#line 309 "proc_pid_io.c"
yy65:
	yych = *++YYCURSOR;
	if (yych != 'i') goto yy17;
	yych = *++YYCURSOR;
	if (yych != 't') goto yy17;
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy17;
	yych = *++YYCURSOR;
	if (yych != '_') goto yy17;
	yych = *++YYCURSOR;
	if (yych != 'b') goto yy17;
	yych = *++YYCURSOR;
	if (yych != 'y') goto yy17;
	yych = *++YYCURSOR;
	if (yych != 't') goto yy17;
	yych = *++YYCURSOR;
	if (yych != 'e') goto yy17;
	yych = *++YYCURSOR;
	if (yych != 's') goto yy17;
	++YYCURSOR;
#line 39 "proc_pid_io.in.c"
	{ tok = TOKEN_CANCELLED_WRITE_BYTES; continue; }
#line 332 "proc_pid_io.c"
}
#line 74 "proc_pid_io.in.c"

    }
}
