[package]
name = "bearing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "sync", "macros", "time"] }

[build-dependencies]
cbindgen = "0.28.0"

[lib]
crate-type = ["staticlib"]
