[package]
name = "bearing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "net", "io-util", "sync", "macros", "time"] }
tokio-stream = "0.1"
tonic = { workspace = true }
bearing-proto = { path = "../bearing-proto" }
hyper-util = "0.1"
http = "1"
tower = "0.5"

[build-dependencies]
cbindgen = "0.28.0"

[lib]
crate-type = ["staticlib"]
