[package]
name = "otel-ledger"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
name = "otel_ledger"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bridge = { path = "../netdata-plugin/bridge" }
chrono = { workspace = true }
ferryboat = { workspace = true }
file-registry = { workspace = true }
futures = { workspace = true }
journal-common = { workspace = true }
netdata-plugin-error = { path = "../netdata-plugin/error" }
netdata-plugin-protocol = { path = "../netdata-plugin/protocol" }
netdata-plugin-types = { path = "../netdata-plugin/types" }
opendal = { workspace = true }
otel-catalog = { workspace = true }
roaring = { workspace = true }
sfst = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
uuid = { workspace = true }
wal = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]
bytesize = { workspace = true }
fst-index = { workspace = true, features = ["serde"] }
tempfile = { workspace = true }
treight = { workspace = true, features = ["roaring", "serde"] }
